import { GovernmentInvestmentSchemeRecord } from '../../types/investmentScheme';

export class MockInvestmentSchemeRepository {
  private schemes: GovernmentInvestmentSchemeRecord[] = [
    {
      id: 'pli-electronics-001',
      schemeName: 'Production Linked Incentive (PLI) Scheme for Large Scale Electronics Manufacturing',
      slug: 'pli-electronics',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'MeitY',
      implementingAuthority: 'MeitY',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Manufacturing',
      investmentPurpose: 'Promote large-scale manufacturing and investment in the electronics sector.',
      targetBeneficiary: 'Electronics manufacturers',
      description: 'The scheme provides financial incentives for incremental sales of goods manufactured in India over a base year.',
      benefits: 'Financial incentives ranging from 4% to 6% on incremental sales.',
      eligibility: 'Companies meeting specific investment and sales thresholds.',
      applicationProcess: 'Online application through the official MeitY portal.',
      documentsRequired: 'Investment proof, audited financial statements, manufacturing unit certificates.',
      officialSourceUrl: 'https://www.meity.gov.in/pli',
      mySchemeUrl: 'https://www.myscheme.gov.in/schemes/pli-electronics',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'MeitY',
      sourceType: 'Ministry',
    },
    {
      id: 'semicon-india-001',
      schemeName: 'Semicon India Programme',
      slug: 'semicon-india',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'India Semiconductor Mission (ISM)',
      implementingAuthority: 'ISM',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Semiconductors',
      investmentPurpose: 'Development of semiconductor and display manufacturing ecosystem in India.',
      targetBeneficiary: 'Semiconductor manufacturers and design companies',
      description: 'Provides fiscal support to companies engaged in Silicon Semiconductor Fabs, Display Fabs, Compound Semiconductors, and Semiconductor Design.',
      benefits: 'Financial support up to 50% of project cost for eligible applicants.',
      eligibility: 'Companies fulfilling capital investment and technology criteria.',
      applicationProcess: 'Applications submitted via the India Semiconductor Mission (ISM) portal.',
      documentsRequired: 'Project report, financial capability proof, technology roadmap.',
      officialSourceUrl: 'https://ism.gov.in/',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'ISM / MeitY',
      sourceType: 'Ministry',
    },
    {
      id: 'pm-mitra-001',
      schemeName: 'PM Mega Integrated Textile Region and Apparel (PM MITRA) Parks Scheme',
      slug: 'pm-mitra',
      ministry: 'Ministry of Textiles',
      department: 'Ministry of Textiles',
      implementingAuthority: 'Ministry of Textiles',
      level: 'Central',
      category: 'Infrastructure',
      subCategory: 'Textiles',
      investmentPurpose: 'To create world-class industrial infrastructure for textile manufacturing and investment.',
      targetBeneficiary: 'Textile manufacturing companies',
      description: 'The scheme aims to set up 7 Mega Integrated Textile Region and Apparel (PM MITRA) Parks in states with necessary infrastructure.',
      benefits: 'Development support and ecosystem infrastructure for investors.',
      eligibility: 'Manufacturing units setting up operations in the designated parks.',
      applicationProcess: 'Application through state SPV / Ministry of Textiles.',
      documentsRequired: 'Business plan, investment commitment.',
      officialSourceUrl: 'https://texmin.gov.in/pm-mitra',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'Ministry of Textiles',
      sourceType: 'Ministry',
    },
    {
      id: 'bulk-drug-parks-001',
      schemeName: 'Scheme for Promotion of Bulk Drug Parks',
      slug: 'bulk-drug-parks',
      ministry: 'Ministry of Chemicals and Fertilizers',
      department: 'Department of Pharmaceuticals',
      implementingAuthority: 'Department of Pharmaceuticals',
      level: 'Central',
      category: 'Infrastructure',
      subCategory: 'Pharmaceuticals',
      investmentPurpose: 'Promote domestic manufacturing of bulk drugs by creating world-class infrastructure.',
      targetBeneficiary: 'Bulk drug manufacturers',
      description: 'Financial assistance to states for creating common infrastructure facilities in Bulk Drug Parks.',
      benefits: 'Grant-in-aid support for infrastructure development.',
      eligibility: 'State implementing agencies and units setting up manufacturing in parks.',
      applicationProcess: 'Proposals submitted by States to the Department of Pharmaceuticals.',
      documentsRequired: 'Detailed Project Report (DPR).',
      officialSourceUrl: 'https://pharmaceuticals.gov.in/',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'Department of Pharmaceuticals',
      sourceType: 'Ministry',
    },
    {
      id: 'green-hydrogen-001',
      schemeName: 'National Green Hydrogen Mission',
      slug: 'national-green-hydrogen-mission',
      ministry: 'Ministry of New and Renewable Energy',
      department: 'MNRE',
      implementingAuthority: 'MNRE',
      level: 'Central',
      category: 'Sector Incentives',
      subCategory: 'Renewable Energy',
      investmentPurpose: 'Make India a global hub for production, utilization, and export of Green Hydrogen.',
      targetBeneficiary: 'Green Hydrogen producers',
      description: 'Incentives for production of green hydrogen and for development of supply chain.',
      benefits: 'Financial incentives for production of Green Hydrogen and its derivatives.',
      eligibility: 'Manufacturers producing green hydrogen meeting specific standards.',
      applicationProcess: 'Guidelines released periodically by MNRE.',
      documentsRequired: 'Project feasibility, production records.',
      officialSourceUrl: 'https://mnre.gov.in/green-hydrogen-mission',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'MNRE',
      sourceType: 'Ministry',
    },
    {
      id: 'pli-auto-001',
      schemeName: 'Production Linked Incentive (PLI) Scheme for Automobile and Auto Component Industry',
      slug: 'pli-automobile',
      ministry: 'Ministry of Heavy Industries',
      department: 'Ministry of Heavy Industries',
      implementingAuthority: 'Ministry of Heavy Industries',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Automobile',
      investmentPurpose: 'To enhance India’s manufacturing capabilities for Advanced Automotive Products.',
      targetBeneficiary: 'Automotive and auto component manufacturers',
      description: 'Provides incentives for sales of Advanced Automotive Technology (AAT) products manufactured in India.',
      benefits: 'Incentives based on incremental sales of AAT products.',
      eligibility: 'Automotive and auto component companies meeting turnover and investment thresholds.',
      applicationProcess: 'Online application through the Ministry of Heavy Industries portal.',
      documentsRequired: 'Financial statements, investment proofs, AAT certification.',
      officialSourceUrl: 'https://heavyindustries.gov.in/',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'Ministry of Heavy Industries',
      sourceType: 'Ministry',
    },
    {
      id: 'pli-acc-001',
      schemeName: 'National Programme on Advanced Chemistry Cell (ACC) Battery Storage',
      slug: 'pli-acc',
      ministry: 'Ministry of Heavy Industries',
      department: 'Ministry of Heavy Industries',
      implementingAuthority: 'Ministry of Heavy Industries',
      level: 'Central',
      category: 'Sector Incentives',
      subCategory: 'Energy Storage',
      investmentPurpose: 'Promote manufacturing of Advanced Chemistry Cell (ACC) battery storage in India.',
      targetBeneficiary: 'Battery manufacturers',
      description: 'Provides incentives for setting up domestic manufacturing for ACC batteries.',
      benefits: 'Production-linked financial incentives.',
      eligibility: 'Companies committing to set up manufacturing facility with specified capacity.',
      applicationProcess: 'Competitive bidding process through the Ministry of Heavy Industries.',
      documentsRequired: 'Technical and financial bids.',
      officialSourceUrl: 'https://heavyindustries.gov.in/',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'Ministry of Heavy Industries',
      sourceType: 'Ministry',
    },
    {
      id: 'pm-edrive-001',
      schemeName: 'PM Electric Drive Revolution in Innovative Vehicle Enhancement (PM E-DRIVE) Scheme',
      slug: 'pm-edrive',
      ministry: 'Ministry of Heavy Industries',
      department: 'Ministry of Heavy Industries',
      implementingAuthority: 'Ministry of Heavy Industries',
      level: 'Central',
      category: 'Sector Incentives',
      subCategory: 'Electric Vehicles',
      investmentPurpose: 'Support adoption of Electric Vehicles (EVs) and develop EV infrastructure.',
      targetBeneficiary: 'EV manufacturers and users',
      description: 'Subsidy support for electric vehicles and installation of charging infrastructure.',
      benefits: 'Demand incentives for EV adoption.',
      eligibility: 'EV manufacturers and charging station operators.',
      applicationProcess: 'As per scheme guidelines on Ministry of Heavy Industries portal.',
      documentsRequired: 'Manufacturer registration, EV certification.',
      officialSourceUrl: 'https://heavyindustries.gov.in/',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      sourceAuthority: 'Ministry of Heavy Industries',
      sourceType: 'Ministry',
    }
  ];

  async getAll(): Promise<GovernmentInvestmentSchemeRecord[]> {
    return this.schemes;
  }

  async getBySlug(slug: string): Promise<GovernmentInvestmentSchemeRecord | null> {
    return this.schemes.find(s => s.slug === slug) || null;
  }
}
