import { GovernmentInvestmentSchemeRecord } from '../../types/investmentScheme';

export class MockInvestmentSchemeRepository {
  private schemes: GovernmentInvestmentSchemeRecord[] = [
    {
      id: 'pli-electronics-001',
      schemeName: 'Production Linked Incentive (PLI) Scheme for Large Scale Electronics Manufacturing',
      slug: 'pli-electronics',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'MeitY',
      implementingAgency: 'MeitY',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Manufacturing',
      shortDescription: 'Financial incentives for large-scale manufacturing of electronics in India.',
      detailedDescription: 'The PLI Scheme for Large Scale Electronics Manufacturing offers financial incentives on incremental sales of goods manufactured in India over a base year. It aims to boost domestic manufacturing, increase exports, and attract large-scale global investment into the electronics value chain.',
      targetBeneficiary: 'Electronics manufacturers and companies aiming to build large-scale facilities.',
      eligibility: 'Applicants must meet specific threshold criteria regarding cumulative investment and incremental sales of eligible electronic goods as defined by the Ministry.',
      benefits: 'Financial incentives ranging from 4% to 6% of incremental sales of manufactured goods.',
      keyBenefits: [
        'Incentives of 4-6% on incremental sales over the base year',
        'Boosts domestic production capacities',
        'Attracts large-scale global electronics manufacturers',
        'Strengthens the electronics supply chain in India'
      ],
      benefitAmount: '4-6% of incremental sales',
      benefitType: 'Production Linked Incentive',
      applicationProcess: 'Online application through the official MeitY PLI portal during active windows.',
      documentsRequired: 'Investment proof, audited financial statements, manufacturing unit certifications, and compliance declarations.',
      officialSourceUrl: 'https://www.meity.gov.in/pli',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      faqItems: [
        { question: 'What is the base year?', answer: 'The base year for measuring incremental sales is generally defined as 2019-20.' },
        { question: 'What goods are covered?', answer: 'Broadly includes mobile phones and specified electronic components.' },
        { question: 'How is incentive paid?', answer: 'Based on verified incremental sales figures reported annually.' },
        { question: 'Is it open to all?', answer: 'Eligibility depends on meeting specified minimum investment and sales thresholds.' },
        { question: 'What is the scheme tenure?', answer: 'The scheme typically spans 5 years.' },
        { question: 'Can I apply anytime?', answer: 'Applications are accepted during specified windows announced by MeitY.' }
      ],
      seoTitle: 'PLI Scheme for Large Scale Electronics Manufacturing 2026',
      seoDescription: 'Understand the PLI scheme for electronics, incentive structure, and eligibility criteria to boost manufacturing in India.',
      primaryKeywords: ['PLI electronics', 'electronics manufacturing India', 'PLI scheme'],
      secondaryKeywords: ['MeitY PLI', 'electronic components manufacturing']
    },
    {
      id: 'semicon-india-001',
      schemeName: 'Semicon India Programme',
      slug: 'semicon-india',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'India Semiconductor Mission (ISM)',
      implementingAgency: 'ISM',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Semiconductors',
      shortDescription: 'Comprehensive fiscal support to develop the semiconductor and display manufacturing ecosystem in India.',
      detailedDescription: 'The Semicon India Programme provides financial support to companies investing in semiconductor fabs, display fabs, compound semiconductors, and semiconductor design, aiming to make India a global hub for electronics system design and manufacturing.',
      targetBeneficiary: 'Semiconductor manufacturers, display fabricators, and semiconductor design companies.',
      eligibility: 'Applicants must fulfill specific capital investment, technology, and financial capability criteria set by the India Semiconductor Mission (ISM).',
      benefits: 'Fiscal support covering up to 50% of the project cost for eligible semiconductor, display, and design-linked projects.',
      keyBenefits: [
        'Fiscal support up to 50% of project cost',
        'Fosters a robust domestic semiconductor ecosystem',
        'Boosts high-tech manufacturing and R&D',
        'Supports specialized design-linked incentives'
      ],
      benefitAmount: 'Up to 50% of eligible project cost',
      benefitType: 'Fiscal Support / Capital Subsidy',
      applicationProcess: 'Applications submitted via the official India Semiconductor Mission (ISM) portal; projects are evaluated based on technical and financial benchmarks.',
      documentsRequired: 'Comprehensive project report, proof of financial capability, technology roadmap, and manufacturing plans.',
      officialSourceUrl: 'https://ism.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      faqItems: [
        { question: 'Who is eligible?', answer: 'Entities setting up Silicon Fabs, Display Fabs, or compound semiconductor facilities.' },
        { question: 'What is covered?', answer: 'Semiconductor Fabs, Display Fabs, compound semiconductors, and design-linked projects.' },
        { question: 'Is support guaranteed?', answer: 'Support is subject to project evaluation against ISM benchmarks.' },
        { question: 'Does it cover design?', answer: 'Yes, specialized design-linked incentives are available.' },
        { question: 'How to apply?', answer: 'Applications are submitted through the India Semiconductor Mission (ISM) website.' },
        { question: 'Are there minimum thresholds?', answer: 'Yes, minimum technology and investment thresholds apply.' }
      ],
      seoTitle: 'Semicon India Programme 2026: Semiconductor Manufacturing Support',
      seoDescription: 'Explore the Semicon India Programme, fiscal support for fabs and design, and how it fosters high-tech manufacturing in India.',
      primaryKeywords: ['semicon india', 'semiconductor manufacturing', 'ISM'],
      secondaryKeywords: ['India Semiconductor Mission', 'chip manufacturing', 'display fabs']
    },
    {
      id: 'pm-mitra-001',
      schemeName: 'PM Mega Integrated Textile Region and Apparel (PM MITRA) Parks Scheme',
      slug: 'pm-mitra',
      ministry: 'Ministry of Textiles',
      department: 'Ministry of Textiles',
      implementingAgency: 'Ministry of Textiles',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Textiles',
      shortDescription: 'Establishment of 7 Mega Integrated Textile Region and Apparel (PM MITRA) Parks with world-class industrial infrastructure.',
      detailedDescription: 'The PM MITRA scheme aims to develop 7 mega integrated textile parks to create a "plug-and-play" ecosystem for the textile industry, reducing logistics costs and promoting large-scale manufacturing.',
      targetBeneficiary: 'Textile manufacturers and investors.',
      eligibility: 'Manufacturing units seeking to set up operations within designated PM MITRA parks.',
      benefits: 'World-class industrial infrastructure, integrated manufacturing facilities, and a competitive ecosystem for global textile competitiveness.',
      keyBenefits: [
        'Plug-and-play industrial infrastructure',
        'Integrated textile and apparel manufacturing facilities',
        'Reduced logistics and operational costs',
        'Boosts global textile competitiveness'
      ],
      benefitAmount: 'Development support and ecosystem infrastructure incentives',
      benefitType: 'Infrastructure Development Support',
      applicationProcess: 'Units apply through the state-level Special Purpose Vehicle (SPV) managing the park or directly as per Ministry of Textiles guidelines.',
      documentsRequired: 'Business plan, investment commitment letter, and operational feasibility study.',
      faqItems: [
        { question: 'What is PM MITRA?', answer: 'Mega Integrated Textile Region and Apparel Parks.' },
        { question: 'How many parks?', answer: 'The scheme aims to set up 7 parks in various states.' },
        { question: 'What is plug-and-play?', answer: 'Ready-to-use infrastructure with utilities for rapid setup.' },
        { question: 'Who manages the parks?', answer: 'Managed by state-level Special Purpose Vehicles (SPVs).' },
        { question: 'Is it for any textile unit?', answer: 'Targeted at integrated textile and apparel manufacturers.' },
        { question: 'How to invest?', answer: 'Investors apply to the specific park management/SPV.' }
      ],
      seoTitle: 'PM MITRA Parks Scheme 2026: Textile Infrastructure',
      seoDescription: 'Learn about PM MITRA Parks, the integrated textile infrastructure, and how it boosts textile manufacturing in India.',
      primaryKeywords: ['PM MITRA', 'textile parks', 'textile infrastructure'],
      secondaryKeywords: ['textile manufacturing India', 'integrated textile parks'],
      officialSourceUrl: 'https://texmin.gov.in/pm-mitra',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'bulk-drug-parks-001',
      schemeName: 'Scheme for Promotion of Bulk Drug Parks',
      slug: 'bulk-drug-parks',
      ministry: 'Ministry of Chemicals and Fertilizers',
      department: 'Department of Pharmaceuticals',
      implementingAgency: 'Department of Pharmaceuticals',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Pharmaceuticals',
      shortDescription: 'Financial assistance for creating common infrastructure facilities in Bulk Drug Parks.',
      detailedDescription: 'The Scheme for Promotion of Bulk Drug Parks provides financial assistance to states to establish common infrastructure facilities, aiming to strengthen the domestic manufacturing of Active Pharmaceutical Ingredients (APIs) and reduce dependency on imports.',
      targetBeneficiary: 'Bulk drug manufacturers and state-level implementing agencies.',
      eligibility: 'State implementing agencies and pharmaceutical units setting up manufacturing operations within the designated Bulk Drug Parks.',
      benefits: 'Grant-in-aid support for establishing essential common infrastructure facilities, such as solvent extraction and common effluent treatment plants.',
      keyBenefits: [
        'Development of common infrastructure facilities',
        'Lowered cost of manufacturing for API units',
        'Enhanced domestic pharmaceutical production capacity',
        'Reduced dependence on bulk drug imports'
      ],
      benefitAmount: 'Grant-in-aid assistance based on scheme guidelines',
      benefitType: 'Grant-in-aid / Infrastructure Support',
      applicationProcess: 'Proposals submitted by State Governments/Agencies to the Department of Pharmaceuticals for evaluation and approval.',
      documentsRequired: 'Detailed Project Report (DPR), land availability certification, and environmental clearance proofs.',
      faqItems: [
        { question: 'What is a Bulk Drug Park?', answer: 'An industrial park with common infrastructure for API manufacturing.' },
        { question: 'What is the primary objective?', answer: 'To make India self-reliant in Active Pharmaceutical Ingredients (APIs).' },
        { question: 'Who gets the grant?', answer: 'Grants are provided to State implementing agencies for infrastructure.' },
        { question: 'Is it for individual drug companies?', answer: 'Individual units benefit from the common infrastructure in the park.' },
        { question: 'How to apply?', answer: 'States submit proposals to the Dept. of Pharmaceuticals.' },
        { question: 'What infrastructure is covered?', answer: 'Includes common utility facilities like treatment plants and storage.' }
      ],
      seoTitle: 'Bulk Drug Parks Scheme 2026: API Infrastructure Support',
      seoDescription: 'Explore the Bulk Drug Parks scheme, infrastructure support for API manufacturing, and India\'s self-reliance in pharmaceuticals.',
      primaryKeywords: ['bulk drug parks', 'API manufacturing', 'pharmaceutical infrastructure'],
      secondaryKeywords: ['active pharmaceutical ingredients', 'pharma manufacturing India'],
      officialSourceUrl: 'https://pharmaceuticals.gov.in/scheme-promotion-bulk-drug-parks',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'green-hydrogen-001',
      schemeName: 'National Green Hydrogen Mission',
      slug: 'national-green-hydrogen-mission',
      ministry: 'Ministry of New and Renewable Energy',
      department: 'MNRE',
      implementingAgency: 'MNRE',
      level: 'Central',
      category: 'Green Energy / Climate',
      subCategory: 'Renewable Energy',
      shortDescription: 'National mission to position India as a global hub for Green Hydrogen production and export.',
      detailedDescription: 'The National Green Hydrogen Mission provides financial incentives to support the production of green hydrogen and the development of essential supply chain and research infrastructure, aligning with global climate goals.',
      targetBeneficiary: 'Green Hydrogen producers, renewable energy firms, and related technology suppliers.',
      eligibility: 'Manufacturers and entities producing green hydrogen or its derivatives meeting specific environmental standards defined by MNRE.',
      benefits: 'Financial incentives for production of Green Hydrogen and its derivatives, alongside support for infrastructure and innovation.',
      keyBenefits: [
        'Direct financial incentives for production',
        'Support for supply chain development',
        'Fosters innovation in green technology',
        'Aligned with India’s net-zero climate goals'
      ],
      benefitAmount: 'Variable based on production targets and mission guidelines',
      benefitType: 'Financial Incentives',
      applicationProcess: 'Guidelines and application procedures are released periodically by the Ministry of New and Renewable Energy (MNRE).',
      documentsRequired: 'Project feasibility study, production records, and adherence to Green Hydrogen standards.',
      faqItems: [
        { question: 'What is green hydrogen?', answer: 'Hydrogen produced using renewable energy sources.' },
        { question: 'What is the goal?', answer: 'To make India a global hub for green hydrogen production and export.' },
        { question: 'Is it open to everyone?', answer: 'Open to entities meeting specific production and technology standards.' },
        { question: 'What support is given?', answer: 'Financial incentives for production and supply chain development.' },
        { question: 'Is it for retail investors?', answer: 'No, this is a mission-level industrial scheme.' },
        { question: 'How is it verified?', answer: 'Based on production output and standard adherence.' }
      ],
      seoTitle: 'National Green Hydrogen Mission 2026: Industrial Support',
      seoDescription: 'Learn about the National Green Hydrogen Mission, production incentives, and India\'s move towards sustainable green energy.',
      primaryKeywords: ['green hydrogen mission', 'green hydrogen India', 'renewable energy'],
      secondaryKeywords: ['hydrogen production incentives', 'climate goals', 'clean energy'],
      officialSourceUrl: 'https://mnre.gov.in/green-hydrogen-mission',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pli-auto-001',
      schemeName: 'Production Linked Incentive (PLI) Scheme for Automobile and Auto Component Industry',
      slug: 'pli-automobile',
      ministry: 'Ministry of Heavy Industries',
      department: 'Ministry of Heavy Industries',
      implementingAgency: 'Ministry of Heavy Industries',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Automobile',
      shortDescription: 'Production-linked incentives for the manufacturing of Advanced Automotive Technology (AAT) products.',
      detailedDescription: 'The PLI Scheme for the Automobile and Auto Component Industry provides incentives for sales of Advanced Automotive Technology (AAT) products manufactured in India, promoting domestic production and innovation in the automotive sector.',
      targetBeneficiary: 'Automotive OEMs and auto component manufacturers.',
      eligibility: 'Automotive and auto component companies meeting defined turnover and investment thresholds.',
      benefits: 'Financial incentives based on incremental sales of AAT products.',
      keyBenefits: [
        'Incentives for Advanced Automotive Technology (AAT) products',
        'Encourages domestic production and investment',
        'Promotes innovation in the automotive sector',
        'Strengthens the automotive supply chain'
      ],
      benefitAmount: 'Variable based on incremental sales of AAT products',
      benefitType: 'Production Linked Incentive',
      applicationProcess: 'Online application through the Ministry of Heavy Industries portal during specified application windows.',
      documentsRequired: 'Audited financial statements, investment proofs, AAT product certifications, and compliance declarations.',
      faqItems: [
        { question: 'What is AAT?', answer: 'Advanced Automotive Technology products.' },
        { question: 'Who is eligible?', answer: 'Automotive and auto component companies meeting threshold criteria.' },
        { question: 'Is it for all auto products?', answer: 'No, it targets Advanced Automotive Technology products.' },
        { question: 'How is the incentive paid?', answer: 'Based on incremental sales figures reported annually.' },
        { question: 'What is the scheme tenure?', answer: 'The scheme spans a set number of years as defined in policy.' },
        { question: 'Where to apply?', answer: 'Through the Ministry of Heavy Industries portal.' }
      ],
      seoTitle: 'PLI Scheme for Automobile and Auto Component Industry 2026',
      seoDescription: 'Explore the PLI scheme for auto and auto components, covering eligibility, incentive structure, and its role in boosting automotive manufacturing.',
      primaryKeywords: ['PLI auto', 'auto components manufacturing', 'PLI automobile scheme'],
      secondaryKeywords: ['advanced automotive technology', 'automotive manufacturing India'],
      officialSourceUrl: 'https://pliauto.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pli-acc-001',
      schemeName: 'National Programme on Advanced Chemistry Cell (ACC) Battery Storage',
      slug: 'pli-acc',
      ministry: 'Ministry of Heavy Industries',
      department: 'Ministry of Heavy Industries',
      implementingAgency: 'Ministry of Heavy Industries',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Energy Storage',
      shortDescription: 'Incentives for setting up domestic manufacturing for Advanced Chemistry Cell (ACC) battery storage.',
      detailedDescription: 'The National Programme on ACC Battery Storage aims to promote domestic manufacturing of advanced battery storage technologies, reducing dependency on imports and fostering a robust ecosystem for electric mobility and energy storage solutions.',
      targetBeneficiary: 'Battery manufacturing companies and energy storage technology firms.',
      eligibility: 'Companies committing to set up manufacturing facilities with specified capacity and technology standards.',
      benefits: 'Production-linked financial incentives based on local value addition and manufacturing output.',
      keyBenefits: [
        'Boosts domestic manufacturing of ACC batteries',
        'Reduces import dependency for energy storage',
        'Supports the electric mobility ecosystem',
        'Encourages technology localization'
      ],
      benefitAmount: 'Variable production-linked incentives',
      benefitType: 'Production Linked Incentive',
      applicationProcess: 'Competitive bidding process managed by the Ministry of Heavy Industries.',
      documentsRequired: 'Detailed technical and financial bids, business plan, and proof of manufacturing capability.',
      faqItems: [
        { question: 'What is ACC?', answer: 'Advanced Chemistry Cell battery technology.' },
        { question: 'What is the goal?', answer: 'To make India a manufacturing hub for advanced battery storage.' },
        { question: 'Who is eligible?', answer: 'Manufacturers committing to specified production capacity.' },
        { question: 'How are incentives calculated?', answer: 'Based on local value addition and sales of manufactured ACC cells.' },
        { question: 'Is it open to all?', answer: 'Subject to competitive bidding and technology qualification.' },
        { question: 'How long is the scheme?', answer: 'Spans multiple years as specified in program guidelines.' }
      ],
      seoTitle: 'PLI Scheme for ACC Battery Storage 2026',
      seoDescription: 'Learn about the PLI scheme for ACC battery storage, domestic manufacturing incentives, and its role in the energy storage value chain.',
      primaryKeywords: ['ACC battery storage', 'PLI battery', 'advanced chemistry cell'],
      secondaryKeywords: ['battery manufacturing India', 'energy storage manufacturing'],
      officialSourceUrl: 'https://pliacc.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pm-edrive-001',
      schemeName: 'PM Electric Drive Revolution in Innovative Vehicle Enhancement (PM E-DRIVE) Scheme',
      slug: 'pm-edrive',
      ministry: 'Ministry of Heavy Industries',
      department: 'Ministry of Heavy Industries',
      implementingAgency: 'Ministry of Heavy Industries',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Electric Vehicles',
      shortDescription: 'Support for the adoption of Electric Vehicles (EVs) and development of EV charging infrastructure.',
      detailedDescription: 'The PM E-DRIVE scheme provides demand incentives for electric vehicle adoption and financial support for installing charging infrastructure, aiming to accelerate the transition to sustainable electric mobility.',
      targetBeneficiary: 'EV manufacturers, charging station operators, and EV buyers.',
      eligibility: 'EV manufacturers meeting specific performance/certification standards and charging station operators.',
      benefits: 'Direct demand incentives for EVs and capital support for EV charging station deployment.',
      keyBenefits: [
        'Direct demand incentives for faster EV adoption',
        'Support for robust EV charging infrastructure',
        'Accelerates electric mobility transition',
        'Promotes innovation in EV components'
      ],
      benefitAmount: 'Variable based on demand incentives and deployment targets',
      benefitType: 'Demand Incentive / Subsidy',
      applicationProcess: 'As per scheme guidelines on the Ministry of Heavy Industries portal.',
      documentsRequired: 'Manufacturer registration, EV certification, and charging station site details.',
      faqItems: [
        { question: 'What is PM E-DRIVE?', answer: 'Scheme to promote EV adoption and charging infrastructure.' },
        { question: 'Who is covered?', answer: 'EV manufacturers and charging infrastructure operators.' },
        { question: 'Is it for retail users?', answer: 'Direct demand incentives facilitate lower prices for retail buyers.' },
        { question: 'How to apply?', answer: 'Follow registration steps on the Ministry of Heavy Industries portal.' },
        { question: 'Are charging stations supported?', answer: 'Yes, financial support is available for deployment.' },
        { question: 'What is the goal?', answer: 'To accelerate adoption of sustainable electric mobility.' }
      ],
      seoTitle: 'PM E-DRIVE Scheme 2026: Electric Vehicle Support',
      seoDescription: 'Explore the PM E-DRIVE scheme, demand incentives for EVs, charging infrastructure support, and India\'s electric mobility transition.',
      primaryKeywords: ['PM E-DRIVE', 'electric vehicles', 'EV subsidy India'],
      secondaryKeywords: ['EV infrastructure', 'electric mobility adoption'],
      officialSourceUrl: 'https://edrive.heavyindustries.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pli-food-processing-001',
      schemeName: 'Production Linked Incentive (PLI) Scheme for Food Processing Industry',
      slug: 'pli-food-processing',
      ministry: 'Ministry of Food Processing Industries',
      department: 'MoFPI',
      implementingAgency: 'MoFPI',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Food Processing',
      shortDescription: 'Production-linked incentives to boost food processing capacities and international brand awareness.',
      detailedDescription: 'The PLI scheme for the Food Processing Industry provides financial incentives for boosting processing capacities, supporting innovation, and enhancing brand awareness of Indian food products in international markets.',
      targetBeneficiary: 'Food processing companies and manufacturers.',
      eligibility: 'Applicants must meet specified investment and incremental sales thresholds in eligible food product categories.',
      benefits: 'Financial incentives based on incremental sales of manufactured food products.',
      keyBenefits: [
        'Incentives for scaling food manufacturing',
        'Supports building Indian food brands globally',
        'Enhances export competitiveness',
        'Promotes value addition in agriculture'
      ],
      benefitAmount: 'Variable based on incremental sales in eligible segments',
      benefitType: 'Production Linked Incentive',
      applicationProcess: 'Online application through the Ministry of Food Processing Industries (MoFPI) portal during open calls.',
      documentsRequired: 'Audited financial statements, investment proofs, and product certifications.',
      faqItems: [
        { question: 'What is the goal?', answer: 'To create global food manufacturing champions.' },
        { question: 'Which products?', answer: 'Includes segments like ready-to-eat, marine products, and fruits/vegetables.' },
        { question: 'How to apply?', answer: 'Submit applications through the MoFPI portal.' },
        { question: 'Are there thresholds?', answer: 'Yes, investment and sales thresholds must be met.' },
        { question: 'How is incentive calculated?', answer: 'Based on incremental sales reported annually.' },
        { question: 'Is it for startups?', answer: 'Targeted at scaling up existing manufacturing operations.' }
      ],
      seoTitle: 'PLI Scheme for Food Processing Industry 2026',
      seoDescription: 'Understand the PLI scheme for the food processing industry, incentives for manufacturing champions, and export competitiveness.',
      primaryKeywords: ['PLI food processing', 'food manufacturing incentives', 'MoFPI PLI'],
      secondaryKeywords: ['food processing India', 'export manufacturing'],
      officialSourceUrl: 'https://mofpi.gov.in/pli-scheme-food-processing-industry',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pli-white-goods-001',
      schemeName: 'Production Linked Incentive (PLI) Scheme for White Goods',
      slug: 'pli-white-goods',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'DPIIT',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'White Goods',
      shortDescription: 'Incentives to promote domestic manufacturing of air-conditioners and LED components.',
      detailedDescription: 'The PLI Scheme for White Goods provides incentives on incremental sales for manufacturers of air-conditioner components and LED lighting products to boost local value addition and domestic manufacturing capabilities.',
      targetBeneficiary: 'Manufacturers of air-conditioners, LED lighting, and related components.',
      eligibility: 'Manufacturing entities complying with Department for Promotion of Industry and Internal Trade (DPIIT) guidelines regarding investment and manufacturing thresholds.',
      benefits: 'Financial incentives based on incremental sales of eligible manufactured goods.',
      keyBenefits: [
        'Boosts domestic production of ACs and LEDs',
        'Enhances component manufacturing ecosystems',
        'Promotes local value addition',
        'Reduces reliance on imported components'
      ],
      benefitAmount: 'Incentives ranging from 4% to 6% based on incremental sales',
      benefitType: 'Production Linked Incentive',
      applicationProcess: 'Online application on the DPIIT portal during announced windows.',
      documentsRequired: 'Detailed business plan, proof of investment, and manufacturing capabilities.',
      faqItems: [
        { question: 'What are white goods?', answer: 'Targeted products like AC components and LED lighting.' },
        { question: 'What is the goal?', answer: 'To build domestic manufacturing capacity.' },
        { question: 'Who is eligible?', answer: 'Manufacturing entities meeting DPIIT investment thresholds.' },
        { question: 'What support is provided?', answer: 'Financial incentives on incremental sales.' },
        { question: 'How to apply?', answer: 'Apply through the official DPIIT portal.' },
        { question: 'Is it for all manufacturers?', answer: 'Eligibility depends on meeting specified manufacturing criteria.' }
      ],
      seoTitle: 'PLI Scheme for White Goods (ACs & LEDs) 2026',
      seoDescription: 'Explore the PLI scheme for white goods, manufacturing incentives for AC components and LEDs, and building domestic value chains.',
      primaryKeywords: ['PLI white goods', 'AC manufacturing PLI', 'LED component manufacturing'],
      secondaryKeywords: ['DPIIT PLI', 'domestic value addition'],
      officialSourceUrl: 'https://dpiit.gov.in/pli-scheme-white-goods',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification against recent policy shifts.'
    },
    {
      id: 'medical-device-parks-001',
      schemeName: 'Scheme for Promotion of Medical Device Parks',
      slug: 'medical-device-parks',
      ministry: 'Ministry of Chemicals and Fertilizers',
      department: 'Department of Pharmaceuticals',
      implementingAgency: 'Department of Pharmaceuticals',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Medical Devices',
      shortDescription: 'Promotion of domestic manufacturing through creation of common infrastructure for medical device parks.',
      detailedDescription: 'This scheme supports states in creating common infrastructure facilities for medical device manufacturing parks, aimed at reducing manufacturing costs and enhancing the competitiveness of the domestic medical device sector.',
      targetBeneficiary: 'Medical device manufacturing companies and state-level agencies.',
      eligibility: 'State governments/Implementing agencies setting up medical device parks with shared infrastructure.',
      benefits: 'Financial assistance for the development of essential common infrastructure facilities, such as testing labs and effluent treatment plants.',
      keyBenefits: [
        'Development of common utility infrastructure',
        'Reduced cost of setting up manufacturing units',
        'Enhances domestic medical device manufacturing capacity',
        'Promotes self-reliance in high-end medical devices'
      ],
      benefitAmount: 'Financial assistance based on scheme guidelines',
      benefitType: 'Financial Assistance / Infrastructure Support',
      applicationProcess: 'State agencies submit proposals to the Department of Pharmaceuticals for review and approval.',
      documentsRequired: 'Detailed Project Report (DPR), proof of land availability, and utility infrastructure plans.',
      faqItems: [
        { question: 'What is the goal?', answer: 'To foster a competitive ecosystem for medical device manufacturing.' },
        { question: 'Who is the applicant?', answer: 'State governments or designated agencies.' },
        { question: 'How does this help me?', answer: 'Reduces operational costs for individual companies in the park.' },
        { question: 'Are all devices covered?', answer: 'Focuses on building an ecosystem for all-round manufacturing.' },
        { question: 'How is it managed?', answer: 'States manage the park infrastructure development.' },
        { question: 'What infrastructure is included?', answer: 'Testing centers, treatment facilities, and shared utilities.' }
      ],
      seoTitle: 'Medical Device Parks Scheme 2026: Infrastructure Support',
      seoDescription: 'Learn about the Medical Device Parks scheme, infrastructure support for manufacturing facilities, and building domestic capacity.',
      primaryKeywords: ['medical device parks', 'manufacturing medical devices', 'pharma infrastructure'],
      secondaryKeywords: ['domestic medical devices', 'shared infrastructure'],
      officialSourceUrl: 'https://pharmaceuticals.gov.in/scheme-promotion-medical-device-parks',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification against recent policy shifts.'
    },
    {
      id: 'aif-001',
      schemeName: 'Agriculture Infrastructure Fund (AIF)',
      slug: 'agriculture-infrastructure-fund',
      ministry: 'Ministry of Agriculture and Farmers Welfare',
      department: 'Department of Agriculture and Farmers Welfare',
      implementingAgency: 'DA&FW',
      level: 'Central',
      category: 'Agriculture & Allied',
      subCategory: 'Infrastructure',
      shortDescription: 'Debt financing facility for investment in viable agricultural infrastructure projects.',
      detailedDescription: 'The Agriculture Infrastructure Fund (AIF) provides medium to long-term debt financing with interest subvention to support viable projects for post-harvest management, community farming, and modern agricultural infrastructure.',
      targetBeneficiary: 'Farmers, Agri-entrepreneurs, FPOs, Cooperatives, and Agri-tech startups.',
      eligibility: 'Entities including farmers, farmer producer organizations (FPOs), cooperatives, and agri-entrepreneurs proposing viable infrastructure projects.',
      benefits: '3% interest subvention per annum for up to 7 years on loans up to specific limits, supported by credit guarantee coverage.',
      keyBenefits: [
        '3% interest subvention for 7 years',
        'Credit guarantee support',
        'Facilitates post-harvest management',
        'Supports community farming infrastructure'
      ],
      benefitAmount: '3% interest subvention',
      benefitType: 'Interest Subvention',
      applicationProcess: 'Eligible borrowers apply through the official AIF portal or designated lending banks.',
      documentsRequired: 'Detailed Project Report (DPR), land documentation, KYC, and financial projections.',
      faqItems: [
        { question: 'What is AIF?', answer: 'Debt financing facility for agri-infrastructure projects.' },
        { question: 'Who is eligible?', answer: 'Farmers, FPOs, agri-entrepreneurs, and startups.' },
        { question: 'What is the benefit?', answer: '3% interest subvention on loans.' },
        { question: 'What projects are covered?', answer: 'Post-harvest management and community farming infrastructure.' },
        { question: 'Is it a grant?', answer: 'No, it is an interest subvention scheme on debt loans.' },
        { question: 'How to apply?', answer: 'Submit proposals on the AIF portal.' }
      ],
      seoTitle: 'Agriculture Infrastructure Fund (AIF) 2026: Financing Support',
      seoDescription: 'Understand the Agriculture Infrastructure Fund, interest subvention for agri-infrastructure projects, and financing post-harvest management.',
      primaryKeywords: ['agri infrastructure fund', 'AIF scheme', 'agricultural loans'],
      secondaryKeywords: ['post-harvest infrastructure', 'agri-entrepreneurship'],
      officialSourceUrl: 'https://agriinfra.dac.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pm-kusum-001',
      schemeName: 'PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan)',
      slug: 'pm-kusum',
      ministry: 'Ministry of New and Renewable Energy',
      department: 'MNRE',
      implementingAgency: 'State Nodal Agencies',
      level: 'Central',
      category: 'Green Energy / Climate',
      subCategory: 'Renewable Energy',
      shortDescription: 'Solarizing pumps and promoting decentralized solar power.',
      detailedDescription: 'PM-KUSUM provides energy security to farmers by solarizing agricultural pumps and promoting decentralized solar power generation in barren or fallow lands.',
      targetBeneficiary: 'Farmers',
      eligibility: 'Individual farmers, farmer groups, cooperatives, and FPOs.',
      benefits: 'Subsidy for solar pump sets and solar power plants.',
      keyBenefits: ['Solar pump subsidy', 'Decentralized power income'],
      benefitType: 'Subsidy',
      applicationProcess: 'Registration through State Nodal Agencies.',
      documentsRequired: 'Land documents, Aadhaar, Bank account.',
      officialSourceUrl: 'https://pmkusum.mnre.gov.in/',
      faqItems: [
        { question: 'What is PM-KUSUM?', answer: 'Solarization of farm irrigation pumps.' },
        { question: 'Who is eligible?', answer: 'Farmers and farmer groups.' }
      ],
      seoTitle: 'PM-KUSUM Scheme',
      seoDescription: 'Solar power for agricultural needs.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'odop-001',
      schemeName: 'One District One Product (ODOP)',
      slug: 'one-district-one-product',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'District Administration',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: 'Branding and promoting unique district products.',
      detailedDescription: 'ODOP aims to identify, promote, and brand one product from each district, fostering local entrepreneurship and socio-economic growth.',
      targetBeneficiary: 'Artisans, MSMEs',
      eligibility: 'Producers and enterprises dealing in designated district products.',
      benefits: 'Marketing, branding, and capacity building support.',
      keyBenefits: ['Marketing support', 'Product branding'],
      benefitType: 'Capacity Building',
      applicationProcess: 'Apply through district-level portals.',
      documentsRequired: 'Business registration, product origin proof.',
      officialSourceUrl: 'https://odop.gov.in/',
      faqItems: [
        { question: 'What is ODOP?', answer: 'Branding district-specific products.' },
        { question: 'How to benefit?', answer: 'Get branding and marketing support.' }
      ],
      seoTitle: 'One District One Product (ODOP) Scheme',
      seoDescription: 'Supporting local district products.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'startup-india-seed-001',
      schemeName: 'Startup India Seed Fund Scheme',
      slug: 'startup-india-seed-fund',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'DPIIT',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'Startups',
      shortDescription: 'Financial assistance for startups.',
      detailedDescription: 'Startup India Seed Fund Scheme (SISFS) provides financial assistance to startups for proof of concept, prototype development, market entry, and commercialization.',
      targetBeneficiary: 'Startups',
      eligibility: 'DPIIT recognized startups.',
      benefits: 'Grants and investments.',
      keyBenefits: ['Proof of concept funding', 'Market entry support'],
      benefitType: 'Seed Funding',
      applicationProcess: 'Apply on Startup India portal.',
      documentsRequired: 'DPIIT startup certificate, business plan.',
      officialSourceUrl: 'https://seedfund.startupindia.gov.in/',
      faqItems: [
        { question: 'What is SISFS?', answer: 'Seed fund for startups.' },
        { question: 'Who is eligible?', answer: 'DPIIT recognized startups.' }
      ],
      seoTitle: 'Startup India Seed Fund Scheme',
      seoDescription: 'Seed capital for innovative startups.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'aspire-001',
      schemeName: 'ASPIRE (A Scheme for Promoting Innovation, Rural Industry and Entrepreneurship)',
      slug: 'aspire-scheme',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'MSME',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: 'Promoting entrepreneurship in rural industries.',
      detailedDescription: 'ASPIRE sets up a network of technology centers and incubation centers to promote entrepreneurship and innovation in rural industries.',
      targetBeneficiary: 'Rural entrepreneurs',
      eligibility: 'Institutions, NGOs, Startups in rural sectors.',
      benefits: 'Support for incubation/technology centers.',
      keyBenefits: ['Incubation support', 'Technology center setup'],
      benefitType: 'Grant',
      applicationProcess: 'Apply through MSME portal.',
      documentsRequired: 'Registration docs, project proposal.',
      officialSourceUrl: 'https://aspire.msme.gov.in/',
      faqItems: [
        { question: 'What is ASPIRE?', answer: 'Promotes rural entrepreneurship.' },
        { question: 'Who is supported?', answer: 'Rural entrepreneurs and NGOs.' }
      ],
      seoTitle: 'ASPIRE Scheme',
      seoDescription: 'Supporting rural innovation.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'sfurti-001',
      schemeName: 'Scheme of Fund for Regeneration of Traditional Industries (SFURTI)',
      slug: 'sfurti-scheme',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'MSME',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: 'Regenerating traditional industries.',
      detailedDescription: 'SFURTI organizes traditional industries and artisans into clusters to improve competitiveness and ensure long-term sustainability.',
      targetBeneficiary: 'Artisans',
      eligibility: 'NGOs, State government agencies, Private institutions.',
      benefits: 'Support for infrastructure and marketing.',
      keyBenefits: ['Cluster infrastructure', 'Marketing support'],
      benefitType: 'Grant',
      applicationProcess: 'Submit through SFURTI portal.',
      documentsRequired: 'Cluster proposal, registration.',
      officialSourceUrl: 'https://sfurti.msme.gov.in/',
      faqItems: [
        { question: 'What is SFURTI?', answer: 'Cluster support for artisans.' },
        { question: 'Who can apply?', answer: 'NGOs and state agencies.' }
      ],
      seoTitle: 'SFURTI Scheme',
      seoDescription: 'Regenerating traditional industries.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'clcss-001',
      schemeName: 'Credit Linked Capital Subsidy for Technology Upgradation (CLCSS)',
      slug: 'clcss-scheme',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'Nodal Banks/Financial Institutions',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'MSME',
      shortDescription: 'MSME technology upgradation subsidy.',
      detailedDescription: 'CLCSS provides a 15% upfront capital subsidy to MSMEs to upgrade their technology and adopt improved industrial processes.',
      targetBeneficiary: 'MSMEs',
      eligibility: 'Micro and Small Enterprises.',
      benefits: '15% upfront capital subsidy.',
      keyBenefits: ['15% capital subsidy', 'Technology upgradation'],
      benefitType: 'Subsidy',
      applicationProcess: 'Through Nodal Banks/FIs.',
      documentsRequired: 'Udyam Registration, Quotations.',
      officialSourceUrl: 'https://clcss.dcmsme.gov.in/',
      faqItems: [
        { question: 'What is CLCSS?', answer: 'Technology subsidy for MSMEs.' },
        { question: 'Eligibility?', answer: 'Micro/Small Enterprises.' }
      ],
      seoTitle: 'CLCSS Scheme',
      seoDescription: 'Technology subsidy for MSMEs.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'epcg-001',
      schemeName: 'Export Promotion Capital Goods (EPCG) Scheme',
      slug: 'epcg-scheme',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DGFT',
      implementingAgency: 'DGFT',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Manufacturing',
      shortDescription: 'Duty-free import of capital goods for export.',
      detailedDescription: 'EPCG allows manufacturers to import capital goods at 0% customs duty, provided they meet specific export obligations.',
      targetBeneficiary: 'Exporters',
      eligibility: 'Manufacturers who export products.',
      benefits: '0% customs duty on capital imports.',
      keyBenefits: ['0% duty on capital goods', 'Export facilitation'],
      benefitType: 'Duty Exemption',
      applicationProcess: 'Apply through DGFT portal.',
      documentsRequired: 'Import docs, Export obligations.',
      officialSourceUrl: 'https://dgft.gov.in/CP/?opt=epcg-scheme',
      faqItems: [
        { question: 'What is EPCG?', answer: 'Duty-free import of capital goods.' },
        { question: 'Who is eligible?', answer: 'Manufacturer exporters.' }
      ],
      seoTitle: 'EPCG Scheme',
      seoDescription: 'Import capital goods for exports.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'sitp-001',
      schemeName: 'Scheme for Integrated Textile Parks (SITP)',
      slug: 'sitp-scheme',
      ministry: 'Ministry of Textiles',
      department: 'Ministry of Textiles',
      implementingAgency: 'Ministry of Textiles',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Textiles',
      shortDescription: 'World-class infrastructure for textile units.',
      detailedDescription: 'SITP provides industrial infrastructure facilities for textile units grouped in clusters, enhancing their competitiveness.',
      targetBeneficiary: 'Textile manufacturers',
      eligibility: 'SPVs of textile manufacturing units.',
      benefits: 'Financial assistance for infrastructure development.',
      keyBenefits: ['Infrastructure grant', 'Cluster support'],
      benefitType: 'Grant',
      applicationProcess: 'Submit proposal to Ministry of Textiles.',
      documentsRequired: 'DPR, land docs.',
      officialSourceUrl: 'https://texmin.gov.in/scheme-integrated-textile-parks-sitp',
      faqItems: [
        { question: 'What is SITP?', answer: 'Textile infrastructure parks.' },
        { question: 'Who is eligible?', answer: 'Textile unit SPVs.' }
      ],
      seoTitle: 'Integrated Textile Parks Scheme (SITP)',
      seoDescription: 'World-class textile infrastructure support.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'ids-001',
      schemeName: 'Industrial Development Scheme (IDS)',
      slug: 'industrial-development-scheme',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'DPIIT',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Infrastructure & Development',
      shortDescription: 'Incentives for industrial units in specific states.',
      detailedDescription: 'The Industrial Development Scheme (IDS) promotes industrialization in specific states (e.g., Himachal Pradesh, Uttarakhand) by providing central capital investment incentives and interest subvention. It aims to encourage new industrial units and expansion of existing ones to drive economic growth.',
      targetBeneficiary: 'Industrial units',
      eligibility: 'New and expanding industrial units in specific states as per the scheme guidelines.',
      benefits: 'Central Capital Investment Incentive, Central Interest Incentive.',
      keyBenefits: ['Capital Investment Incentive', 'Interest Subvention'],
      benefitType: 'Fiscal Support / Incentive',
      applicationProcess: 'Online application through the official DPIIT portal. Detailed guidelines and timelines are updated on the portal.',
      documentsRequired: 'Business registration certificate, comprehensive project details, financial capability proof.',
      officialSourceUrl: 'https://dpiit.gov.in/schemes/industrial-development-scheme',
      faqItems: [
        { question: 'Who can apply for IDS?', answer: 'New or existing industrial units expanding in designated states.' },
        { question: 'What are the main benefits?', answer: 'Benefits include Central Capital Investment Incentive and Central Interest Incentive.' }
      ],
      seoTitle: 'Industrial Development Scheme (IDS) - Incentives for Industrial Units',
      seoDescription: 'Learn about the Industrial Development Scheme (IDS) providing investment incentives and interest subvention for industrial units in specific states.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'neids-001',
      schemeName: 'North East Industrial Development Scheme (NEIDS)',
      slug: 'neids-scheme',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'DPIIT',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Infrastructure & Development',
      shortDescription: 'Promote industrialization in the North Eastern Region.',
      detailedDescription: 'The North East Industrial Development Scheme (NEIDS) provides incentives to units in the manufacturing and service sectors in the North Eastern States to promote industrialization in the region.',
      targetBeneficiary: 'Industrial units in NER',
      eligibility: 'Manufacturing and Service sector units located in North Eastern States.',
      benefits: 'Capital investment subsidy, interest subvention, GST reimbursement.',
      keyBenefits: ['Capital investment subsidy', 'Interest subvention', 'GST reimbursement'],
      benefitType: 'Fiscal Support',
      applicationProcess: 'Apply through the official DPIIT portal. Eligibility criteria are subject to scheme notifications.',
      documentsRequired: 'Business registration, detailed project report, proof of location in NER.',
      officialSourceUrl: 'https://dpiit.gov.in/schemes/north-east-industrial-development-scheme',
      faqItems: [
        { question: 'What is NEIDS?', answer: 'An industrial promotion scheme for North Eastern States.' },
        { question: 'Which sectors are covered?', answer: 'Manufacturing and service sectors.' }
      ],
      seoTitle: 'NEIDS Scheme - Industrial Incentives for North East India',
      seoDescription: 'Explore NEIDS industrial incentives for manufacturing and service sectors in North Eastern states.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'msme-interest-sub-001',
      schemeName: 'Interest Subvention Scheme for Incremental Credit to MSMEs',
      slug: 'msme-interest-subvention',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'MSME',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: '2% interest subvention for GST-registered MSMEs.',
      detailedDescription: 'This scheme provides a 2% interest subvention on fresh or incremental loans for GST-registered MSMEs to reduce their borrowing costs.',
      targetBeneficiary: 'MSMEs',
      eligibility: 'GST-registered MSMEs.',
      benefits: '2% interest subvention on loans.',
      keyBenefits: ['Reduced interest burden', 'Supports MSME growth'],
      benefitType: 'Interest Subvention',
      applicationProcess: 'Through lending banks.',
      documentsRequired: 'GST registration, MSME registration.',
      officialSourceUrl: 'https://msme.gov.in/interest-subvention-scheme-msmes',
      faqItems: [
        { question: 'What is the subvention?', answer: '2% on incremental loans.' },
        { question: 'Eligibility?', answer: 'GST-registered MSMEs.' }
      ],
      seoTitle: 'MSME Interest Subvention Scheme',
      seoDescription: '2% interest subvention for MSMEs.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'zed-001',
      schemeName: 'ZED Certification Scheme (Zero Defect Zero Effect)',
      slug: 'zed-certification',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'QCI',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'Manufacturing',
      shortDescription: 'Quality and environmental standards certification.',
      detailedDescription: 'ZED Certification assesses MSMEs on quality standards and environmental impact, promoting "Zero Defect" and "Zero Effect" manufacturing.',
      targetBeneficiary: 'MSMEs',
      eligibility: 'MSMEs in the manufacturing sector.',
      benefits: 'Certification support, assessment fee subsidies.',
      keyBenefits: ['Quality improvement', 'Environmental standards'],
      benefitType: 'Certification Support',
      applicationProcess: 'Online through ZED portal.',
      documentsRequired: 'MSME reg, process docs.',
      officialSourceUrl: 'https://zed.msme.gov.in/',
      faqItems: [
        { question: 'What is ZED?', answer: 'Zero Defect Zero Effect certification.' },
        { question: 'Benefits?', answer: 'Subsidies and quality certification.' }
      ],
      seoTitle: 'ZED Certification Scheme',
      seoDescription: 'Promoting quality manufacturing.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pm-vishwakarma-001',
      schemeName: 'PM Vishwakarma Scheme',
      slug: 'pm-vishwakarma',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'MSME',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'Traditional Industries',
      shortDescription: 'Support for traditional artisans and craftspeople.',
      detailedDescription: 'Provides support to artisans through skill training, a tool kit incentive, and collateral-free credit support to enhance their businesses.',
      targetBeneficiary: 'Artisans',
      eligibility: 'Artisans in 18 identified trades.',
      benefits: 'Skill training, tool kit incentive, credit support.',
      keyBenefits: ['Skill training', 'Tool kit incentive', 'Collateral-free credit'],
      benefitType: 'Comprehensive Support',
      applicationProcess: 'Apply through PM Vishwakarma portal.',
      documentsRequired: 'Aadhaar, Bank details.',
      officialSourceUrl: 'https://pmvishwakarma.gov.in/',
      faqItems: [
        { question: 'Who is it for?', answer: 'Traditional artisans.' },
        { question: 'What is the support?', answer: 'Training, tools, credit.' }
      ],
      seoTitle: 'PM Vishwakarma Scheme',
      seoDescription: 'Support for traditional artisans.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pmmsy-infra-001',
      schemeName: 'Pradhan Mantri Matsya Sampada Yojana (PMMSY) - Infrastructure',
      slug: 'pmmsy-infrastructure',
      ministry: 'Ministry of Fisheries, Animal Husbandry and Dairying',
      department: 'Department of Fisheries',
      implementingAgency: 'DoF',
      level: 'Central',
      category: 'Agriculture',
      subCategory: 'Fisheries',
      shortDescription: 'Fisheries sector infrastructure development.',
      detailedDescription: 'PMMSY provides financial support for infrastructure development in fisheries, including fishing harbors, cold chains, and processing units, to enhance productivity.',
      targetBeneficiary: 'Fisheries enterprises',
      eligibility: 'Fisheries associations, entrepreneurs, state agencies.',
      benefits: 'Grants and subsidies for infrastructure.',
      keyBenefits: ['Infrastructure grants', 'Productivity enhancement'],
      benefitType: 'Grant/Subsidy',
      applicationProcess: 'Through State Fisheries Department.',
      documentsRequired: 'Project DPR, Land documents.',
      officialSourceUrl: 'https://dof.gov.in/',
      faqItems: [
        { question: 'What is PMMSY?', answer: 'Fisheries infrastructure support.' },
        { question: 'Who is eligible?', answer: 'Fisheries associations/entrepreneurs.' }
      ],
      seoTitle: 'PMMSY Fisheries Infrastructure',
      seoDescription: 'Fisheries sector infrastructure development.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'mega-food-park-001',
      schemeName: 'Mega Food Park Scheme',
      slug: 'mega-food-park',
      ministry: 'Ministry of Food Processing Industries',
      department: 'MoFPI',
      implementingAgency: 'MoFPI',
      level: 'Central',
      category: 'Infrastructure',
      subCategory: 'Food Processing',
      shortDescription: 'Creation of modern infrastructure for food processing clusters.',
      detailedDescription: 'Provides infrastructure for food processing, including collection centers, primary processing centers, and central processing centers.',
      targetBeneficiary: 'Food processors',
      eligibility: 'SPVs of food processing units.',
      benefits: 'Grant-in-aid support for infrastructure.',
      applicationProcess: 'Expression of Interest through MoFPI portal.',
      documentsRequired: 'DPR, Financial proof.',
      officialSourceUrl: 'https://mofpi.gov.in/mega-food-parks',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification of current phase/eligibility status.'
    },
    {
      id: 'agro-cluster-001',
      schemeName: 'Scheme for Creation of Infrastructure for Agro-Processing Clusters',
      slug: 'agro-processing-clusters',
      ministry: 'Ministry of Food Processing Industries',
      department: 'MoFPI',
      implementingAgency: 'MoFPI',
      level: 'Central',
      category: 'Infrastructure',
      subCategory: 'Food Processing',
      shortDescription: 'Modern infrastructure for agro-processing clusters.',
      detailedDescription: 'The Scheme for Creation of Infrastructure for Agro-Processing Clusters promotes the setting up of modern infrastructure for food processing clusters to enhance the food processing sector and reduce waste.',
      targetBeneficiary: 'Food processing entrepreneurs',
      eligibility: 'Private entrepreneurs, FPOs, Cooperatives intending to set up agro-processing clusters.',
      benefits: 'Grant-in-aid support for infrastructure.',
      keyBenefits: ['Grant-in-aid support', 'Infrastructure development'],
      benefitType: 'Grant-in-aid',
      applicationProcess: 'Through the official MoFPI portal. Subject to the latest Expression of Interest.',
      documentsRequired: 'DPR, Financial and land documents.',
      officialSourceUrl: 'https://mofpi.gov.in/scheme-creation-infrastructure-agro-processing-clusters',
      faqItems: [
        { question: 'Who can apply?', answer: 'Private entrepreneurs, FPOs, and Cooperatives.' },
        { question: 'What is the support?', answer: 'Grant-in-aid for infrastructure development.' }
      ],
      seoTitle: 'Agro-Processing Cluster Infrastructure Scheme',
      seoDescription: 'Support for creating modern infrastructure in agro-processing clusters.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'cold-chain-001',
      schemeName: 'Integrated Cold Chain and Value Addition Infrastructure',
      slug: 'integrated-cold-chain',
      ministry: 'Ministry of Food Processing Industries',
      department: 'MoFPI',
      implementingAgency: 'MoFPI',
      level: 'Central',
      category: 'Infrastructure',
      subCategory: 'Food Processing',
      shortDescription: 'Modern cold chain and value addition infrastructure.',
      detailedDescription: 'The Integrated Cold Chain and Value Addition Infrastructure scheme promotes integrated cold chain infrastructure to reduce post-harvest losses and improve food processing.',
      targetBeneficiary: 'Food processors',
      eligibility: 'Entrepreneurs, Cooperatives, FPOs involved in food processing and cold chain.',
      benefits: 'Subsidy for cold chain infrastructure development.',
      keyBenefits: ['Subsidy for cold chain infrastructure'],
      benefitType: 'Subsidy',
      applicationProcess: 'Apply through the official MoFPI portal via Expression of Interest.',
      documentsRequired: 'Detailed Project Report (DPR), financial details.',
      officialSourceUrl: 'https://mofpi.gov.in/integrated-cold-chain-and-value-addition-infrastructure',
      faqItems: [
        { question: 'What is the goal?', answer: 'Reduce post-harvest losses.' },
        { question: 'Who is eligible?', answer: 'Food processors and entrepreneurs.' }
      ],
      seoTitle: 'Integrated Cold Chain Infrastructure Scheme',
      seoDescription: 'Support for developing integrated cold chain and value addition infrastructure.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'samarth-001',
      schemeName: 'Scheme for Capacity Building in Textile Sector (SAMARTH)',
      slug: 'samarth-scheme',
      ministry: 'Ministry of Textiles',
      department: 'Ministry of Textiles',
      implementingAgency: 'Ministry of Textiles',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'Textiles',
      shortDescription: 'Skill development in the textile sector.',
      detailedDescription: 'Provides demand-driven, placement-oriented National Skills Qualifications Framework (NSQF) compliant skilling programmes.',
      targetBeneficiary: 'Textile units',
      eligibility: 'Industrial units, Training institutions.',
      benefits: 'Financial support for training and capacity building.',
      applicationProcess: 'As per Ministry of Textiles guidelines.',
      documentsRequired: 'Training plan, Institutional details.',
      officialSourceUrl: 'https://samarth-textiles.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification of current training partner onboarding status.'
    },
    {
      id: 'textile-rd-001',
      schemeName: 'Scheme for Research & Development in Textile Sector',
      slug: 'textile-rd-scheme',
      ministry: 'Ministry of Textiles',
      department: 'Ministry of Textiles',
      implementingAgency: 'Ministry of Textiles',
      level: 'Central',
      category: 'Technology / Digital Industry',
      subCategory: 'Textiles',
      shortDescription: 'Promote R&D in the textile sector.',
      detailedDescription: 'Supports research and development activities in the textile sector to improve productivity and quality.',
      targetBeneficiary: 'Textile research institutions',
      eligibility: 'Research institutions, Industry associations.',
      benefits: 'Financial grants for research projects.',
      applicationProcess: 'Proposal submission to Ministry of Textiles.',
      documentsRequired: 'Research proposal, Institutional credentials.',
      officialSourceUrl: 'https://txcindia.gov.in/Research_and_Development.aspx',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification of current open call status.'
    },
    {
      id: 'solar-mission-001',
      schemeName: 'National Solar Mission',
      slug: 'national-solar-mission',
      ministry: 'Ministry of New and Renewable Energy',
      department: 'MNRE',
      implementingAgency: 'MNRE',
      level: 'Central',
      category: 'Green Energy / Climate',
      subCategory: 'Renewable Energy',
      shortDescription: 'Promote solar energy generation.',
      detailedDescription: 'Aims to establish India as a global leader in solar energy by creating policy conditions for its diffusion across the country.',
      targetBeneficiary: 'Energy enterprises',
      eligibility: 'Solar energy developers, Consumers.',
      benefits: 'Subsidies, policy support for solar projects.',
      applicationProcess: 'As per scheme guidelines.',
      documentsRequired: 'Project details.',
      officialSourceUrl: 'https://mnre.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification of current subsidy schemes.'
    },
    {
      id: 'fame-ii-001',
      schemeName: 'Faster Adoption and Manufacturing of Hybrid & Electric Vehicles (FAME) II',
      slug: 'fame-ii-scheme',
      ministry: 'Ministry of Heavy Industries',
      department: 'Ministry of Heavy Industries',
      implementingAgency: 'Ministry of Heavy Industries',
      level: 'Central',
      category: 'Green Energy / Climate',
      subCategory: 'Electric Vehicles',
      shortDescription: 'Promote adoption of electric vehicles.',
      detailedDescription: 'Provides demand incentives for electric vehicles and supports the development of charging infrastructure.',
      targetBeneficiary: 'EV manufacturers/users',
      eligibility: 'EV manufacturers, Charging infrastructure providers.',
      benefits: 'Demand incentives for EVs.',
      applicationProcess: 'As per Ministry guidelines.',
      documentsRequired: 'Vehicle certification, manufacturer registration.',
      officialSourceUrl: 'https://heavyindustries.gov.in/',
      sourceType: 'Ministry',
      status: 'CLOSED',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
      statusNote: 'Closed, succeeded by newer initiatives.'
    },
    {
      id: 'zed-assistance-001',
      schemeName: 'Scheme for Financial Assistance to MSMEs for ZED Certification',
      slug: 'zed-financial-assistance',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'MSME',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: 'Financial assistance for ZED certification.',
      detailedDescription: 'Provides financial support to MSMEs for ZED assessment and certification.',
      targetBeneficiary: 'MSMEs',
      eligibility: 'MSMEs.',
      benefits: 'Financial assistance for assessment and certification.',
      applicationProcess: 'Online application through ZED portal.',
      documentsRequired: 'Udyam Registration.',
      officialSourceUrl: 'https://zed.msme.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED',
    },
    {
      id: 'sip-eit-001',
      schemeName: 'Support for International Patent Protection in Electronics & IT (SIP-EIT)',
      slug: 'sip-eit',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'MeitY',
      implementingAgency: 'MeitY',
      level: 'Central',
      category: 'Technology / Digital Industry',
      subCategory: 'IT',
      shortDescription: 'Financial support for international patent protection.',
      detailedDescription: 'Provides financial support to MSMEs and Startups in the electronics and IT sector for international patent protection.',
      targetBeneficiary: 'MSMEs, Startups',
      eligibility: 'MSMEs, Startups in Electronics/IT sector.',
      benefits: 'Reimbursement of expenses incurred for international patent filing.',
      applicationProcess: 'Online application through MeitY portal.',
      documentsRequired: 'Patent filing documents, Business registration.',
      officialSourceUrl: 'https://meity.gov.in/sip-eit',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification of current funding cycle.'
    },
    {
      id: 'emc-2-001',
      schemeName: 'Modified Electronics Manufacturing Clusters (EMC 2.0) Scheme',
      slug: 'emc-2-scheme',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'MeitY',
      implementingAgency: 'MeitY',
      level: 'Central',
      category: 'Infrastructure',
      subCategory: 'Electronics',
      shortDescription: 'Development of electronics manufacturing clusters.',
      detailedDescription: 'Provides support for the development of world-class infrastructure for electronics manufacturing units.',
      targetBeneficiary: 'Electronics manufacturers',
      eligibility: 'Implementing agencies/SPVs.',
      benefits: 'Financial assistance for infrastructure development in clusters.',
      applicationProcess: 'Proposals submitted to MeitY.',
      documentsRequired: 'DPR, land documents.',
      officialSourceUrl: 'https://meity.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Requires verification of current cluster application status.'
    },
    {
      id: 'pmegp-001',
      schemeName: 'Prime Minister\'s Employment Generation Programme (PMEGP)',
      slug: 'pmegp-scheme',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'KVIC',
      implementingAgency: 'KVIC',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: 'Credit-linked subsidy for new micro-enterprises.',
      detailedDescription: 'Supports setting up new micro-enterprises in non-farm sector.',
      targetBeneficiary: 'Entrepreneurs',
      eligibility: 'New entrepreneurs.',
      benefits: 'Credit-linked subsidy.',
      applicationProcess: 'Online application.',
      documentsRequired: 'Project report.',
      officialSourceUrl: 'https://kviconline.gov.in/pmegp/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'cgtmse-001',
      schemeName: 'Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)',
      slug: 'cgtmse-scheme',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'CGTMSE',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: 'Collateral-free credit to MSEs.',
      detailedDescription: 'Provides collateral-free loans to micro and small enterprises.',
      targetBeneficiary: 'Micro and small enterprises',
      eligibility: 'New and existing MSEs.',
      benefits: 'Collateral-free credit guarantee.',
      applicationProcess: 'Through member lending institutions.',
      documentsRequired: 'Business plan.',
      officialSourceUrl: 'https://www.cgtmse.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'ramp-001',
      schemeName: 'Raising and Accelerating MSME Performance (RAMP)',
      slug: 'ramp-programme',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'MSME',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'MSME',
      shortDescription: 'Support for MSME performance.',
      detailedDescription: 'World Bank assisted program to improve MSME performance.',
      targetBeneficiary: 'MSMEs',
      eligibility: 'Eligible MSMEs.',
      benefits: 'Credit access, technology support.',
      applicationProcess: 'Through MSME ministry portals.',
      documentsRequired: 'Registration docs.',
      officialSourceUrl: 'https://ramp.msme.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'mudra-001',
      schemeName: 'Pradhan Mantri MUDRA Yojana (PMMY)',
      slug: 'mudra-yojana',
      ministry: 'Ministry of Finance',
      department: 'Department of Financial Services',
      implementingAgency: 'Banks/MFIs',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'Microfinance',
      shortDescription: 'Loans for small income-generating activities.',
      detailedDescription: 'Loans up to ₹20 lakh for non-corporate, non-farm income-generating activities.',
      targetBeneficiary: 'Small businesses',
      eligibility: 'Small income-generating enterprises.',
      benefits: 'Collateral-free loans.',
      applicationProcess: 'Apply through banks.',
      documentsRequired: 'KYC, Business proof.',
      officialSourceUrl: 'https://www.mudra.org.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'stand-up-india-001',
      schemeName: 'Stand-Up India Scheme',
      slug: 'stand-up-india',
      ministry: 'Ministry of Finance',
      department: 'Department of Financial Services',
      implementingAgency: 'Banks',
      level: 'Central',
      category: 'Business & Entrepreneurship',
      subCategory: 'Inclusive Entrepreneurship',
      shortDescription: 'Loans for SC/ST/women entrepreneurs.',
      detailedDescription: 'Loans between ₹10 lakh and ₹1 crore for new enterprises by SC/ST/women.',
      targetBeneficiary: 'Women, SC/ST entrepreneurs',
      eligibility: 'SC/ST/women entrepreneurs for new enterprises.',
      benefits: 'Loans for business setup.',
      applicationProcess: 'Apply through banks.',
      documentsRequired: 'Project report.',
      officialSourceUrl: 'https://www.standupmitra.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'msme-design-001',
      schemeName: 'MSME Innovative Scheme: Design Component',
      slug: 'msme-design-scheme',
      ministry: 'Ministry of Micro, Small and Medium Enterprises',
      department: 'MSME',
      implementingAgency: 'MSME',
      level: 'Central',
      category: 'Technology',
      subCategory: 'MSME',
      shortDescription: 'Access professional design expertise.',
      detailedDescription: 'Support MSMEs to access design expertise.',
      targetBeneficiary: 'MSMEs',
      eligibility: 'Eligible MSMEs.',
      benefits: 'Financial support for design.',
      applicationProcess: 'Online application.',
      documentsRequired: 'Design proposal.',
      officialSourceUrl: 'https://innovative.msme.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'mobile-mfg-001',
      schemeName: 'Mobile Phone Manufacturing Scheme',
      slug: 'mobile-mfg-scheme',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'MeitY',
      implementingAgency: 'MeitY',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Manufacturing',
      shortDescription: 'Incentives for mobile phone production.',
      detailedDescription: 'The PLI scheme for mobile manufacturing incentivizes domestic value addition and large-scale manufacturing of mobile phones and components.',
      targetBeneficiary: 'Mobile phone manufacturers',
      eligibility: 'Manufacturers meeting capital investment and production criteria.',
      benefits: 'Production linked incentives.',
      keyBenefits: ['Production linked incentives', 'Boosts domestic manufacturing'],
      benefitType: 'PLI',
      applicationProcess: 'Apply through the official MeitY portal.',
      documentsRequired: 'Investment proof, production records.',
      officialSourceUrl: 'https://www.meity.gov.in/esdm',
      faqItems: [
        { question: 'What is the focus?', answer: 'Mobile phone manufacturing.' },
        { question: 'Who can apply?', answer: 'Manufacturers meeting criteria.' }
      ],
      seoTitle: 'PLI Scheme for Mobile Manufacturing',
      seoDescription: 'Incentives for large-scale mobile phone manufacturing in India.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW'
    },
    {
      id: 'sip-dpiit-001',
      schemeName: 'Scheme for Investment Promotion (SIP)',
      slug: 'sip-dpiit',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'DPIIT',
      level: 'Central',
      category: 'Industrial Incentives',
      subCategory: 'Investment Promotion',
      shortDescription: 'Fostering industrial collaboration and FDI.',
      detailedDescription: 'The Scheme for Investment Promotion (SIP) by DPIIT focuses on promoting 27 champion sectors to boost manufacturing and attract Foreign Direct Investment (FDI).',
      targetBeneficiary: 'Investors',
      eligibility: 'Manufacturing investors interested in champion sectors.',
      benefits: 'Investment support and promotion.',
      keyBenefits: ['Investment support', 'Promotes FDI'],
      benefitType: 'Promotion Support',
      applicationProcess: 'Through the official DPIIT portal.',
      documentsRequired: 'Detailed investment plan.',
      officialSourceUrl: 'https://dpiit.gov.in/schemes/investment-promotion',
      faqItems: [
        { question: 'What is SIP?', answer: 'Scheme for Investment Promotion.' },
        { question: 'Who is it for?', answer: 'Investors in manufacturing sectors.' }
      ],
      seoTitle: 'Investment Promotion Scheme (SIP)',
      seoDescription: 'Promoting investment and FDI in India’s manufacturing sectors.',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'c2s-001',
      schemeName: 'Chips to Startup (C2S) Programme',
      slug: 'c2s-programme',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'MeitY',
      implementingAgency: 'MeitY',
      level: 'Central',
      category: 'Technology',
      subCategory: 'Semiconductors',
      shortDescription: 'Talent development for semiconductor design.',
      detailedDescription: 'Focuses on developing talent in semiconductor design.',
      targetBeneficiary: 'Academic institutions, Startups',
      eligibility: 'Eligible institutions/startups.',
      benefits: 'Training, financial support.',
      applicationProcess: 'Apply through MeitY portal.',
      documentsRequired: 'Project proposal.',
      officialSourceUrl: 'https://www.meity.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'idex-001',
      schemeName: 'Innovations for Defence Excellence (iDEX)',
      slug: 'idex-defence',
      ministry: 'Ministry of Defence',
      department: 'Department of Defence Production',
      implementingAgency: 'DIO',
      level: 'Central',
      category: 'Technology',
      subCategory: 'Defence',
      shortDescription: 'Promote defense technology innovation.',
      detailedDescription: 'Supports startups and innovators in defense technology.',
      targetBeneficiary: 'Startups, Innovators',
      eligibility: 'Startups, MSMEs.',
      benefits: 'Grants, market access.',
      applicationProcess: 'iDEX portal.',
      documentsRequired: 'Project proposal.',
      officialSourceUrl: 'https://idex.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'tide-2-001',
      schemeName: 'TIDE 2.0 Programme',
      slug: 'tide-programme',
      ministry: 'Ministry of Electronics and Information Technology',
      department: 'MeitY',
      implementingAgency: 'MeitY',
      level: 'Central',
      category: 'Technology',
      subCategory: 'Startups',
      shortDescription: 'Incubation for technology startups.',
      detailedDescription: 'Supports tech startups with incubation and seed funding.',
      targetBeneficiary: 'Technology startups',
      eligibility: 'Tech startups.',
      benefits: 'Incubation, seed funding.',
      applicationProcess: 'Apply through TIDE portal.',
      documentsRequired: 'Business plan.',
      officialSourceUrl: 'https://meity.gov.in/tide2.0',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'export-promotion-mission-001',
      schemeName: 'Export Promotion Mission (EPM)',
      slug: 'export-promotion-mission',
      ministry: 'Ministry of Commerce and Industry',
      department: 'Department of Commerce',
      implementingAgency: 'DGFT',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Export Promotion',
      shortDescription: 'End-to-end export support.',
      detailedDescription: 'Provides support to exporters through Niryat Protsahan and Niryat Disha.',
      targetBeneficiary: 'Exporters',
      eligibility: 'Registered exporters.',
      benefits: 'Financial assistance, market access.',
      applicationProcess: 'Apply through DGFT.',
      documentsRequired: 'Export records.',
      officialSourceUrl: 'https://www.dgft.gov.in/CP/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'rodtep-001',
      schemeName: 'Remission of Duties and Taxes on Exported Products (RoDTEP)',
      slug: 'rodtep-scheme',
      ministry: 'Ministry of Commerce and Industry',
      department: 'Department of Commerce',
      implementingAgency: 'DGFT',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Export Promotion',
      shortDescription: 'Refund of embedded taxes on exports.',
      detailedDescription: 'Refunds taxes on inputs used in export products.',
      targetBeneficiary: 'Exporters',
      eligibility: 'Registered exporters.',
      benefits: 'Duty credit scrip.',
      applicationProcess: 'Automatic through shipping bill.',
      documentsRequired: 'Shipping bill.',
      officialSourceUrl: 'https://www.dgft.gov.in/CP/?opt=rodtep',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'rosctl-001',
      schemeName: 'Rebate of State and Central Taxes and Levies (RoSCTL)',
      slug: 'rosctl-scheme',
      ministry: 'Ministry of Textiles',
      department: 'Ministry of Textiles',
      implementingAgency: 'DGFT',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Textiles',
      shortDescription: 'Rebate on taxes for apparel/made-ups.',
      detailedDescription: 'Rebate on state and central taxes/levies on apparel/made-up exports.',
      targetBeneficiary: 'Apparel exporters',
      eligibility: 'Apparel/made-up exporters.',
      benefits: 'Rebate on taxes.',
      applicationProcess: 'Online DGFT portal.',
      documentsRequired: 'Export shipping bill.',
      officialSourceUrl: 'https://www.dgft.gov.in/CP/?opt=rosctl',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'duty-drawback-001',
      schemeName: 'Duty Drawback Scheme',
      slug: 'duty-drawback',
      ministry: 'Ministry of Finance',
      department: 'Department of Revenue',
      implementingAgency: 'CBIC',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Export Promotion',
      shortDescription: 'Refund of customs duty on imported inputs.',
      detailedDescription: 'Refund of customs duties paid on imported inputs used for exported products.',
      targetBeneficiary: 'Exporters',
      eligibility: 'Exporters using imported inputs.',
      benefits: 'Customs duty refund.',
      applicationProcess: 'Automatic through customs.',
      documentsRequired: 'Import/Export documents.',
      officialSourceUrl: 'https://www.cbic.gov.in/htdocs-cbec/customs/cs-act/formatted-htmls/duty-drawback',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'advance-auth-001',
      schemeName: 'Advance Authorization Scheme',
      slug: 'advance-authorization',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DGFT',
      implementingAgency: 'DGFT',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Export Promotion',
      shortDescription: 'Duty-free import for export production.',
      detailedDescription: 'Allows duty-free import of inputs for export products.',
      targetBeneficiary: 'Manufacturers exporters',
      eligibility: 'Manufacturers-exporters.',
      benefits: 'Duty-free imports.',
      applicationProcess: 'DGFT portal.',
      documentsRequired: 'Production details.',
      officialSourceUrl: 'https://www.dgft.gov.in/CP/?opt=advance-authorisation',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'msme-interest-export-001',
      schemeName: 'MSME Interest Subvention Scheme (Export)',
      slug: 'msme-interest-subvention-export',
      ministry: 'Ministry of Commerce and Industry',
      department: 'Department of Commerce',
      implementingAgency: 'Banks',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Export Promotion',
      shortDescription: 'Interest subsidy on export credit for MSMEs.',
      detailedDescription: 'Provides interest subvention on pre/post-shipment export credit for MSMEs.',
      targetBeneficiary: 'MSME exporters',
      eligibility: 'MSME exporter.',
      benefits: '2.75% interest subsidy.',
      applicationProcess: 'Through banks.',
      documentsRequired: 'Export records.',
      officialSourceUrl: 'https://www.dgft.gov.in/CP/?opt=interest-subvention',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'market-access-initiative-001',
      schemeName: 'Market Access Initiative (MAI)',
      slug: 'market-access-initiative',
      ministry: 'Ministry of Commerce and Industry',
      department: 'Department of Commerce',
      implementingAgency: 'Department of Commerce',
      level: 'Central',
      category: 'Export & Trade',
      subCategory: 'Export Promotion',
      shortDescription: 'Export promotion and market access support.',
      detailedDescription: 'Supports market research, trade fairs, and export promotion.',
      targetBeneficiary: 'Exporter associations',
      eligibility: 'Exporter associations.',
      benefits: 'Financial assistance for market access.',
      applicationProcess: 'Through DOC.',
      documentsRequired: 'Project proposal.',
      officialSourceUrl: 'https://commerce.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'bharatmala-001',
      schemeName: 'Bharatmala Pariyojana',
      slug: 'bharatmala-pariyojana',
      ministry: 'Ministry of Road Transport and Highways',
      department: 'MoRTH',
      implementingAgency: 'NHAI',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Road Transport',
      shortDescription: 'Large-scale road development.',
      detailedDescription: 'Development of economic corridors and highways.',
      targetBeneficiary: 'Logistics and transportation industry',
      eligibility: 'General.',
      benefits: 'Improved logistics infrastructure.',
      applicationProcess: 'Infrastructure projects.',
      documentsRequired: 'Infrastructure plan.',
      officialSourceUrl: 'https://morth.nic.in/bharatmala-pariyojana',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'gatishakti-001',
      schemeName: 'PM GatiShakti National Master Plan',
      slug: 'pm-gatishakti',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'DPIIT',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Logistics',
      shortDescription: 'Integrated planning for multimodal connectivity.',
      detailedDescription: 'Digital platform for integrated planning of infrastructure.',
      targetBeneficiary: 'Infrastructure developers',
      eligibility: 'General.',
      benefits: 'Logistics efficiency.',
      applicationProcess: 'As per planning guidelines.',
      documentsRequired: 'Infrastructure proposal.',
      officialSourceUrl: 'https://gati.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'amrit-bharat-001',
      schemeName: 'Amrit Bharat Station Scheme',
      slug: 'amrit-bharat-station',
      ministry: 'Ministry of Railways',
      department: 'Ministry of Railways',
      implementingAgency: 'Railways',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Railways',
      shortDescription: 'Modernization of railway stations.',
      detailedDescription: 'Upgradation and modernization of railway stations.',
      targetBeneficiary: 'Rail network users',
      eligibility: 'General.',
      benefits: 'Modern passenger amenities.',
      applicationProcess: 'Railway project.',
      documentsRequired: 'Project details.',
      officialSourceUrl: 'https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366,2758',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'pm-shri-001',
      schemeName: 'PM Schools for Rising India (PM SHRI)',
      slug: 'pm-shri',
      ministry: 'Ministry of Education',
      department: 'Department of School Education and Literacy',
      implementingAgency: 'Department of School Education',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Education',
      shortDescription: 'Upgradation of schools.',
      detailedDescription: 'Development of model schools.',
      targetBeneficiary: 'Schools',
      eligibility: 'Selected schools.',
      benefits: 'Infrastructure upgrade.',
      applicationProcess: 'Apply through MoE portal.',
      documentsRequired: 'School data.',
      officialSourceUrl: 'https://pmshrischools.education.gov.in/',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'digital-comm-001',
      schemeName: 'Digital Communication Innovation Square (DCIS)',
      slug: 'dcis-programme',
      ministry: 'Ministry of Communications',
      department: 'Department of Telecommunications',
      implementingAgency: 'DoT',
      level: 'Central',
      category: 'Technology',
      subCategory: 'Telecommunications',
      shortDescription: 'Research and commercialization in telecom.',
      detailedDescription: 'Supports research and development in 5G and network tech.',
      targetBeneficiary: 'Researchers, Startups',
      eligibility: 'Startups, researchers.',
      benefits: 'R&D grants.',
      applicationProcess: 'DoT portal.',
      documentsRequired: 'Proposal.',
      officialSourceUrl: 'https://dot.gov.in/dcis',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    },
    {
      id: 'infra-guarantee-001',
      schemeName: 'Infrastructure Risk Guarantee Fund',
      slug: 'infra-risk-guarantee',
      ministry: 'Ministry of Finance',
      department: 'Department of Financial Services',
      implementingAgency: 'DFS',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Infrastructure',
      shortDescription: 'Partial credit guarantee for infra loans.',
      detailedDescription: 'Provides guarantees on loans for infrastructure projects.',
      targetBeneficiary: 'Infrastructure developers',
      eligibility: 'Infra project developers.',
      benefits: 'Risk guarantee.',
      applicationProcess: 'As per banking guidelines.',
      documentsRequired: 'Loan application.',
      officialSourceUrl: 'https://financialservices.gov.in/',
      sourceType: 'Ministry',
      status: 'UPCOMING',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'NEEDS_REVIEW',
      statusNote: 'Proposed in budget, awaiting final guidelines.'
    },
    {
      id: 'national-logistics-001',
      schemeName: 'National Logistics Policy (NLP)',
      slug: 'national-logistics-policy',
      ministry: 'Ministry of Commerce and Industry',
      department: 'DPIIT',
      implementingAgency: 'DPIIT',
      level: 'Central',
      category: 'Infrastructure & Development',
      subCategory: 'Logistics',
      shortDescription: 'Improving logistics efficiency.',
      detailedDescription: 'Comprehensive policy to lower logistics costs.',
      targetBeneficiary: 'Logistics sector',
      eligibility: 'General.',
      benefits: 'Improved efficiency.',
      applicationProcess: 'As per policy guidelines.',
      documentsRequired: 'N/A.',
      officialSourceUrl: 'https://dpiit.gov.in/national-logistics-policy',
      sourceType: 'Ministry',
      status: 'ACTIVE',
      lastVerifiedAt: '2026-09-12',
      verificationStatus: 'VERIFIED'
    }
  ];


  async getAll(): Promise<GovernmentInvestmentSchemeRecord[]> {
    return this.schemes;
  }

  async getBySlug(slug: string): Promise<GovernmentInvestmentSchemeRecord | null> {
    return this.schemes.find(s => s.slug === slug) || null;
  }
}
