import { Investment } from '../../types/investment';
import { IInvestmentRepository } from './InvestmentRepository';

const MOCK_INVESTMENTS: Investment[] = [
  {
    id: 'ppf',
    slug: 'public-provident-fund',
    name: 'Public Provident Fund (PPF)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.1%',
    tenure: '15 Years',
    lockIn: '15 Years',
    minimumInvestment: '₹500',
    maximumInvestment: '₹1.5 Lakh',
    shortName: 'PPF',
    description: 'The Public Provident Fund (PPF) is a long-term government-backed small savings scheme in India, aimed at providing retirement security and tax-efficient wealth creation.',
    plainLanguageSummary: 'PPF is a safe, long-term savings scheme where you can invest small amounts annually to build a retirement corpus, enjoy tax-free interest, and claim tax deductions on your deposits.',
    keyBenefits: [
      'Government-backed safety',
      'Tax deduction under 80C',
      'Tax-free interest earnings (EEE)',
      'Long-term wealth creation',
      'Partial withdrawal allowed',
      'Loan facility available'
    ],
    contributionFrequency: 'Annual (min 1 deposit)',
    maturityRules: 'Matures after 15 years, extendable in blocks of 5 years.',
    withdrawalRules: 'Partial withdrawal allowed from 7th financial year onwards.',
    prematureWithdrawalRules: 'Not allowed, except in cases of death of the account holder.',
    taxBenefits: 'Deduction under Section 80C up to ₹1.5 Lakh per annum.',
    taxation: 'EEE (Exempt-Exempt-Exempt): Deposits, Interest, and Maturity amount are all tax-exempt.',
    riskInformation: 'Zero/Low (Sovereign Guaranteed)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Open an account at any authorized bank or post office branch.',
    documentsRequired: 'Identity Proof (Aadhaar/PAN), Address Proof, Passport size photos.',
    faqItems: [
      { question: 'What is the lock-in period?', answer: 'The lock-in period is 15 years, with partial withdrawal allowed after the 7th year.' },
      { question: 'Is PPF tax-free?', answer: 'Yes, PPF follows the EEE (Exempt-Exempt-Exempt) taxation regime.' },
      { question: 'Can I extend PPF?', answer: 'Yes, accounts can be extended in blocks of 5 years after maturity.' },
      { question: 'What if I miss a deposit?', answer: 'The account becomes inactive. It can be revived by paying a small penalty.' },
      { question: 'Can I take a loan?', answer: 'Yes, loans are available between the 3rd and 6th financial year.' }
    ],
    eligibility: 'Resident Indians',
    officialSource: 'India Post / Ministry of Finance / National Savings Institute (NSI)',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12'
  },
  {
    id: 'nps',
    slug: 'national-pension-system',
    name: 'National Pension System (NPS)',
    category: 'Pension',
    authority: 'PFRDA',
    status: 'ACTIVE',
    interestRate: 'Market Linked',
    tenure: 'Until 60/70 Years',
    lockIn: 'Until 60 Years',
    minimumInvestment: '₹500',
    maximumInvestment: 'No Limit',
    shortName: 'NPS',
    description: 'The National Pension System (NPS) is a voluntary, long-term retirement savings scheme regulated by the PFRDA, offering market-linked returns.',
    plainLanguageSummary: 'NPS helps you build a retirement corpus through market-linked investments. It offers tax efficiency, flexibility in asset allocation, and is portable across locations and jobs.',
    keyBenefits: [
      'Market-linked growth potential',
      'Additional tax deduction under 80CCD(1B)',
      'Low fund management charges',
      'Portability across India',
      'Flexibility in choosing investment mix',
      'Option for systematic withdrawal post-60'
    ],
    contributionFrequency: 'Flexible',
    maturityRules: 'Matures at age 60, with options for deferment up to age 75.',
    withdrawalRules: 'Partial withdrawal (up to 25%) allowed for specific purposes after 3 years.',
    prematureWithdrawalRules: 'Full withdrawal allowed only under specific conditions; otherwise 80% of corpus must be annuitized.',
    taxBenefits: 'Deduction under 80C, plus an exclusive deduction of ₹50,000 under 80CCD(1B).',
    taxation: 'EET: Contributions and interest are exempt, but annuity and lump-sum withdrawal are taxable as per slab.',
    riskInformation: 'Moderate to High (Subject to market risks)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Register online via eNPS or visit a Point of Presence (PoP) bank.',
    documentsRequired: 'Identity Proof (PAN), Address Proof, Bank account details.',
    faqItems: [
      { question: 'Is NPS return guaranteed?', answer: 'No, returns depend on the market performance of chosen investment funds.' },
      { question: 'Can I choose my asset mix?', answer: 'Yes, you can choose between Active Choice (auto-rebalancing or self) and Auto Choice.' },
      { question: 'What is Tier 1 vs Tier 2?', answer: 'Tier 1 is for retirement (restricted); Tier 2 is a flexible, withdrawable account.' },
      { question: 'Can I exit before 60?', answer: 'Yes, but strict withdrawal rules apply on how the corpus is handled.' },
      { question: 'How is the annuity provided?', answer: 'Upon maturity, a portion must be used to purchase an annuity from a PFRDA-registered service provider.' },
      { question: 'Can I continue after 60?', answer: 'Yes, NPS can be extended up to the age of 75.' }
    ],
    eligibility: '18-70 Years',
    officialSource: 'PFRDA',
    officialInformationUrl: 'https://www.npscra.nsdl.co.in',
    lastVerified: '2026-09-12',
    seoTitle: 'National Pension System (NPS) 2026: Eligibility & Benefits',
    seoDescription: 'Understand NPS eligibility, tax benefits under 80CCD(1B), and market-linked retirement planning.',
    primaryKeywords: ['NPS', 'pension', 'retirement planning'],
    secondaryKeywords: ['NPS interest', 'NPS tax benefits', 'PFRDA']
  },
  {
    id: 'nsc',
    slug: 'national-savings-certificate',
    name: 'National Savings Certificate (NSC)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.7%',
    tenure: '5 Years',
    lockIn: '5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: 'No Limit',
    shortName: 'NSC',
    description: 'The National Savings Certificate (NSC) is a fixed-income investment scheme offered by the government, providing safety and tax benefits.',
    plainLanguageSummary: 'NSC is a secure, 5-year savings plan with a fixed interest rate. It is ideal for conservative investors looking for guaranteed returns and tax savings.',
    keyBenefits: [
      'Government-backed fixed returns',
      'Tax deduction under 80C',
      'Fixed interest rate for the tenure',
      'No maximum investment limit',
      'Easy availability at Post Offices'
    ],
    contributionFrequency: 'Lump sum',
    maturityRules: 'Matures after 5 years.',
    prematureWithdrawalRules: 'Not allowed, except in cases of death of account holder or court order.',
    taxBenefits: 'Deduction under Section 80C up to ₹1.5 Lakh per annum.',
    taxation: 'Taxable: Interest earned is taxable as per individual slab, but qualifies for 80C deduction when reinvested.',
    riskInformation: 'Zero (Sovereign Guaranteed)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Apply at any post office branch.',
    documentsRequired: 'Identity Proof, Address Proof.',
    faqItems: [
      { question: 'Is NSC tax-free?', answer: 'No, interest is taxable, but the invested amount qualifies for 80C deduction.' },
      { question: 'Can I withdraw NSC early?', answer: 'No, premature withdrawal is restricted.' },
      { question: 'Is interest compounded?', answer: 'Yes, interest is compounded annually and paid at maturity.' },
      { question: 'Can I invest jointly?', answer: 'Yes, a joint account is allowed.' },
      { question: 'Are returns guaranteed?', answer: 'Yes, the interest rate is fixed at the time of purchase for the entire tenure.' },
      { question: 'Can minors invest?', answer: 'Yes, minors can be account holders.' }
    ],
    eligibility: 'Resident Indians',
    officialSource: 'India Post / National Savings Institute (NSI)',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12'
  },
  {
    id: 'kvp',
    slug: 'kisan-vikas-patra',
    name: 'Kisan Vikas Patra (KVP)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.5%',
    tenure: '115 Months',
    lockIn: '2.5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: 'No Limit',
    shortName: 'KVP',
    description: 'Kisan Vikas Patra (KVP) is a long-term fixed-income savings scheme where the invested amount doubles over a specific period.',
    plainLanguageSummary: 'KVP is a simple scheme designed to double your investment over a fixed period. It is safe, government-backed, and provides guaranteed returns.',
    keyBenefits: [
      'Guaranteed doubling of investment',
      'Government-backed security',
      'Flexibility in investment amount',
      'Easy transferability'
    ],
    contributionFrequency: 'Lump sum',
    maturityRules: 'Doubles in 115 months.',
    prematureWithdrawalRules: 'Allowed after 2.5 years of deposit.',
    taxation: 'Taxable: Interest is fully taxable as per income slab.',
    riskInformation: 'Zero (Sovereign Guaranteed)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Open at any post office branch.',
    documentsRequired: 'Identity Proof, Address Proof.',
    faqItems: [
      { question: 'When does money double?', answer: 'The investment doubles in 115 months.' },
      { question: 'Is it tax-free?', answer: 'No, interest is fully taxable.' },
      { question: 'Can I withdraw early?', answer: 'Yes, after a lock-in period of 2.5 years.' },
      { question: 'Is joint account allowed?', answer: 'Yes.' },
      { question: 'Can minors open it?', answer: 'Yes, minors can be account holders.' },
      { question: 'Are returns fixed?', answer: 'Yes, guaranteed as per the scheme terms.' }
    ],
    eligibility: 'Resident Indians',
    officialSource: 'India Post / National Savings Institute (NSI)',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12'
  },
  {
    id: 'scss',
    slug: 'senior-citizen-savings-scheme',
    name: 'Senior Citizen Savings Scheme (SCSS)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '8.2% (Jul-Sep 2026)',
    tenure: '5 Years',
    lockIn: '5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: '₹30 Lakh',
    shortName: 'SCSS',
    description: 'The Senior Citizen Savings Scheme (SCSS) is a government-backed investment product specifically for individuals aged 60 and above, offering regular interest income.',
    plainLanguageSummary: 'SCSS is a highly safe, quarterly-interest-paying scheme perfect for senior citizens to generate steady income with tax-saving benefits.',
    keyBenefits: [
      'Higher interest rates for seniors',
      'Quarterly interest payouts',
      'Government-backed safety',
      'Tax deduction under 80C',
      'Tenure of 5 years (extendable)'
    ],
    contributionFrequency: 'Lump sum (at opening)',
    maturityRules: '5 years, extendable by 3 years.',
    withdrawalRules: 'Premature closure allowed with penalty.',
    taxBenefits: 'Deduction under Section 80C up to ₹1.5 Lakh per annum.',
    taxation: 'Taxable: Interest is taxable as per income slab.',
    riskInformation: 'Zero (Sovereign Guaranteed)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Open at Post Office or authorized bank.',
    documentsRequired: 'Age proof, Identity proof, Address proof.',
    faqItems: [
      { question: 'Who can open SCSS?', answer: 'Individuals aged 60+.' },
      { question: 'How often is interest paid?', answer: 'Interest is paid quarterly.' },
      { question: 'Can I extend it?', answer: 'Yes, after 5 years, it can be extended for 3 more years.' },
      { question: 'Is interest tax-free?', answer: 'No, it is taxable.' },
      { question: 'What is the limit?', answer: 'Maximum ₹30 Lakh per individual.' },
      { question: 'Can I close it early?', answer: 'Yes, with a penalty based on time of closure.' }
    ],
    eligibility: '60+ Years',
    officialSource: 'India Post / Ministry of Finance',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12'
  },
  {
    id: 'ssa',
    slug: 'sukanya-samriddhi-account',
    name: 'Sukanya Samriddhi Account (SSA)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '8.2%',
    tenure: '21 Years',
    lockIn: 'Until girl attains 18/21 years',
    minimumInvestment: '₹250',
    maximumInvestment: '₹1.5 Lakh',
    shortName: 'SSY',
    description: 'The Sukanya Samriddhi Account (SSA) is a government-backed small savings scheme designed for the financial welfare of a girl child.',
    plainLanguageSummary: 'SSA is a secure investment for the girl child, offering high tax-free interest and long-term security to fund education or marriage expenses.',
    keyBenefits: [
      'Highest safety with sovereign guarantee',
      'Tax-free interest earnings (EEE)',
      'Tax deduction under 80C',
      'Higher interest rate compared to most savings schemes',
      'Helps secure girl child future'
    ],
    contributionFrequency: 'Annual',
    maturityRules: '21 years from account opening or upon marriage after 18.',
    withdrawalRules: 'Partial withdrawal (up to 50%) for education allowed after age 18.',
    taxBenefits: 'Deduction under Section 80C up to ₹1.5 Lakh per annum.',
    taxation: 'EEE (Exempt-Exempt-Exempt): Deposits, Interest, and Maturity amount are all tax-exempt.',
    riskInformation: 'Zero (Sovereign Guaranteed)',
    nominationRules: 'Not applicable (account is in the name of the child).',
    applicationMethod: 'Open at Post Office or authorized bank.',
    documentsRequired: 'Birth Certificate of girl child, Parent/Guardian ID.',
    faqItems: [
      { question: 'Who is eligible?', answer: 'Girl child below 10 years of age.' },
      { question: 'When does it mature?', answer: '21 years from account opening.' },
      { question: 'Can I withdraw for education?', answer: 'Yes, up to 50% for higher education after age 18.' },
      { question: 'Is interest taxable?', answer: 'No, interest earned is tax-exempt.' },
      { question: 'What if I miss a deposit?', answer: 'Account can be revived by paying penalty.' },
      { question: 'How many accounts?', answer: 'Maximum two accounts per family (three in case of twins/triplets).' }
    ],
    eligibility: 'Girl child <10 yrs',
    officialSource: 'India Post / National Savings Institute (NSI)',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12'
  },
  {
    id: 'po-rd',
    slug: 'post-office-recurring-deposit',
    name: 'Post Office Recurring Deposit (PORD)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '6.7% (Jul-Sep 2026)',
    tenure: '5 Years',
    minimumInvestment: '₹100',
    shortName: 'PORD',
    description: 'Post Office Recurring Deposit (PORD) is a savings scheme allowing monthly investments for a period of 5 years with fixed interest.',
    plainLanguageSummary: 'PORD is a disciplined savings scheme where you deposit a fixed amount every month for 5 years to build a lump sum with guaranteed interest.',
    keyBenefits: [
      'Discipline in savings',
      'Government-backed safety',
      'Flexible monthly deposit amounts',
      'Fixed interest rate',
      'Nomination facility'
    ],
    contributionFrequency: 'Monthly',
    maturityRules: 'Matures after 5 years.',
    withdrawalRules: 'Premature closure allowed after 3 years.',
    taxation: 'Taxable: Interest earned is taxable as per individual income slab.',
    riskInformation: 'Zero (Sovereign Guaranteed)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Open at Post Office branch.',
    documentsRequired: 'Identity Proof, Address Proof.',
    faqItems: [
      { question: 'What is the tenure?', answer: 'Fixed at 5 years.' },
      { question: 'How is interest calculated?', answer: 'Compounded quarterly at the applicable rate.' },
      { question: 'Can I deposit less than minimum?', answer: 'Minimum is ₹100, can be increased in multiples of ₹10.' },
      { question: 'What if I miss a monthly deposit?', answer: 'A penalty is charged; if multiple missed, the account may be discontinued.' },
      { question: 'Can I withdraw early?', answer: 'Yes, premature closure is allowed after 3 years.' },
      { question: 'Can I open a joint account?', answer: 'Yes.' }
    ],
    eligibility: 'Resident Indians',
    officialSource: 'India Post / Ministry of Finance / National Savings Institute (NSI)',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12',
    availabilityNote: 'Continuously available at post offices',
    statusNote: 'Active, rates revised quarterly',
    seoTitle: 'Post Office Recurring Deposit (PORD) 2026: Rates',
    seoDescription: 'Check Post Office RD interest rates, eligibility, and maturity rules for 2026.',
    primaryKeywords: ['Post Office RD', 'PORD', 'recurring deposit'],
    secondaryKeywords: ['RD interest rate', 'Post Office savings']
  },
  {
    id: 'po-mis',
    slug: 'post-office-mis',
    name: 'Monthly Income Scheme (MIS)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.4% (Jul-Sep 2026)',
    tenure: '5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: '₹9 Lakh (Single) / ₹15 Lakh (Joint)',
    shortName: 'MIS',
    description: 'The Post Office Monthly Income Scheme (MIS) is a stable investment option designed for individuals looking for a regular monthly income.',
    plainLanguageSummary: 'MIS is a safe government-backed investment that pays you monthly interest, providing a steady income stream for 5 years.',
    keyBenefits: [
      'Guaranteed monthly income',
      'Government-backed safety',
      'Flexible joint account options',
      'Tenure of 5 years',
      'Premature withdrawal permitted'
    ],
    contributionFrequency: 'Lump sum',
    maturityRules: 'Matures in 5 years.',
    withdrawalRules: 'Premature withdrawal allowed after 1 year with a penalty.',
    taxation: 'Taxable: Interest earned is fully taxable.',
    riskInformation: 'Zero (Sovereign Guaranteed)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Open at Post Office branch.',
    documentsRequired: 'Identity Proof, Address Proof.',
    faqItems: [
      { question: 'Is interest guaranteed?', answer: 'Yes, it is fixed by the government.' },
      { question: 'How is interest paid?', answer: 'Interest is paid monthly.' },
      { question: 'Can I withdraw early?', answer: 'Yes, after 1 year with a small penalty.' },
      { question: 'Can I open a joint account?', answer: 'Yes, joint accounts are available.' },
      { question: 'Is interest tax-free?', answer: 'No, it is taxable as per income slab.' },
      { question: 'What is the limit?', answer: '₹9 Lakh for single, ₹15 Lakh for joint account.' }
    ],
    eligibility: 'Resident Indians',
    officialSource: 'India Post / Ministry of Finance / National Savings Institute (NSI)',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12',
    availabilityNote: 'Continuously available at post offices',
    statusNote: 'Active, rates revised quarterly',
    seoTitle: 'Post Office Monthly Income Scheme (MIS) 2026',
    seoDescription: 'Get regular monthly income with the Post Office MIS. Check 7.4% interest rate and eligibility.',
    primaryKeywords: ['Post Office MIS', 'monthly income scheme', 'savings'],
    secondaryKeywords: ['MIS interest rate', 'MIS eligibility']
  },
  {
    id: 'po-sb',
    slug: 'post-office-savings-account',
    name: 'Post Office Savings Account',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'LEGACY',
    interestRate: '4.0%',
    eligibility: 'Resident Indians',
    taxation: 'Taxable (with 80TTA/TTB benefit)',
    officialSource: 'India Post',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12'
  },
  {
    id: 'po-td',
    slug: 'national-savings-time-deposit',
    name: 'National Savings Time Deposit (PO-TD)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '6.9% to 7.5% (varies by tenure, Jul-Sep 2026)',
    tenure: '1, 2, 3, 5 Years',
    minimumInvestment: '₹1000',
    shortName: 'POTD',
    description: 'Post Office Time Deposit (POTD) is a fixed-income investment scheme offered by the India Post, similar to bank fixed deposits, providing guaranteed returns.',
    plainLanguageSummary: 'POTD is a safe, government-backed fixed deposit scheme available at post offices with flexible tenure options of 1, 2, 3, and 5 years.',
    keyBenefits: [
      'Government-backed safety',
      'Flexible tenure options',
      'Guaranteed fixed returns',
      '80C benefit for 5-year deposit',
      'Nomination facility'
    ],
    contributionFrequency: 'Lump sum',
    maturityRules: 'Matures after the selected tenure (1, 2, 3, or 5 years).',
    withdrawalRules: 'Premature withdrawal allowed after 6 months.',
    taxBenefits: 'Section 80C deduction applies only to 5-year tenure deposits.',
    taxation: 'Taxable: Interest earned is taxable as per individual slab.',
    riskInformation: 'Zero (Sovereign Guaranteed)',
    nominationRules: 'Nomination facility available.',
    applicationMethod: 'Open at Post Office branch.',
    documentsRequired: 'Identity Proof, Address Proof.',
    faqItems: [
      { question: 'What are the tenure options?', answer: '1, 2, 3, and 5 years.' },
      { question: 'Is interest rate fixed?', answer: 'Yes, it is fixed at the time of opening for the entire tenure.' },
      { question: 'Can I withdraw prematurely?', answer: 'Yes, after 6 months with a penalty.' },
      { question: 'Is it tax-efficient?', answer: 'Only the 5-year deposit qualifies for 80C tax deduction.' },
      { question: 'Is it safe?', answer: 'Yes, it is backed by the Government of India.' },
      { question: 'Can I invest online?', answer: 'Available at post offices; digital banking options depend on specific post office services.' }
    ],
    eligibility: 'Resident Indians',
    officialSource: 'India Post / Ministry of Finance / National Savings Institute (NSI)',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12',
    seoTitle: 'Post Office Time Deposit (POTD) 2026: Interest Rates',
    seoDescription: 'Check Post Office Time Deposit (POTD) interest rates for different tenures and tax benefits.',
    primaryKeywords: ['Post Office Time Deposit', 'POTD', 'fixed deposit'],
    secondaryKeywords: ['POTD interest rate', 'POTD tenure', '80C tax benefit']
  },
  {
    id: 'apy',
    slug: 'atal-pension-yojana',
    name: 'Atal Pension Yojana (APY)',
    category: 'Pension',
    authority: 'PFRDA',
    status: 'ACTIVE',
    interestRate: 'Pension slabs based on contribution',
    tenure: 'Until 60',
    minimumInvestment: 'Based on age and desired pension',
    shortName: 'APY',
    description: 'Atal Pension Yojana (APY) is a government-backed pension scheme aimed at providing old-age income security to workers in the unorganized sector.',
    plainLanguageSummary: 'APY is a pension scheme where your monthly contributions lead to a guaranteed minimum monthly pension after age 60.',
    keyBenefits: [
      'Guaranteed minimum monthly pension',
      'Spouse pension benefit',
      'Government co-contribution (eligible cases)',
      'Life-long income support'
    ],
    contributionFrequency: 'Monthly/Quarterly/Half-Yearly',
    maturityRules: 'Pension starts at age 60.',
    withdrawalRules: 'Exit allowed under specific conditions (death or terminal illness).',
    taxation: 'Taxable: Contributions are eligible for tax benefits.',
    riskInformation: 'Low (Government-backed)',
    nominationRules: 'Nomination facility mandatory.',
    applicationMethod: 'Open through bank accounts.',
    documentsRequired: 'Bank account, Aadhaar.',
    faqItems: [
      { question: 'Who can join?', answer: 'Indian citizens aged 18-40.' },
      { question: 'When does pension start?', answer: 'At age 60.' },
      { question: 'What is guaranteed?', answer: 'A minimum pension slab based on your contribution plan.' },
      { question: 'Can the spouse get pension?', answer: 'Yes, in case of the subscriber\'s death.' },
      { question: 'Is exit allowed?', answer: 'Voluntary exit is permitted only under specific conditions.' },
      { question: 'How to choose pension amount?', answer: 'Based on the selected contribution slab.' }
    ],
    eligibility: '18-40 Years',
    officialSource: 'PFRDA',
    officialInformationUrl: 'https://www.npscra.nsdl.co.in',
    lastVerified: '2026-09-12',
    availabilityNote: 'Continuously available through banks',
    statusNote: 'Active for fresh subscribers',
    seoTitle: 'Atal Pension Yojana (APY) 2026: Pension Benefits',
    seoDescription: 'Understand APY pension slabs, eligibility (18-40 years), and contribution rules.',
    primaryKeywords: ['Atal Pension Yojana', 'APY', 'pension scheme'],
    secondaryKeywords: ['APY pension amount', 'APY age limit']
  },
  {
    id: 'pm-sym',
    slug: 'pm-sym',
    name: 'PM-SYM (Shram Yogi Maandhan)',
    category: 'Social Security',
    authority: 'Ministry of Labour',
    status: 'LEGACY',
    interestRate: 'Guaranteed pension',
    tenure: 'Until 60',
    eligibility: 'Unorganized workers',
    officialSource: 'Ministry of Labour',
    officialInformationUrl: 'https://labour.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'nps-vatsalya',
    slug: 'nps-vatsalya',
    name: 'NPS Vatsalya',
    category: 'Pension',
    authority: 'PFRDA',
    status: 'LEGACY',
    interestRate: 'Market Linked',
    eligibility: 'Minors',
    officialSource: 'PFRDA',
    officialInformationUrl: 'https://www.npscra.nsdl.co.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'sgb',
    slug: 'sovereign-gold-bonds',
    name: 'Sovereign Gold Bonds (SGB)',
    category: 'Gold',
    authority: 'RBI',
    status: 'DISCONTINUED',
    interestRate: '2.5% p.a.',
    tenure: '8 Years',
    lockIn: '5 Years',
    taxation: 'Taxable',
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'frsb',
    slug: 'floating-rate-savings-bonds',
    name: 'Floating Rate Savings Bonds (FRSB)',
    category: 'Government Securities',
    authority: 'RBI',
    status: 'ACTIVE',
    interestRate: 'Floating (linked to NSC rate + 0.35%)',
    tenure: '7 Years',
    minimumInvestment: '₹1000',
    shortName: 'FRSB',
    description: 'Floating Rate Savings Bonds (FRSB) are taxable savings bonds issued by the Government of India with a variable interest rate linked to the National Savings Certificate (NSC) rate.',
    plainLanguageSummary: 'FRSB is a safe, government-backed bond with a floating interest rate that is revised every six months, providing long-term security.',
    keyBenefits: [
      'Government-backed safety',
      'Floating interest rate mechanism',
      'Interest payable half-yearly',
      'Tenure of 7 years'
    ],
    availabilityNote: 'Available through authorized banks',
    statusNote: 'Active',
    faqItems: [
      { question: 'What is the interest rate?', answer: 'Floating rate linked to NSC rate + 0.35%.' },
      { question: 'How often is it revised?', answer: 'Every six months.' },
      { question: 'Is it safe?', answer: 'Yes, it is guaranteed by the Government of India.' },
      { question: 'Can I invest jointly?', answer: 'Yes.' },
      { question: 'Is interest tax-free?', answer: 'No, it is taxable.' },
      { question: 'What is the tenure?', answer: '7 years.' },
      { question: 'Is the interest rate fixed?', answer: 'No, it is a floating rate adjusted every six months.' }
    ],
    seoTitle: 'Floating Rate Savings Bonds (FRSB) 2026',
    seoDescription: 'Details on RBI Floating Rate Savings Bonds, interest rate formula, and 7-year tenure.',
    primaryKeywords: ['FRSB', 'Floating Rate Savings Bonds', 'RBI bonds'],
    secondaryKeywords: ['FRSB interest rate', 'FRSB maturity'],
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-12'
  },
  {
    id: 'epf',
    slug: 'epf',
    name: 'Employees Provident Fund (EPF)',
    category: 'EPFO',
    authority: 'EPFO',
    status: 'ACTIVE',
    interestRate: 'Declared Annually',
    taxBenefits: 'Deduction under Section 80C.',
    taxation: 'Interest is tax-exempt subject to certain limits.',
    riskInformation: 'Zero (Government backed)',
    nominationRules: 'Nomination facility mandatory.',
    applicationMethod: 'Through employer via EPFO portal.',
    documentsRequired: 'Aadhaar, UAN, PAN.',
    faqItems: [
      { question: 'Who contributes?', answer: 'Both employee and employer.' },
      { question: 'Is interest guaranteed?', answer: 'Yes, declared annually by EPFO.' },
      { question: 'Can I withdraw early?', answer: 'Yes, for specific reasons like housing or medical.' },
      { question: 'What is UAN?', answer: 'Universal Account Number for portability.' },
      { question: 'Is it tax-efficient?', answer: 'Yes, both contribution and interest (up to limits) enjoy tax benefits.' },
      { question: 'When can I fully withdraw?', answer: 'Upon retirement or 2 months after leaving employment.' },
      { question: 'Is EPF interest taxable?', answer: 'Interest is tax-exempt subject to certain limits under Income Tax rules.' }
    ],
    eligibility: 'Employees',
    officialSource: 'EPFO / Ministry of Labour',
    officialInformationUrl: 'https://www.epfindia.gov.in',
    lastVerified: '2026-09-12',
    availabilityNote: 'Mandatory for eligible employees',
    statusNote: 'Active',
    seoTitle: 'Employees Provident Fund (EPF) 2026: Benefits',
    seoDescription: 'Understand EPF contribution rules, tax benefits, and retirement saving features for employees.',
    primaryKeywords: ['EPF', 'provident fund', 'retirement savings'],
    secondaryKeywords: ['EPF interest', 'EPF withdrawal', 'EPFO']
  },
  {
    id: 'eps',
    slug: 'eps',
    name: 'Employees Pension Scheme (EPS)',
    category: 'EPFO',
    authority: 'EPFO',
    status: 'ACTIVE',
    interestRate: 'Defined benefit based on service',
    eligibility: 'Employees (EPF members)',
    officialSource: 'EPFO / Ministry of Labour',
    officialInformationUrl: 'https://www.epfindia.gov.in',
    lastVerified: '2026-09-12',
    shortName: 'EPS',
    description: 'The Employees Pension Scheme (EPS) is a defined-benefit pension scheme administered by the Employees Provident Fund Organisation (EPFO) for its members.',
    plainLanguageSummary: 'EPS provides a pension for employees upon retirement, ensuring basic income security through regular contributions made by the employer during service.',
    keyBenefits: [
      'Assured monthly pension post-retirement',
      'Family pension provision for survivors',
      'Retirement income security',
      'Administration by EPFO'
    ],
    contributionFrequency: 'Monthly (employer contribution)',
    maturityRules: 'Pension entitlement begins upon retirement at age 58.',
    withdrawalRules: 'Governed by EPFO service rules.',
    riskInformation: 'Low (EPFO/Government supported)',
    nominationRules: 'Nomination facility applicable.',
    applicationMethod: 'Managed through EPFO portal via employer.',
    faqItems: [
      { question: 'What is EPS?', answer: 'It is a pension scheme for employees providing retirement income.' },
      { question: 'Who contributes?', answer: 'The employer contributes a portion of the EPF contribution to EPS.' },
      { question: 'Can I withdraw early?', answer: 'Limited exit options based on service length.' },
      { question: 'Is it different from EPF?', answer: 'Yes, EPF is a provident fund while EPS is a pension scheme.' },
      { question: 'Is it guaranteed?', answer: 'It is an assured benefit scheme based on service.' },
      { question: 'Does it cover family?', answer: 'Yes, it provides family pension benefits.' }
    ],
    seoTitle: 'Employees Pension Scheme (EPS) 2026: Features',
    seoDescription: 'Overview of the Employees Pension Scheme (EPS), pension benefits, and eligibility rules.',
    primaryKeywords: ['EPS', 'pension scheme', 'retirement income'],
    secondaryKeywords: ['EPS benefits', 'EPS eligibility']
  },
  {
    id: 'pm-kmy',
    slug: 'pm-kisan-maandhan',
    name: 'PM-Kisan Maandhan (PM-KMY)',
    category: 'Pension',
    authority: 'Ministry of Agriculture',
    status: 'ACTIVE',
    interestRate: 'Contribution-linked guaranteed pension',
    eligibility: 'Small/Marginal Farmers',
    officialSource: 'Ministry of Agriculture',
    officialInformationUrl: 'https://maandhan.in',
    lastVerified: '2026-09-12',
    shortName: 'PM-KMY',
    description: 'PM-Kisan Maandhan (PM-KMY) is a contributory pension scheme aimed at providing old-age social security to eligible small and marginal farmers in India.',
    plainLanguageSummary: 'PM-KMY is a pension scheme where eligible small farmers make monthly contributions to receive a guaranteed minimum monthly pension after attaining age 60.',
    keyBenefits: [
      'Guaranteed minimum monthly pension of ₹3,000 post-60',
      'Old-age income support',
      'Spouse pension provision (50% of pension amount)',
      'Government-backed pension scheme'
    ],
    contributionFrequency: 'Monthly (based on age at entry)',
    maturityRules: 'Pension payout commences upon attaining age 60.',
    withdrawalRules: 'Exit allowed under specific conditions (death or terminal illness).',
    riskInformation: 'Low (Government-backed)',
    nominationRules: 'Nomination facility mandatory.',
    applicationMethod: 'Register through Common Service Centres (CSCs) or designated offices.',
    faqItems: [
      { question: 'Who is eligible?', answer: 'Small and marginal farmers aged 18 to 40 years.' },
      { question: 'What is the guaranteed pension?', answer: 'A minimum of ₹3,000 per month after age 60.' },
      { question: 'What if I die?', answer: 'Spouse is entitled to 50% of the pension amount.' },
      { question: 'How much to contribute?', answer: 'Contributions vary based on age at entry.' },
      { question: 'Is it different from PM-KISAN?', answer: 'Yes, PM-KISAN is income support while PM-KMY is a pension scheme.' },
      { question: 'Can I exit early?', answer: 'Voluntary exit is permitted only under specific conditions.' }
    ],
    seoTitle: 'PM-Kisan Maandhan (PM-KMY) 2026: Pension',
    seoDescription: 'Details on PM-Kisan Maandhan eligibility, contribution, and pension benefits for small farmers.',
    primaryKeywords: ['PM-Kisan Maandhan', 'PM-KMY', 'farmers pension'],
    secondaryKeywords: ['PM-KMY pension', 'farmers social security']
  },
  {
    id: 'rbi-retail',
    slug: 'rbi-retail-direct',
    name: 'RBI Retail Direct',
    category: 'Government Securities',
    authority: 'RBI',
    status: 'LEGACY',
    interestRate: 'Market Linked',
    eligibility: 'Resident Indians',
    officialSource: 'RBI',
    officialInformationUrl: 'https://rbiretaildirect.org.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'mahila-samman',
    slug: 'mahila-samman-savings-certificate',
    name: 'Mahila Samman Savings Certificate',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'DISCONTINUED',
    interestRate: '7.5%',
    tenure: '2 Years',
    eligibility: 'Women/Girls',
    taxation: 'Taxable',
    officialSource: 'India Post',
    officialInformationUrl: 'https://nsiindia.gov.in/',
    lastVerified: '2026-09-12'
  },
  {
    id: 'sdl',
    slug: 'state-development-loans',
    name: 'State Development Loans (SDL)',
    category: 'Government Securities',
    authority: 'RBI / State Governments',
    status: 'ACTIVE',
    interestRate: 'Market Linked (Auction based)',
    eligibility: 'Resident Indians',
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-12',
    shortName: 'SDL',
    description: 'State Development Loans (SDL) are dated securities issued by State Governments through the Reserve Bank of India (RBI) to meet their budget requirements.',
    plainLanguageSummary: 'SDLs are government-backed debt securities issued by various State Governments, offering interest payments and principal repayment guaranteed by the respective state.',
    keyBenefits: [
      'State-government backed security',
      'Market-linked interest rates',
      'Tradable in the secondary market',
      'Regular interest payouts'
    ],
    contributionFrequency: 'Market-linked (auction-based subscription)',
    maturityRules: 'Determined at the time of issuance (tenure varies).',
    withdrawalRules: 'Tradable in secondary market; no premature redemption facility directly from issuer.',
    riskInformation: 'Low (State government guarantee)',
    nominationRules: 'Nomination facility applicable.',
    applicationMethod: 'Available through secondary market/brokers or retail direct scheme.',
    faqItems: [
      { question: 'What are SDLs?', answer: 'They are debt securities issued by State Governments.' },
      { question: 'Are they safe?', answer: 'Yes, guaranteed by the respective State Government.' },
      { question: 'How is interest paid?', answer: 'Usually paid at regular intervals as per terms.' },
      { question: 'Can I sell before maturity?', answer: 'Yes, they are tradable in the secondary market.' },
      { question: 'Is interest taxable?', answer: 'Yes, interest earned is taxable as per income slab.' },
      { question: 'Where to buy?', answer: 'Available through primary auctions or secondary market via brokers.' }
    ],
    seoTitle: 'State Development Loans (SDL) 2026: Features',
    seoDescription: 'Overview of State Development Loans (SDL), auction mechanism, and investment features.',
    primaryKeywords: ['SDL', 'State Development Loans', 'govt securities'],
    secondaryKeywords: ['SDL interest rate', 'SDL investment']
  },
  {
    id: '54ec-bonds',
    slug: '54ec-capital-gains-bonds',
    name: '54EC Capital Gains Bonds',
    category: 'Government Securities',
    authority: 'NHAI / REC',
    status: 'ACTIVE',
    interestRate: 'As declared by issuing entity',
    tenure: '5 Years',
    lockIn: '5 Years',
    minimumInvestment: '₹10,000',
    eligibility: 'Resident Indians',
    taxation: 'Interest Taxable',
    taxBenefits: 'Section 54EC',
    officialSource: 'NHAI / REC',
    officialInformationUrl: 'https://nhai.gov.in',
    lastVerified: '2026-09-12',
    shortName: '54EC',
    description: '54EC Capital Gains Bonds are specified long-term bonds issued by eligible government institutions that allow investors to claim tax exemption on long-term capital gains.',
    plainLanguageSummary: 'These bonds help you save long-term capital gains tax by investing the gain amount, providing a safe, government-backed instrument with a 5-year lock-in.',
    keyBenefits: [
      'Exemption from long-term capital gains tax under Section 54EC',
      'Safe investment backed by government institutions',
      'Fixed interest-earning instrument',
      '5-year lock-in tenure'
    ],
    contributionFrequency: 'Lump sum',
    maturityRules: 'Matures after 5 years.',
    withdrawalRules: 'Non-transferable with a fixed 5-year lock-in period.',
    riskInformation: 'Low (Government-backed)',
    nominationRules: 'Nomination facility applicable.',
    applicationMethod: 'Available through issuing institutions.',
    faqItems: [
      { question: 'What is 54EC?', answer: 'It is a section of IT Act allowing tax exemption on capital gains.' },
      { question: 'What is the lock-in?', answer: 'Bonds have a fixed 5-year lock-in period.' },
      { question: 'Who issues these?', answer: 'Entities like NHAI and REC, as specified.' },
      { question: 'Is interest taxable?', answer: 'Yes, interest earned is taxable.' },
      { question: 'Can I sell before 5 years?', answer: 'No, these bonds cannot be sold before the lock-in period.' },
      { question: 'Is there a limit?', answer: 'Check current IT rules for applicable investment limits.' }
    ],
    seoTitle: '54EC Capital Gains Bonds 2026: Tax Saving',
    seoDescription: 'Learn about 54EC Capital Gains Bonds for tax saving on long-term capital gains.',
    primaryKeywords: ['54EC bonds', 'capital gains tax', 'tax saving'],
    secondaryKeywords: ['54EC lock-in', 'REC bonds']
  },
  {
    id: 'sovereign-green-bonds',
    slug: 'sovereign-green-bonds',
    name: 'Sovereign Green Bonds',
    category: 'Government Securities',
    authority: 'RBI / Ministry of Finance',
    status: 'ACTIVE',
    interestRate: 'Market Linked (Auction based)',
    eligibility: 'Resident Indians',
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-12',
    shortName: 'Green Bonds',
    description: 'Sovereign Green Bonds are debt instruments issued by the Government of India to mobilize resources for environmentally sustainable and climate-friendly projects.',
    plainLanguageSummary: 'These are government-backed securities that fund eco-friendly projects, offering safety along with market-linked returns to investors interested in sustainable development.',
    keyBenefits: [
      'Funding for environmentally sustainable projects',
      'Sovereign-backed security',
      'Market-linked yield potential',
      'Contributes to green initiative'
    ],
    contributionFrequency: 'Auction based',
    maturityRules: 'Determined at the time of issuance.',
    withdrawalRules: 'Tradable in secondary market; no premature redemption facility.',
    riskInformation: 'Low (Sovereign guarantee)',
    nominationRules: 'Nomination facility applicable.',
    applicationMethod: 'Available through primary auctions or secondary market.',
    faqItems: [
      { question: 'What is a Green Bond?', answer: 'A security issued to fund environmentally sustainable projects.' },
      { question: 'Are they safe?', answer: 'Yes, they are guaranteed by the Government of India.' },
      { question: 'How is yield determined?', answer: 'It is market-linked and determined through auction.' },
      { question: 'Who uses the funds?', answer: 'Funds are used for public sector projects aimed at reducing carbon intensity.' },
      { question: 'Is interest taxable?', answer: 'Yes, interest earned is taxable as per income slab.' },
      { question: 'Where to buy?', answer: 'Available through primary auctions or secondary market via brokers.' }
    ],
    seoTitle: 'Sovereign Green Bonds 2026: Investment',
    seoDescription: 'Overview of Sovereign Green Bonds, issuance mechanism, and environmental impact.',
    primaryKeywords: ['green bonds', 'Sovereign Green Bonds', 'RBI bonds'],
    secondaryKeywords: ['green investment', 'sustainable finance']
  },
];


export class MockInvestmentRepository implements IInvestmentRepository {
  async getAll(): Promise<Investment[]> {
    return MOCK_INVESTMENTS;
  }
  async getBySlug(slug: string): Promise<Investment | null> {
    return MOCK_INVESTMENTS.find(i => i.slug === slug) || null;
  }
  async getByCategory(category: string): Promise<Investment[]> {
    return MOCK_INVESTMENTS.filter(i => i.category === category);
  }
}
