import { Investment } from '../../types/investment';
import { IInvestmentRepository } from './InvestmentRepository';

const MOCK_INVESTMENTS: Investment[] = [
  {
    id: 'ppf',
    slug: 'public-provident-fund',
    name: 'Public Provident Fund (PPF)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.1%',
    tenure: '15 Years',
    lockIn: '15 Years',
    minimumInvestment: '₹500',
    maximumInvestment: '₹1.5 Lakh',
    eligibility: 'Resident Indians',
    taxation: 'EEE',
    taxBenefits: '80C',
    withdrawalRules: 'After 7 years',
    maturityRules: '15 Years',
    riskInformation: 'Low',
    officialSource: 'India Post / Ministry of Finance',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'nps',
    slug: 'national-pension-system',
    name: 'National Pension System (NPS)',
    category: 'Pension',
    authority: 'PFRDA',
    status: 'ACTIVE',
    interestRate: 'Market Linked',
    tenure: 'Up to 60/70 Years',
    lockIn: 'Until 60 Years',
    minimumInvestment: '₹500',
    maximumInvestment: 'No Limit',
    eligibility: '18-70 Years',
    taxation: 'EET',
    taxBenefits: '80CCD(1B)',
    withdrawalRules: 'Partial at 60',
    maturityRules: '60 Years',
    riskInformation: 'Moderate',
    officialSource: 'PFRDA',
    officialInformationUrl: 'https://www.npscra.nsdl.co.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'nsc',
    slug: 'national-savings-certificate',
    name: 'National Savings Certificate (NSC)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.7%',
    tenure: '5 Years',
    lockIn: '5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: 'No Limit',
    eligibility: 'Resident Indians',
    taxation: 'Taxable',
    taxBenefits: '80C',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'kvp',
    slug: 'kisan-vikas-patra',
    name: 'Kisan Vikas Patra (KVP)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.5%',
    tenure: '115 Months',
    lockIn: '2.5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: 'No Limit',
    eligibility: 'Resident Indians',
    taxation: 'Taxable',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'scss',
    slug: 'senior-citizen-savings-scheme',
    name: 'Senior Citizen Savings Scheme (SCSS)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '8.2%',
    tenure: '5 Years',
    lockIn: '5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: '₹30 Lakh',
    eligibility: '60+ Years',
    taxation: 'Taxable',
    taxBenefits: '80C',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'ssa',
    slug: 'sukanya-samriddhi-account',
    name: 'Sukanya Samriddhi Account (SSA)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '8.2%',
    tenure: '21 Years',
    lockIn: 'Until girl attains 18/21 years',
    minimumInvestment: '₹250',
    maximumInvestment: '₹1.5 Lakh',
    eligibility: 'Girl child <10 yrs',
    taxation: 'EEE',
    taxBenefits: '80C',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'po-rd',
    slug: 'post-office-recurring-deposit',
    name: 'Post Office Recurring Deposit (PO-RD)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '6.7%',
    tenure: '5 Years',
    minimumInvestment: '₹100',
    eligibility: 'Resident Indians',
    taxation: 'Taxable',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'po-mis',
    slug: 'post-office-mis',
    name: 'Monthly Income Scheme (MIS)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '7.4%',
    tenure: '5 Years',
    minimumInvestment: '₹1000',
    maximumInvestment: '₹9 Lakh (Single) / ₹15 Lakh (Joint)',
    eligibility: 'Resident Indians',
    taxation: 'Taxable',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'po-sb',
    slug: 'post-office-savings-account',
    name: 'Post Office Savings Account',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '4.0%',
    eligibility: 'Resident Indians',
    taxation: 'Taxable (with 80TTA/TTB benefit)',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'po-td',
    slug: 'national-savings-time-deposit',
    name: 'National Savings Time Deposit (PO-TD)',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: '6.9% - 7.5% (varies by tenure)',
    tenure: '1, 2, 3, 5 Years',
    minimumInvestment: '₹1000',
    eligibility: 'Resident Indians',
    taxation: 'Taxable',
    taxBenefits: '80C (for 5yr TD only)',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'apy',
    slug: 'atal-pension-yojana',
    name: 'Atal Pension Yojana (APY)',
    category: 'Pension',
    authority: 'PFRDA',
    status: 'ACTIVE',
    interestRate: 'Guaranteed pension',
    tenure: 'Until 60',
    eligibility: '18-40 Years',
    taxation: 'Taxable',
    officialSource: 'PFRDA',
    officialInformationUrl: 'https://www.npscra.nsdl.co.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'pm-sym',
    slug: 'pm-sym',
    name: 'PM-SYM (Shram Yogi Maandhan)',
    category: 'Social Security',
    authority: 'Ministry of Labour',
    status: 'ACTIVE',
    interestRate: 'Guaranteed pension',
    tenure: 'Until 60',
    eligibility: 'Unorganized workers',
    officialSource: 'Ministry of Labour',
    officialInformationUrl: 'https://labour.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'nps-vatsalya',
    slug: 'nps-vatsalya',
    name: 'NPS Vatsalya',
    category: 'Pension',
    authority: 'PFRDA',
    status: 'ACTIVE',
    interestRate: 'Market Linked',
    eligibility: 'Minors',
    officialSource: 'PFRDA',
    officialInformationUrl: 'https://www.npscra.nsdl.co.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'sgb',
    slug: 'sovereign-gold-bonds',
    name: 'Sovereign Gold Bonds (SGB)',
    category: 'Gold',
    authority: 'RBI',
    status: 'DISCONTINUED',
    interestRate: '2.5% p.a.',
    tenure: '8 Years',
    lockIn: '5 Years',
    taxation: 'Taxable',
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'frsb',
    slug: 'floating-rate-savings-bonds',
    name: 'Floating Rate Savings Bonds (FRSB)',
    category: 'Government Securities',
    authority: 'RBI',
    status: 'ACTIVE',
    interestRate: 'Variable',
    tenure: '7 Years',
    minimumInvestment: '₹1000',
    eligibility: 'Resident Indians',
    taxation: 'Taxable',
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'gms',
    slug: 'gold-monetisation-scheme',
    name: 'Gold Monetisation Scheme (GMS)',
    category: 'Gold',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: 'Variable',
    officialSource: 'Ministry of Finance',
    officialInformationUrl: 'https://finmin.nic.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'ups',
    slug: 'unified-pension-scheme',
    name: 'Unified Pension Scheme (UPS)',
    category: 'Pension',
    authority: 'Ministry of Finance',
    status: 'ACTIVE',
    interestRate: 'Guaranteed',
    eligibility: 'Govt Employees',
    officialSource: 'Ministry of Finance',
    officialInformationUrl: 'https://finmin.nic.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'epf',
    slug: 'epf',
    name: 'Employees Provident Fund (EPF)',
    category: 'EPFO',
    authority: 'EPFO',
    status: 'ACTIVE',
    interestRate: 'Declared Annually',
    taxBenefits: '80C',
    eligibility: 'Employees',
    officialSource: 'EPFO',
    officialInformationUrl: 'https://www.epfindia.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'eps',
    slug: 'eps',
    name: 'Employees Pension Scheme (EPS)',
    category: 'EPFO',
    authority: 'EPFO',
    status: 'ACTIVE',
    interestRate: 'Not applicable',
    eligibility: 'Employees',
    officialSource: 'EPFO',
    officialInformationUrl: 'https://www.epfindia.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'pm-kmy',
    slug: 'pm-kisan-maandhan',
    name: 'PM-Kisan Maandhan (PM-KMY)',
    category: 'Pension',
    authority: 'Ministry of Agriculture',
    status: 'ACTIVE',
    interestRate: 'Guaranteed',
    eligibility: 'Small/Marginal Farmers',
    officialSource: 'Ministry of Agriculture',
    officialInformationUrl: 'https://maandhan.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'rbi-retail',
    slug: 'rbi-retail-direct',
    name: 'RBI Retail Direct',
    category: 'Government Securities',
    authority: 'RBI',
    status: 'ACTIVE',
    interestRate: 'Market Linked',
    eligibility: 'Resident Indians',
    officialSource: 'RBI',
    officialInformationUrl: 'https://rbiretaildirect.org.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'mahila-samman',
    slug: 'mahila-samman-savings-certificate',
    name: 'Mahila Samman Savings Certificate',
    category: 'Government Savings',
    authority: 'Ministry of Finance',
    status: 'DISCONTINUED',
    interestRate: '7.5%',
    tenure: '2 Years',
    eligibility: 'Women/Girls',
    taxation: 'Taxable',
    officialSource: 'India Post',
    officialInformationUrl: 'https://www.indiapost.gov.in',
    lastVerified: '2026-09-11'
  },
  {
    id: 'sdl',
    slug: 'state-development-loans',
    name: 'State Development Loans (SDL)',
    category: 'Government Securities',
    authority: 'RBI / State Governments',
    status: 'ACTIVE',
    interestRate: 'Market Linked',
    eligibility: 'Resident Indians',
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-11'
  },
  {
    id: '54ec-bonds',
    slug: '54ec-capital-gains-bonds',
    name: '54EC Capital Gains Bonds',
    category: 'Government Securities',
    authority: 'NHAI / REC',
    status: 'ACTIVE',
    interestRate: 'As declared by issuing entity',
    tenure: '5 Years',
    lockIn: '5 Years',
    minimumInvestment: '₹10,000',
    eligibility: 'Resident Indians',
    taxation: 'Interest Taxable',
    taxBenefits: 'Section 54EC',
    officialSource: 'NHAI / REC',
    officialInformationUrl: 'https://nhai.gov.in',
    lastVerified: '2026-09-12',
    sourceLastChecked: '2026-09-12',
    sourceVerificationStatus: 'VERIFIED'
  },
  {
    id: 'sovereign-green-bonds',
    slug: 'sovereign-green-bonds',
    name: 'Sovereign Green Bonds',
    category: 'Government Securities',
    authority: 'RBI / Ministry of Finance',
    status: 'ACTIVE',
    interestRate: 'Market Linked',
    eligibility: 'Resident Indians',
    officialSource: 'RBI',
    officialInformationUrl: 'https://www.rbi.org.in',
    lastVerified: '2026-09-12',
    sourceLastChecked: '2026-09-12',
    sourceVerificationStatus: 'VERIFIED'
  }
];


export class MockInvestmentRepository implements IInvestmentRepository {
  async getAll(): Promise<Investment[]> {
    return MOCK_INVESTMENTS;
  }
  async getBySlug(slug: string): Promise<Investment | null> {
    return MOCK_INVESTMENTS.find(i => i.slug === slug) || null;
  }
  async getByCategory(category: string): Promise<Investment[]> {
    return MOCK_INVESTMENTS.filter(i => i.category === category);
  }
}
