import { NewsItem } from '../../types';

export const newsDataPart2: NewsItem[] = [
  {
    id: 'news-niti-16',
    title: 'NITI Aayog Releases State Energy and Climate Index Highlighting Renewable Transition Leaders',
    slug: 'niti-aayog-releases-state-energy-climate-index',
    description: 'Ranking framework rewards states demonstrating aggressive decarbonization, rooftop solar adoption, and electric mobility penetration.',
    authority: 'NITI Aayog',
    ministry: 'Cabinet Secretariat / NITI Aayog',
    department: 'Energy and Climate Change Vertical',
    category: 'Energy & Climate',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://niti.gov.in',
    sourceAuthority: 'NITI Aayog Official Report',
    sourceName: 'SECI Index Publication',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-14',
    effectiveDate: '2026-08-15',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'NITI Aayog published the updated State Energy and Climate Index (SECI), evaluating Indian states across clean energy adoption, grid efficiency, and environmental sustainability.',
    whatChanged: 'States demonstrating top-tier performance receive priority central capital grants for power distribution modernization and green industrial zones.',
    whyItMatters: 'Creates healthy competitive federalism among states to accelerate India’s 500 GW non-fossil fuel capacity target.',
    whoIsAffected: 'State electricity boards, discoms, renewable energy developers, and urban municipal corporations.',
    relevance: 'Guides institutional investors on state-specific regulatory friendliness for clean energy projects.',
    keyAnnouncement: 'Allocation of ₹5,000 Crore performance-linked incentive grants for top-performing clean energy states.',
    importantNumbers: ['500 GW non-fossil target tracking', '₹5,000 Crore performance incentive pool', '28 states and 8 UTs evaluated'],
    previousRule: 'Uniform central energy allocation without performance-based climate governance incentives.',
    newRule: 'Indexed evaluation linking central discom financial turnaround grants directly to renewable energy penetration milestones.',
    practicalImpact: 'Accelerates state-level regulatory approvals for rooftop solar and EV charging station rollouts.',
    actionRequired: 'State energy departments should align their state action plans with SECI benchmark parameters.',
    importantConditions: ['Independent audit of discom financial health', 'Transparent open-access electricity pricing rules'],
    officialNotification: 'NITI/Energy/2026/SECI-03',
    circularNumber: 'NITI-Aayog-PR-2026-44',
    relatedInvestment: 'Clean Energy Infrastructure & State Power Discom Bonds',
    relatedScheme: 'Revamped Distribution Sector Scheme (RDSS)',
    relatedOpportunity: 'Development of 250MW Solar Park Transmission System',
    relatedTender: 'tender-sec-sol-22',
    faqs: [
      {
        question: 'Which states ranked highest in the latest SECI index?',
        answer: 'Gujarat, Karnataka, and Kerala secured top rankings for aggressive renewable integration and electric mobility adoption.'
      }
    ],
    whatThisUpdateMeans: 'NITI Aayog is driving state-level accountability in climate action, rewarding states that embrace renewable energy with priority central funding.',
    content: 'NITI Aayog published its comprehensive climate governance report, identifying leading states in clean energy transition and outlining targeted financial grants for regional distribution company (discom) financial turnaround.',
    factBreakdown: {
      fact: 'NITI Aayog released State Energy and Climate Index with ₹5,000 Crore performance grants.',
      source: 'NITI Aayog official report publication dated August 14, 2026.',
      explanation: 'Encourages competitive federalism in decarbonization, rooftop solar, and EV infrastructure.'
    }
  },
  {
    id: 'news-textiles-17',
    title: 'National Technical Textiles Mission Approves 35 New R&D Projects in Smart Wearables',
    slug: 'national-technical-textiles-mission-approves-projects',
    description: 'Support for high-performance protective gear, medical textiles, and geotextiles used in civil engineering projects.',
    authority: 'Ministry of Textiles',
    ministry: 'Ministry of Textiles',
    department: 'National Technical Textiles Mission Secretariat',
    category: 'Technical Textiles',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://texmin.nic.in',
    sourceAuthority: 'Ministry of Textiles Release',
    sourceName: 'NTTM Project Approval Bulletin',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-12',
    effectiveDate: '2026-08-20',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Mission Steering Group of the National Technical Textiles Mission (NTTM) cleared 35 new R&D projects.',
    whatChanged: 'Grant-in-aid funding sanctioned for indigenous development of carbon fiber composites, firefighter thermal suits, and geo-synthetics.',
    whyItMatters: 'Reduces import dependency for high-value technical textiles used in defense, healthcare, and infrastructure.',
    whoIsAffected: 'Technical textile manufacturers, research institutes, geotechnical engineers, and defense suppliers.',
    relevance: 'Unlocks high-margin manufacturing opportunities in specialized industrial textiles.',
    keyAnnouncement: 'Sanction of ₹150 Crore in research grants for smart wearables and high-strength geo-textiles.',
    importantNumbers: ['35 R&D projects cleared', '₹150 Crore research grant disbursement', '100% indigenous raw material mandate'],
    previousRule: 'Heavy import reliance for high-performance aramid fibers and specialized medical textiles.',
    newRule: 'Mission-mode funding for domestic academic and industrial consortiums to manufacture technical textiles locally.',
    practicalImpact: 'Boosts domestic availability of certified protective gear and slope stabilization materials.',
    actionRequired: 'Approved project leads must execute tripartite agreements with the Ministry of Textiles and designated incubators.',
    importantConditions: ['Must achieve prototype commercialization within 24 months', 'Rigorous quality testing at NABL accredited labs'],
    officialNotification: 'NTTM/R&D/2026/Msg-09',
    circularNumber: 'Textiles-F.No. 12/2/2025-NTTM',
    relatedInvestment: 'Technical Textiles Manufacturing & Composite Materials Funds',
    relatedScheme: 'National Technical Textiles Mission (NTTM)',
    relatedOpportunity: 'Establishment of Common Facility Center for Precision Tooling',
    relatedTender: 'tender-HAL-14',
    faqs: [
      {
        question: 'Are start-ups eligible to apply for NTTM R&D grants?',
        answer: 'Yes, start-ups partnering with recognized research institutions can apply as co-applicants for grant funding.'
      }
    ],
    whatThisUpdateMeans: 'India is systematically building a high-tech technical textile manufacturing base, replacing imported protective and industrial fabrics with homegrown innovations.',
    content: 'The Mission Steering Group of the National Technical Textiles Mission has cleared projects focusing on carbon fiber composites, firefighter thermal protection suits, and geo-synthetics for landslide stabilization.',
    factBreakdown: {
      fact: 'Ministry of Textiles approved 35 new R&D projects under NTTM for smart wearables and geotextiles.',
      source: 'Ministry of Textiles official press release dated August 12, 2026.',
      explanation: 'Funds domestic R&D to eliminate import dependence for high-performance industrial and defense fabrics.'
    }
  },
  {
    id: 'news-mines-18',
    title: 'Ministry of Mines Auctions 20 Critical Mineral Blocks for Lithium, Cobalt, and Rare Earth Elements',
    slug: 'ministry-mines-auctions-critical-mineral-blocks',
    description: 'Commercial exploration and mining leases awarded to consortiums specializing in advanced mineral beneficiation.',
    authority: 'Ministry of Mines',
    ministry: 'Ministry of Mines',
    department: 'Geological Survey of India / Mineral Concession Division',
    category: 'Mining & Minerals',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://mines.gov.in',
    sourceAuthority: 'Ministry of Mines Auction Portal',
    sourceName: 'Critical Mineral Auction Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-10',
    effectiveDate: '2026-08-15',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Ministry of Mines concluded its successful commercial auction round for 20 critical and strategic mineral blocks.',
    whatChanged: 'Exploration and mining licenses awarded to qualified domestic and joint-venture consortiums for lithium, cobalt, nickel, and rare earth elements (REE).',
    whyItMatters: 'Secures primary raw material supply chains for India’s booming electric vehicle battery and renewable energy storage sectors.',
    whoIsAffected: 'Mining conglomerates, battery manufacturers, EV producers, and mineral processing firms.',
    relevance: 'Unlocks upstream mining investment and mineral beneficiation engineering opportunities.',
    keyAnnouncement: 'Successful electronic auction of 20 critical mineral blocks across Jammu & Kashmir, Chhattisgarh, Karnataka, and Odisha.',
    importantNumbers: ['20 critical mineral blocks auctioned', '4 Lithium blocks included', '100% transparent e-auction framework'],
    previousRule: 'Restricted government-only exploration with sluggish lease allocation timelines.',
    newRule: 'Composite exploration-cum-mining licenses awarded via competitive transparent e-bidding with revenue sharing models.',
    practicalImpact: 'Accelerates domestic extraction of battery-grade lithium and rare earths.',
    actionRequired: 'Successful bidders must submit statutory environmental clearance timelines and exploration work programs.',
    importantConditions: ['Strict adherence to Mine Environment and Rehabilitation guidelines', 'Mandatory domestic processing commitment'],
    officialNotification: 'Mines/Auction/2026/CM-05',
    circularNumber: 'F.No. 10/1/2025-M.I',
    relatedInvestment: 'Critical Mineral Mining & Battery Supply Chain Funds',
    relatedScheme: 'National Critical Mineral Mission',
    relatedOpportunity: 'Airborne Geophysical Surveying and Radiometric Mapping',
    relatedTender: 'tender-gsi-25',
    faqs: [
      {
        question: 'Are foreign companies allowed to participate in mineral block auctions?',
        answer: 'Foreign entities can participate through Indian-registered subsidiary joint ventures meeting prescribed net-worth criteria.'
      }
    ],
    whatThisUpdateMeans: 'India is aggressively securing its upstream mineral supply chain for the energy transition, ensuring domestic availability of lithium and rare earths.',
    content: 'In a vital move to secure domestic supply chains for electric vehicles and renewable energy storage, the Ministry of Mines successfully concluded its latest commercial auction of critical mineral exploration blocks.',
    factBreakdown: {
      fact: 'Ministry of Mines successfully auctioned 20 critical mineral blocks including lithium and rare earths.',
      source: 'Ministry of Mines official auction portal bulletin dated August 10, 2026.',
      explanation: 'Grants commercial exploration and mining rights to secure raw materials for EV batteries and clean energy.'
    }
  },
  {
    id: 'news-ireda-19',
    title: 'IREDA Secures Green Bond Financing Line Worth USD 500 Million from International Lenders',
    slug: 'ireda-secures-green-bond-financing-line',
    description: 'Low-cost foreign capital earmarked for solar and wind energy project refinancing across Indian states.',
    authority: 'Indian Renewable Energy Development Agency (IREDA)',
    ministry: 'Ministry of New and Renewable Energy',
    department: 'Resource Mobilization and International Finance',
    category: 'Green Finance',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.ireda.in',
    sourceAuthority: 'IREDA Financial Disclosure',
    sourceName: 'Green Bond Issue Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-08',
    effectiveDate: '2026-08-12',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'IREDA finalized a USD 500 Million institutional green bond financing line with international multilateral development finance institutions.',
    whatChanged: 'Mobilization of low-cost foreign currency debt to refinance utility-scale solar, wind, and hybrid renewable energy projects in India.',
    whyItMatters: 'Lowers debt servicing costs for renewable energy developers, directly reducing tariff rates for power distribution companies.',
    whoIsAffected: 'Renewable energy IPPs (Independent Power Producers), institutional bondholders, and commercial banks.',
    relevance: 'Ensures robust liquidity and competitive interest rate financing for clean energy infrastructure.',
    keyAnnouncement: 'Successful syndication of USD 500 Million green credit line at benchmark-beating SOFR spreads.',
    importantNumbers: ['USD 500 Million credit line secured', '15-year amortizing debt tenure', 'AAA domestic credit rating maintained'],
    previousRule: 'Higher domestic borrowing costs for long-term renewable infrastructure financing.',
    newRule: 'Direct access to global green bond capital markets via sovereign-backed institutional intermediaries like IREDA.',
    practicalImpact: 'Enables developers to finance gigawatt-scale solar parks at highly competitive single-digit interest rates.',
    actionRequired: 'Renewable developers can apply for IREDA refinancing windows through the online loan application portal.',
    importantConditions: ['Projects must comply with Climate Bonds Initiative (CBI) taxonomy', 'Zero fossil fuel asset contamination'],
    officialNotification: 'IREDA/Finance/2026/GB-04',
    circularNumber: 'IREDA-PR-2026-19',
    relatedInvestment: 'Green Bonds & Renewable Energy Debt Funds',
    relatedScheme: 'National Clean Energy Fund (NCEF)',
    relatedOpportunity: 'Development of 250MW Solar Park Transmission System',
    relatedTender: 'tender-sec-sol-22',
    faqs: [
      {
        question: 'Are foreign exchange fluctuation risks hedged under this financing line?',
        answer: 'IREDA provides structured hedging options or unhedged foreign currency loan facilities based on developer preference and RBI guidelines.'
      }
    ],
    whatThisUpdateMeans: 'IREDA continues to unlock international low-cost capital for Indian clean energy developers, keeping solar and wind tariffs among the lowest globally.',
    content: 'IREDA has finalized institutional green financing agreements with global multilateral development banks, providing competitive interest rate loans for utility-scale renewable energy developers.',
    factBreakdown: {
      fact: 'IREDA secured USD 500 Million in international green bond financing for renewable projects.',
      source: 'Indian Renewable Energy Development Agency financial disclosure dated August 8, 2026.',
      explanation: 'Provides low-cost long-term debt financing to lower clean energy tariffs across Indian states.'
    }
  },
  {
    id: 'news-uidai-20',
    title: 'UIDAI Introduces Next-Gen Biometric Authentication SDK with Liveness Detection for FinTechs',
    slug: 'uidai-introduces-next-gen-biometric-authentication-sdk',
    description: 'Enhanced cryptographic security protects user identity verification while reducing authentication latency.',
    authority: 'Unique Identification Authority of India (UIDAI)',
    ministry: 'Ministry of Electronics and Information Technology (MeitY)',
    department: 'Technology and Architecture Division',
    category: 'Digital Governance',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://uidai.gov.in',
    sourceAuthority: 'UIDAI Circular & Developer Portal',
    sourceName: 'Aadhaar SDK 3.0 Release Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-06',
    effectiveDate: '2026-08-10',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'UIDAI released its upgraded Aadhaar authentication Software Development Kit (SDK 3.0) featuring edge-based facial and iris liveness detection.',
    whatChanged: 'Banking and financial applications can now execute zero-touch biometric KYC checks instantly without requiring dedicated external hardware scanners.',
    whyItMatters: 'Improves cyber-security, prevents biometric spoofing attempts, and enables seamless digital onboarding for millions of citizens.',
    whoIsAffected: 'Scheduled commercial banks, fintech companies, payment aggregators, and AUAs/KUA entities.',
    relevance: 'Enhances security and user experience for digital identity verification workflows.',
    keyAnnouncement: 'Mandatory migration to SDK 3.0 with built-in anti-spoofing liveness algorithms for all regulated financial entities.',
    importantNumbers: ['< 400 milliseconds average authentication latency', '99.99% facial recognition accuracy benchmark', 'Zero data storage on client devices'],
    previousRule: 'Older authentication protocols required physical fingerprint or iris scanners, limiting remote onboarding flexibility.',
    newRule: 'Smartphone camera-based facial liveness capture backed by end-to-end device-level hardware enclaves.',
    practicalImpact: 'Enables fully remote video-KYC and instant bank account opening with supreme cryptographic security.',
    actionRequired: 'Licensed Authentication User Agencies (AUAs) must integrate SDK 3.0 into their mobile and web applications.',
    importantConditions: ['Must comply with Aadhaar Act 2016 privacy mandates', 'Biometric templates must never be stored locally on merchant servers'],
    officialNotification: 'UIDAI/Auth/2026/SDK-3.0',
    circularNumber: 'F.No. 13012/64/2025-UIDAI',
    relatedInvestment: 'Digital Public Infrastructure & Cybersecurity Funds',
    relatedScheme: 'Aadhaar Enabled Payment System (AePS) Framework',
    relatedOpportunity: 'Procurement of Enterprise Cloud Servers and Storage Area Network',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'Is facial authentication secure against photograph presentation attacks?',
        answer: 'Yes, SDK 3.0 includes certified ISO-compliant passive liveness detection that rejects photos, videos, and 3D silicone masks.'
      }
    ],
    whatThisUpdateMeans: 'UIDAI has made remote biometric verification completely secure and frictionless, enabling instant digital trust across Indian banking and commerce.',
    content: 'UIDAI has released its updated software development kit (SDK) featuring edge-based facial liveness detection, enabling banking and fintech apps to execute secure, instant KYC checks with zero possibility of spoofing.',
    factBreakdown: {
      fact: 'UIDAI launched Aadhaar SDK 3.0 with edge-based facial liveness detection for secure remote KYC.',
      source: 'Unique Identification Authority of India circular dated August 6, 2026.',
      explanation: 'Enables instant smartphone-based video KYC with robust anti-spoofing cryptographic security.'
    }
  },
  {
    id: 'news-corporate-21',
    title: 'Ministry of Corporate Affairs Simplifies Company Incorporation and MCA-21 Portal V3 Upgrades',
    slug: 'mca-simplifies-company-incorporation-portal-upgrades',
    description: 'Automated approval workflows reduce private limited company registration turnaround time to under 24 hours.',
    authority: 'Ministry of Corporate Affairs (MCA)',
    ministry: 'Ministry of Corporate Affairs',
    department: 'E-Governance Division / Registrar of Companies',
    category: 'Corporate Governance',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.mca.gov.in',
    sourceAuthority: 'MCA Official Notification',
    sourceName: 'MCA-21 V3 Enhancement Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-04',
    effectiveDate: '2026-08-08',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Ministry of Corporate Affairs completed major structural upgrades to the MCA-21 V3 portal.',
    whatChanged: 'Integration of automated PAN, TAN, EPFO, and ESIC registrations directly into the SPICe+ company incorporation workflow.',
    whyItMatters: 'Drastically reduces administrative burden and incorporation latency for entrepreneurs starting new businesses in India.',
    whoIsAffected: 'Corporate law practitioners, chartered accountants, company secretaries, and startup founders.',
    relevance: 'Simplifies business establishment and regulatory compliance filing procedures.',
    keyAnnouncement: 'Average company incorporation approval time reduced to under 24 hours via straight-through digital processing.',
    importantNumbers: ['< 24 hours incorporation approval SLA', 'Unified SPICe+ digital form', 'Zero manual touchpoints for standard filings'],
    previousRule: 'Sequential multi-agency filings causing registration delays of 7 to 15 business days.',
    newRule: 'Single-window integrated digital filing issuing incorporation certificate along with tax and labor registrations simultaneously.',
    practicalImpact: 'Entrepreneurs can commence commercial business operations immediately upon incorporation.',
    actionRequired: 'Submit SPICe+ forms using updated digital signature certificates (DSC) on the MCA-21 portal.',
    importantConditions: ['Accurate name approval and KYC verification of all subscribers', 'Registered office address proof verification'],
    officialNotification: 'G.S.R. 512(E) - Companies (Incorporation) Amendment Rules, 2026',
    circularNumber: 'MCA Circular No. 11/2026',
    relatedInvestment: 'Startup Incubation & Corporate Law Tech Funds',
    relatedScheme: 'Ease of Doing Business Administrative Reform Initiative',
    relatedOpportunity: 'Establishment of Common Facility Center for Precision Tooling',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'Are foreign nationals permitted to act as directors during online incorporation?',
        answer: 'Yes, provided their apostilled passport copies and digital signatures are verified through authorized Indian embassies or V3 pathways.'
      }
    ],
    whatThisUpdateMeans: 'Registering a company in India is now a streamlined, automated 24-hour digital experience, showcasing world-class ease of doing business.',
    content: 'The Ministry of Corporate Affairs has completed rollout enhancements on the MCA-21 V3 platform, integrating automated PAN, TAN, and EPFO registration directly into the corporate incorporation filing workflow.',
    factBreakdown: {
      fact: 'Ministry of Corporate Affairs upgraded MCA-21 V3 portal to achieve <24 hour company incorporation.',
      source: 'Ministry of Corporate Affairs official notification dated August 4, 2026.',
      explanation: 'Integrates automated PAN, TAN, EPFO, and ESIC registration into a single SPICe+ workflow.'
    }
  },
  {
    id: 'news-electronics-22',
    title: 'Electronics Manufacturing Output Crosses USD 120 Billion Milestone with 25% Export Growth',
    slug: 'electronics-manufacturing-output-crosses-milestone',
    description: 'Mobile phone production and component localization drive robust manufacturing sector expansion.',
    authority: 'Ministry of Electronics and Information Technology (MeitY)',
    ministry: 'Ministry of Electronics and Information Technology',
    department: 'Electronics and Hardware Division',
    category: 'Electronics Manufacturing',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.meity.gov.in',
    sourceAuthority: 'MeitY Statistical Report',
    sourceName: 'Electronics Production & Export Bulletin',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-02',
    effectiveDate: '2026-08-05',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'MeitY announced that domestic electronics manufacturing output crossed USD 120 Billion, led by mobile phone assembly and sub-component localization.',
    whatChanged: 'Surge in high-value electronics exports driven by the Production Linked Incentive (PLI) scheme and SPEZS.',
    whyItMatters: 'Establishes India as a trusted global electronics manufacturing hub, diversifying international supply chains.',
    whoIsAffected: 'Contract manufacturers, component suppliers, OEM brands, and logistics operators.',
    relevance: 'Highlights rapid growth and investment viability in Indian electronics manufacturing ecosystems.',
    keyAnnouncement: 'Export of mobile phones from India registers 25% year-on-year growth to reach major global markets.',
    importantNumbers: ['USD 120 Billion total production output', '25% annual export growth rate', '10 Lakh+ direct and indirect jobs created'],
    previousRule: 'Heavy dependence on finished electronics imports with minimal domestic value addition.',
    newRule: 'Incentivized domestic assembly and component manufacturing ecosystems under PLI 1.0 and 2.0.',
    practicalImpact: 'Attracts global technology giants to establish Tier-1 supplier clusters in Tamil Nadu, Uttar Pradesh, and Karnataka.',
    actionRequired: 'Component manufacturers should explore joint venture opportunities with established OEM assembly parks.',
    importantConditions: ['Adherence to phased manufacturing program (PMP) milestones', 'Minimum domestic value addition criteria'],
    officialNotification: 'MeitY/Stat/2026/Elec-08',
    circularNumber: 'MeitY-PR-2026-38',
    relatedInvestment: 'Electronics Manufacturing PLI & Component Parks',
    relatedScheme: 'Production Linked Incentive (PLI) Scheme for Large Scale Electronics',
    relatedOpportunity: 'Procurement of Enterprise Cloud Servers and Storage Area Network',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'Which product category witnessed the highest export surge?',
        answer: 'Smartphones, hearables/wearables, and printed circuit board assemblies (PCBAs) led the export volume growth.'
      }
    ],
    whatThisUpdateMeans: 'India has successfully transitioned from an electronics importer to a powerhouse exporter of advanced technology hardware.',
    content: 'Driven by the Production Linked Incentive (PLI) scheme for large-scale electronics manufacturing, India continues to cement its position as a global hub for smartphone assembly and sub-assembly exports.',
    factBreakdown: {
      fact: 'Domestic electronics manufacturing crossed USD 120 Billion with 25% export growth.',
      source: 'Ministry of Electronics and Information Technology statistical report dated August 2, 2026.',
      explanation: 'Validated by successful PLI implementation and deep component localization across industrial clusters.'
    }
  },
  {
    id: 'news-skill-23',
    title: 'MSDE Launches National Apprenticeship Promotion Scheme (NAPS 3.0) with Stipend Support',
    slug: 'msde-launches-national-apprenticeship-promotion-scheme-3',
    description: 'Direct benefit transfer for industrial training participants across automotive, electronics, and aerospace manufacturing sectors.',
    authority: 'Ministry of Skill Development and Entrepreneurship (MSDE)',
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    department: 'Directorate General of Training (DGT)',
    category: 'Skill Development',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://msde.gov.in',
    sourceAuthority: 'MSDE Official Notification',
    sourceName: 'NAPS 3.0 Guidelines Circular',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-30',
    effectiveDate: '2026-08-01',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'MSDE launched the National Apprenticeship Promotion Scheme 3.0 (NAPS 3.0) with enhanced direct benefit transfer (DBT) stipend co-funding.',
    whatChanged: 'Government co-funds up to 50% of the apprentice stipend (up to ₹1,500 per month per apprentice) directly to trainees via Aadhaar-seeded bank accounts.',
    whyItMatters: 'Equips industrial workers with practical shop-floor skills while reducing wage cost burdens for MSME employers.',
    whoIsAffected: 'Industrial employers, manufacturing units, ITI graduates, and vocational trainees.',
    relevance: 'Ensures a steady pipeline of trained technical manpower for industrial expansion.',
    keyAnnouncement: 'Targeted engagement of 20 Lakh apprentices across manufacturing and services sectors in FY 2026-27.',
    importantNumbers: ['₹1,500 monthly direct government stipend subsidy', '20 Lakh apprentice target', '10,000+ registered industrial establishments'],
    previousRule: 'NAPS 2.0 involved complex reimbursement paperwork for employers, causing administrative delays.',
    newRule: 'Direct Benefit Transfer (DBT) model transferring government co-share directly to apprentice bank accounts with automated attendance tracking.',
    practicalImpact: 'Reduces net training costs for factories while guaranteeing fair stipend disbursement to youth.',
    actionRequired: 'Employers must register on the National Apprenticeship Training Portal (NATS/NAPS) and upload contract details.',
    importantConditions: ['Apprentices must be aged 14 years and above', 'Stipend paid must equal or exceed statutory minimum rates'],
    officialNotification: 'MSDE-1(1)/2025-AP (NAPS-III)',
    circularNumber: 'DGT-35/1/2026-NAPS',
    relatedInvestment: 'Vocational Training & Industrial Skill Development Funds',
    relatedScheme: 'National Apprenticeship Promotion Scheme (NAPS 3.0)',
    relatedOpportunity: 'Establishment of Common Facility Center for Precision Tooling',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'Are micro-enterprises with fewer than 10 employees eligible to hire apprentices?',
        answer: 'Yes, micro-enterprises can hire optional-trade apprentices through third-party aggregator aggregators.'
      }
    ],
    whatThisUpdateMeans: 'India is aggressively bridging the employability gap by financially backing structured on-the-job industrial apprenticeships for youth.',
    content: 'MSDE has initiated NAPS 3.0, partnering with over 10,000 industrial employers to provide structured on-the-job apprenticeship training coupled with direct government stipend co-funding.',
    factBreakdown: {
      fact: 'MSDE launched NAPS 3.0 providing direct benefit transfer stipend support for 20 Lakh apprentices.',
      source: 'Ministry of Skill Development and Entrepreneurship official notification dated July 30, 2026.',
      explanation: 'Co-funds apprentice stipends directly to trainee bank accounts and reduces training cost burdens for employers.'
    }
  },
  {
    id: 'news-petroleum-24',
    title: 'Strategic Petroleum Reserve Expansion Project Awarded to Domestic Infrastructure Consortium',
    slug: 'strategic-petroleum-reserve-expansion-project-awarded',
    description: 'Underground rock cavern storage capacity augmented to buffer against global crude oil price volatility.',
    authority: 'Ministry of Petroleum and Natural Gas',
    ministry: 'Ministry of Petroleum and Natural Gas',
    department: 'ISPRL (Indian Strategic Petroleum Reserves Limited)',
    category: 'Energy Security',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://mopng.gov.in',
    sourceAuthority: 'MoPNG Press Release',
    sourceName: 'SPR Phase-2 Award Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-28',
    effectiveDate: '2026-08-05',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'MoPNG awarded engineering, procurement, and construction (EPC) contracts for Phase-2 of India’s Strategic Petroleum Reserves (SPR).',
    whatChanged: 'Construction of massive underground excavated rock caverns in southern coastal locations to store an additional 12 Million Metric Tonnes (MMT) of crude oil.',
    whyItMatters: 'Provides an essential macroeconomic buffer against geopolitical supply shocks and international crude price spikes.',
    whoIsAffected: 'Refiners, crude oil suppliers, public sector undertaking (PSU) oil companies, and civil construction firms.',
    relevance: 'Unlocks large-scale underground civil construction, tunneling, and pipeline infrastructure contracts.',
    keyAnnouncement: 'Award of Phase-2 SPR construction contracts valued at ₹6,500 Crores to domestic EPC consortiums.',
    importantNumbers: ['12 MMT additional crude storage capacity', '₹6,500 Crore capital expenditure outlay', '36-month construction completion timeline'],
    previousRule: 'Phase-1 SPR capacity of 5.33 MMT located in Mangaluru, Padur, and Visakhapatnam.',
    newRule: 'Expansion into subterranean granite rock caverns with state-of-the-art leak-prevention grouting and automated pumping systems.',
    practicalImpact: 'Secures nearly 25 days of India’s total crude oil import requirement within domestic underground vaults.',
    actionRequired: 'EPC contractors must mobilize heavy tunneling equipment and adhere to stringent petroleum safety rules.',
    importantConditions: ['Mandatory compliance with OISD (Oil Industry Safety Directorate) standards', 'Local geo-technical stability monitoring'],
    officialNotification: 'MoPNG/ISPRL/2026/SPR-02',
    circularNumber: 'ISPRL-PR-2026-11',
    relatedInvestment: 'Energy Security Infrastructure & Heavy Civil Construction Bonds',
    relatedScheme: 'National Strategic Petroleum Reserve Program',
    relatedOpportunity: 'Construction of Cryogenic LPG Storage Mounded Bullets',
    relatedTender: 'tender-iocl-11',
    faqs: [
      {
        question: 'Who funds the crude oil stored inside these strategic caverns?',
        answer: 'Financed through a mix of central budgetary allocations, oil company cesses, and international leasing arrangements.'
      }
    ],
    whatThisUpdateMeans: 'India is systematically fortifying its national energy security by expanding underground crude oil reserves to withstand global supply disruptions.',
    content: 'The government has awarded contracts for the second phase of strategic petroleum reserves, constructing underground excavated rock caverns in southern coastal locations to ensure long-term energy security.',
    factBreakdown: {
      fact: 'MoPNG awarded ₹6,500 Crore EPC contracts for Phase-2 Strategic Petroleum Reserve caverns.',
      source: 'Ministry of Petroleum and Natural Gas official release dated July 28, 2026.',
      explanation: 'Builds 12 MMT of underground crude oil storage capacity to buffer against global supply shocks.'
    }
  },
  {
    id: 'news-shipping-25',
    title: 'Maritime India Vision 2030 Milestone Reached: Major Ports Handle Record Cargo Throughput',
    slug: 'maritime-india-vision-2030-milestone-reached',
    description: 'Turnaround time at major ports drops significantly due to container berth automation and direct port delivery (DPD).',
    authority: 'Ministry of Ports, Shipping and Waterways',
    ministry: 'Ministry of Ports, Shipping and Waterways',
    department: 'Port Operations Division',
    category: 'Ports & Shipping',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://shipmin.gov.in',
    sourceAuthority: 'Ministry of Ports Performance Report',
    sourceName: 'Maritime Cargo Throughput Bulletin',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-26',
    effectiveDate: '2026-07-26',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Ministry of Ports, Shipping and Waterways announced that major Indian ports crossed historical cargo throughput benchmarks.',
    whatChanged: 'Average vessel turnaround time dropped below 24 hours across major ports due to automated container handling and Direct Port Delivery (DPD) adoption.',
    whyItMatters: 'Reduces logistics friction, lowers ocean freight demurrage costs, and improves maritime export competitiveness.',
    whoIsAffected: 'Port terminal operators, shipping lines, exporters, importers, and custom house agents.',
    relevance: 'Highlights operational efficiency and modernization across India’s coastline ports.',
    keyAnnouncement: 'Achievement of sub-24-hour average vessel turnaround time across all 12 major ports.',
    importantNumbers: ['< 24 hours average vessel turnaround', '15% increase in annual container throughput', '90% DPD adoption rate'],
    previousRule: 'Port congestion and manual documentation caused vessel turnaround times to stretch over 3 to 4 days.',
    newRule: 'Automated vessel traffic management, digital port community systems (PCS 1x), and mechanised berth handling.',
    practicalImpact: 'Container cargo moves from ship to highway truck within hours of berthing.',
    actionRequired: 'Importers should utilize Direct Port Delivery (DPD) protocols to bypass container freight stations (CFS).',
    importantConditions: ['Mandatory RFID tagging on all containers entering port gates', 'Electronic payment of port charges'],
    officialNotification: 'MoPSW/PortOp/2026/M-14',
    circularNumber: 'Shipping Circular No. 08/2026',
    relatedInvestment: 'Port Infrastructure & Maritime Logistics Funds',
    relatedScheme: 'Sagarmala Programme & Maritime India Vision 2030',
    relatedOpportunity: 'Dry Docking, Special Survey and Hull Rehabilitation of Vessels',
    relatedTender: 'tender-sci-10',
    faqs: [
      {
        question: 'Which port recorded the highest cargo volume growth?',
        answer: 'JNPT (Mumbai), Mundra, and Paradip registered the highest container and bulk cargo throughput growth.'
      }
    ],
    whatThisUpdateMeans: 'Indian ports have achieved global efficiency benchmarks, cutting vessel turnaround times and slashing port-related logistics costs.',
    content: 'Minister of Ports, Shipping and Waterways announced that major Indian ports have achieved record-breaking operational efficiency metrics, aided by private terminal investments and digital vessel traffic management systems.',
    factBreakdown: {
      fact: 'Major Indian ports achieved sub-24-hour average vessel turnaround time and record cargo throughput.',
      source: 'Ministry of Ports, Shipping and Waterways performance report dated July 26, 2026.',
      explanation: 'Driven by container berth automation, digital PCS 1x portals, and Direct Port Delivery adoption.'
    }
  },
  {
    id: 'news-space-26',
    title: 'IN-SPACe Approves First Commercial Private Launch Complex and Space Park in Sriharikota',
    slug: 'in-space-approves-first-commercial-private-launch-complex',
    description: 'Private aerospace startups gain independent launch pad facilities and ground tracking station integration.',
    authority: 'IN-SPACe / ISRO',
    ministry: 'Department of Space',
    department: 'IN-SPACe (Indian National Space Promotion and Authorization Centre)',
    category: 'Space Commerce',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.inspace.gov.in',
    sourceAuthority: 'IN-SPACe Official Authorization',
    sourceName: 'Commercial Space Launch License',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-24',
    effectiveDate: '2026-07-28',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'IN-SPACe granted final operational authorization for India’s first dedicated private commercial launch complex and space manufacturing park.',
    whatChanged: 'Private aerospace companies can now independently assemble, test, and launch orbital rockets from dedicated pads adjacent to ISRO facilities.',
    whyItMatters: 'Positions India as a preferred global destination for low-cost commercial satellite launches and private space exploration.',
    whoIsAffected: 'Private rocket manufacturers, satellite constellation operators, avionics suppliers, and aerospace engineers.',
    relevance: 'Unlocks massive high-tech commercial investment and manufacturing opportunities in the private space sector.',
    keyAnnouncement: 'Operationalization of the Sriharikota Private Space Park with shared telemetry and radar tracking access.',
    importantNumbers: ['1st private commercial launch complex', '3 private launch pads operational', '50+ satellite payloads booked for FY 2026-27'],
    previousRule: 'All rocket launches were exclusively conducted by ISRO from government launch pads with limited commercial slot availability.',
    newRule: 'Open commercial access for private aerospace companies to build and operate dedicated launch infrastructure under IN-SPACe regulation.',
    practicalImpact: 'Startups can execute orbital launches on demand without scheduling conflicts with national missions.',
    actionRequired: 'Private space operators must secure mission safety certification and payload clearance from IN-SPACe.',
    importantConditions: ['Compliance with international space debris mitigation guidelines', 'Mandatory range safety coordination with ISRO telemetry'],
    officialNotification: 'IN-SPACe/Auth/2026/PLC-01',
    circularNumber: 'DOS-INSPACe-2026-09',
    relatedInvestment: 'Commercial Aerospace & Satellite Constellation Funds',
    relatedScheme: 'Indian Space Policy 2023 / Space Sector FDI Guidelines',
    relatedOpportunity: 'Procurement of Aerospace-Grade Carbon Fiber Composites',
    relatedTender: 'tender-isro-08',
    faqs: [
      {
        question: 'Can international satellite operators launch from the private Indian complex?',
        answer: 'Yes, foreign commercial payloads can be launched following diplomatic clearance and IN-SPACe regulatory approval.'
      }
    ],
    whatThisUpdateMeans: 'India’s space sector is fully open to private enterprise, with dedicated commercial launch pads enabling startups to service the global satellite market.',
    content: 'IN-SPACe has granted final operational authorization for India’s first dedicated private commercial launch complex and mission control facility, enabling domestic rocket startups to conduct orbital launches seamlessly.',
    factBreakdown: {
      fact: 'IN-SPACe approved India’s first private commercial launch complex and space park in Sriharikota.',
      source: 'IN-SPACe official authorization notice dated July 24, 2026.',
      explanation: 'Grants private aerospace startups independent launch pad facilities and ground telemetry integration.'
    }
  },
  {
    id: 'news-housing-27',
    title: 'PMAY-Urban 2.0 Scheme Notified to Provide Interest Subsidy for Affordable Housing Loans',
    slug: 'pmay-urban-2-0-scheme-notified-interest-subsidy',
    description: 'Urban middle-class and economically weaker section families benefit from direct credit-linked subsidy disbursements.',
    authority: 'Ministry of Housing and Urban Affairs (MoHUA)',
    ministry: 'Ministry of Housing and Urban Affairs',
    department: 'Housing Division (PMAY-U Directorate)',
    category: 'Urban Development',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://mohua.gov.in',
    sourceAuthority: 'MoHUA Gazette Notification',
    sourceName: 'PMAY-U 2.0 Operational Guidelines',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-22',
    effectiveDate: '2026-08-01',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'MoHUA officially notified the operational guidelines for Pradhan Mantri Awas Yojana Urban 2.0 (PMAY-U 2.0).',
    whatChanged: 'Provision of interest subvention on home loans for economically weaker sections (EWS), low-income groups (LIG), and middle-income groups (MIG) in urban areas.',
    whyItMatters: 'Makes homeownership financially accessible for millions of urban families while driving residential real estate and construction demand.',
    whoIsAffected: 'Homebuyers, scheduled banks, housing finance companies (HFCs), and real estate developers.',
    relevance: 'Stimulates residential housing construction and mortgage finance markets across Indian cities.',
    keyAnnouncement: 'Interest subvention of up to 4% on home loans up to ₹8 Lakhs for eligible urban households.',
    importantNumbers: ['Up to ₹2.67 Lakh maximum interest subsidy per beneficiary', '10 Million urban houses targeted', '4% annual interest subvention rate'],
    previousRule: 'PMAY-U Phase 1 credit-linked subsidy scheme (CLSS) concluded in March 2022.',
    newRule: 'PMAY-U 2.0 introduces streamlined digital subsidy crediting directly into borrower loan accounts via Central Nodal Agency (CNA).',
    practicalImpact: 'Lowers monthly equated monthly installments (EMIs) for first-time urban homebuyers.',
    actionRequired: 'Eligible borrowers should apply through primary lending institutions or designated common service centers (CSCs).',
    importantConditions: ['Beneficiary must not own a pucca house anywhere in India', 'Carpet area restrictions apply based on income tier'],
    officialNotification: 'G.S.R. 418(E) - PMAY-U 2.0 Scheme Guidelines',
    circularNumber: 'MoHUA-F.No. N-11011/4/2026-HFA-I',
    relatedInvestment: 'Affordable Housing REITs & Mortgage Finance Bonds',
    relatedScheme: 'Pradhan Mantri Awas Yojana Urban 2.0 (PMAY-U 2.0)',
    relatedOpportunity: 'Construction of Residential Housing & Urban Infrastructure',
    relatedTender: 'tender-nhai-03',
    faqs: [
      {
        question: 'Can beneficiaries who availed Phase-1 subsidy apply under PMAY-U 2.0?',
        answer: 'No, families that already received financial assistance under PMAY-U Phase 1 are not eligible for a second subsidy.'
      }
    ],
    whatThisUpdateMeans: 'PMAY-U 2.0 makes affordable urban homeownership a reality for millions of middle and lower-income families through direct interest subventions.',
    content: 'MoHUA has officially notified the operational guidelines for Pradhan Mantri Awas Yojana Urban 2.0, extending interest subvention on housing loans through scheduled commercial banks and housing finance companies.',
    factBreakdown: {
      fact: 'MoHUA notified PMAY-U 2.0 providing interest subsidies up to ₹2.67 Lakhs for urban homebuyers.',
      source: 'Ministry of Housing and Urban Affairs gazette notification dated July 22, 2026.',
      explanation: 'Extends credit-linked interest subvention through commercial banks for EWS, LIG, and MIG urban households.'
    }
  },
  {
    id: 'news-defence-28',
    title: 'Defence Acquisition Council Clears Indigenous Procurement Proposals Worth ₹45,000 Crore',
    slug: 'dac-clears-indigenous-procurement-proposals',
    description: 'Approval granted for next-generation attack helicopters, anti-drone systems, and unmanned surface vessels for the armed forces.',
    authority: 'Ministry of Defence',
    ministry: 'Ministry of Defence',
    department: 'Department of Defence Production / Acquisition Wing',
    category: 'Defence Procurement',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://mod.gov.in',
    sourceAuthority: 'Ministry of Defence Press Release',
    sourceName: 'DAC Meeting Outcome Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-20',
    effectiveDate: '2026-07-25',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Defence Acquisition Council (DAC) chaired by the Defence Minister cleared capital acquisition proposals worth ₹45,000 Crore.',
    whatChanged: 'All cleared proposals are categorized under "Buy (Indian-IDDM)", mandating indigenous design, development, and manufacturing.',
    whyItMatters: 'Reduces foreign defense import dependency and builds a robust domestic defense industrial base under Aatmanirbhar Bharat.',
    whoIsAffected: 'Indian defense manufacturers, DPSUs, MSME component suppliers, and the armed forces.',
    relevance: 'Unlocks massive domestic defense manufacturing and R&D procurement contracts.',
    keyAnnouncement: 'Approval for indigenous light combat helicopters, counter-drone electronic warfare suites, and naval unmanned surface craft.',
    importantNumbers: ['₹45,000 Crore total procurement value', '100% sourced from Indian domestic entities', '25+ MSME tier-1 suppliers integrated'],
    previousRule: 'Heavy reliance on foreign original equipment manufacturers (OEMs) for frontline defense hardware acquisitions.',
    newRule: 'Strict procurement preference for indigenous designs with mandatory domestic intellectual property ownership.',
    practicalImpact: 'Guaranteed long-term manufacturing orders for Indian private and public defense shipyards and aerospace firms.',
    actionRequired: 'Defense manufacturers should monitor MoD RFP postings on the e-Procure defense portal.',
    importantConditions: ['Minimum 60% indigenous content by value', 'Transfer of technology provisions for critical sub-systems'],
    officialNotification: 'MoD/DAC/2026/A-09',
    circularNumber: 'Acquisition Wing Circular No. 2026/55',
    relatedInvestment: 'Indian Defence Manufacturing & Aerospace Equity Funds',
    relatedScheme: 'Defence Production and Export Promotion Policy (DPEPP)',
    relatedOpportunity: 'Machining and Heat Treatment of Aero-Engine Turbine Blades',
    relatedTender: 'tender-HAL-14',
    faqs: [
      {
        question: 'Are private sector defense firms treated equally with Public Sector Undertakings (DPSUs)?',
        answer: 'Yes, private defense manufacturers participate on equal footing under competitive RFP bidding categories.'
      }
    ],
    whatThisUpdateMeans: 'India’s defense modernization is now inextricably tied to domestic manufacturing, ensuring sovereign technological self-reliance and robust industrial growth.',
    content: 'Emphasizing Aatmanirbhar Bharat in defense production, the Defence Acquisition Council has cleared capital acquisition cases to be sourced exclusively from Indian defense manufacturers.',
    factBreakdown: {
      fact: 'Defence Acquisition Council cleared ₹45,000 Crore in indigenous defense procurement proposals.',
      source: 'Ministry of Defence official press release dated July 20, 2026.',
      explanation: 'All acquisitions categorized under Buy (Indian-IDDM) to mandate domestic design and manufacturing.'
    }
  },
  {
    id: 'news-telecom-29',
    title: 'TRAI Issues Recommendations on Spectrum Pricing for SatCom and Direct-to-Cell Services',
    slug: 'trai-issues-recommendations-spectrum-pricing-satcom',
    description: 'Regulatory framework paves the way for commercial satellite broadband rollout and seamless cellular-satellite roaming.',
    authority: 'Telecom Regulatory Authority of India (TRAI)',
    ministry: 'Ministry of Communications',
    department: 'TRAI Secretariat / Spectrum Division',
    category: 'Telecom Policy',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.trai.gov.in',
    sourceAuthority: 'TRAI Recommendations Document',
    sourceName: 'SatCom Spectrum Pricing Policy',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-18',
    effectiveDate: '2026-07-25',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'TRAI released its definitive policy recommendations governing satellite communication (SatCom) spectrum allocation and pricing.',
    whatChanged: 'Administrative assignment of satellite spectrum aligned with global best practices to enable high-speed broadband in remote rural sectors.',
    whyItMatters: 'Bridges the digital divide, enabling schools, hospitals, and remote communities to access gigabit satellite internet.',
    whoIsAffected: 'Satellite broadband operators, telecommunication service providers, enterprises, and rural consumers.',
    relevance: 'Unlocks telecom infrastructure investments in satellite gateways and user terminal manufacturing.',
    keyAnnouncement: 'Recommendation for transparent administrative assignment of satellite spectrum with optimal royalty structures.',
    importantNumbers: ['100% broadband coverage target for remote terrain', 'Transparent administrative pricing formula', 'Zero interference threshold compliance'],
    previousRule: 'Ambiguous regulatory framework regarding satellite spectrum licensing and commercial gateway establishment.',
    newRule: 'Clear administrative spectrum assignment guidelines coupled with strict quality-of-service benchmarks.',
    practicalImpact: 'Accelerates commercial rollout of direct-to-cell satellite connectivity and high-speed enterprise broadband.',
    actionRequired: 'Satellite operators must apply for Global Mobile Personal Communication by Satellite (GMPCS) licenses from DoT.',
    importantConditions: ['Must establish local earth station gateways within India', 'Compliance with national security interception mandates'],
    officialNotification: 'TRAI Recommendation No. 12/2026-SatCom',
    circularNumber: 'DoT-Telecom-2026-89',
    relatedInvestment: 'Satellite Broadband & Telecom Infrastructure Funds',
    relatedScheme: 'National Broadband Mission & BharatNet',
    relatedOpportunity: 'Rollout of FTTH Fiber Optic Cable Access Networks in Rural Blocks',
    relatedTender: 'tender-bsnl-13',
    faqs: [
      {
        question: 'Will satellite broadband compete directly with terrestrial fiber?',
        answer: 'Satellite broadband is intended primarily for remote, hilly, and maritime regions where laying optical fiber is economically unviable.'
      }
    ],
    whatThisUpdateMeans: 'TRAI has cleared the path for commercial satellite broadband in India, ensuring every remote corner of the country can access high-speed internet.',
    content: 'TRAI has released its definitive policy recommendations governing satellite communication spectrum allocation, ensuring fair competition and rapid deployment of high-speed broadband to remote rural clusters.',
    factBreakdown: {
      fact: 'TRAI issued recommendations on administrative satellite spectrum pricing for SatCom broadband.',
      source: 'Telecom Regulatory Authority of India policy document dated July 18, 2026.',
      explanation: 'Paves the way for commercial satellite internet and direct-to-cell roaming rollouts across remote regions.'
    }
  },
  {
    id: 'news-food-30',
    title: 'Ministry of Food Processing Industries Approves 50 New Mega Food Parks and Cold Chains',
    slug: 'ministry-food-processing-approves-50-new-mega-food-parks',
    description: 'Capital grants support integrated cold storage, IQF freezing units, and value-addition agricultural processing lines.',
    authority: 'Ministry of Food Processing Industries (MoFPI)',
    ministry: 'Ministry of Food Processing Industries',
    department: 'Pradhan Kisan Sampada Yojana Directorate',
    category: 'Food Processing',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://mofpi.gov.in',
    sourceAuthority: 'MoFPI Official Release',
    sourceName: 'Mega Food Park Sanction Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-07-16',
    effectiveDate: '2026-07-22',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'MoFPI sanctioned financial assistance for 50 new agro-processing clusters and cold chain infrastructure projects.',
    whatChanged: 'Provision of capital grants up to ₹10 Crores per project for establishing integrated cold storage, IQF freezing, and sorting facilities.',
    whyItMatters: 'Minimizes post-harvest agricultural wastage, enhances farmer income, and boosts processed food export revenues.',
    whoIsAffected: 'Food processors, cold storage operators, agricultural cooperatives, and exporters.',
    relevance: 'Unlocks capital subsidy and commercial infrastructure development opportunities in rural agricultural belts.',
    keyAnnouncement: 'Sanction of ₹500 Crore in capital subsidy grants for 50 new cold chain and mega food park projects.',
    importantNumbers: ['50 new food processing clusters approved', '₹500 Crore capital subsidy outlay', '30% average reduction in post-harvest wastage'],
    previousRule: 'Inadequate cold chain infrastructure leading to significant perishable crop spoilage during transit.',
    newRule: 'Mission-mode capital grants under PMKSY to build integrated cold chain grids connecting farms to export ports.',
    practicalImpact: 'Farmers can store perishable fruits and vegetables safely and sell them at optimal market prices.',
    actionRequired: 'Project promoters must execute grant-in-aid agreements and complete construction milestones within 18 months.',
    importantConditions: ['Must source at least 50% of raw produce directly from farmer producer organizations (FPOs)', 'Adherence to FSSAI food safety standards'],
    officialNotification: 'MoFPI/PMKSY/2026/MFP-08',
    circularNumber: 'F.No. 8/1/2025-ColdChain',
    relatedInvestment: 'Agri-Food Processing Infrastructure & Cold Chain Funds',
    relatedScheme: 'Pradhan Mantri Kisan Sampada Yojana (PMKSY)',
    relatedOpportunity: 'Establishment of Common Facility Center for Agri-Processing',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'What is the maximum financial grant available per cold chain project?',
        answer: 'Capital grant up to 50% of the total project cost in general areas and 75% in difficult/hilly regions, capped at ₹10 Crores.'
      }
    ],
    whatThisUpdateMeans: 'India is aggressively upgrading its agricultural supply chain infrastructure, eliminating wastage and empowering food processors with modern cold chain networks.',
    content: 'MoFPI has sanctioned financial assistance for 50 new agro-processing clusters and cold chain infrastructure projects across major agricultural states, minimizing farm-gate wastage and boosting processed food exports.',
    factBreakdown: {
      fact: 'MoFPI approved 50 new Mega Food Parks and cold chain infrastructure projects with ₹500 Crore grants.',
      source: 'Ministry of Food Processing Industries official release dated July 16, 2026.',
      explanation: 'Reduces post-harvest agricultural wastage and enhances processed food export capabilities.'
    }
  }
];
