import { NewsItem } from '../../types';

export const newsDataPart1: NewsItem[] = [
  {
    id: 'news-pib-01',
    title: 'Union Cabinet Approves National Deep Tech Innovation Strategy and Venture Seed Fund',
    slug: 'union-cabinet-approves-national-deep-tech-strategy',
    description: 'Government unveils a dedicated ₹10,000 Crore fund to boost indigenous quantum computing, semiconductor packaging, and AI research startups.',
    authority: 'Press Information Bureau (PIB)',
    ministry: 'Ministry of Science and Technology / MeitY',
    department: 'Department of Science and Technology (DST)',
    category: 'Policy & Budget',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://pib.gov.in',
    sourceAuthority: 'PIB Official Release',
    sourceName: 'PIB Press Release',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-09-11',
    effectiveDate: '2026-09-15',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Union Cabinet chaired by the Prime Minister approved the comprehensive National Deep Tech Innovation Strategy (NDTIS) with an initial corpus of ₹10,000 Crore.',
    whatChanged: 'Streamlined regulatory clearances, fast-tracked IP protection for deep tech ventures, and direct equity-linked seed funding for pre-commercialization stages.',
    whyItMatters: 'Deep tech startups face prolonged gestation periods and high capital expenditure; this policy bridges the "valley of death" between laboratory research and commercial deployment.',
    whoIsAffected: 'Early-stage deep tech startups, academic research institutions, quantum computing developers, and semiconductor packaging enterprises.',
    relevance: 'Provides critical risk capital and IP support for startups operating in frontier technology sectors across India.',
    keyAnnouncement: 'Establishment of the ₹10,000 Crore National Deep Tech Venture Seed Fund with single-window clearance for dual-use technologies.',
    importantNumbers: ['₹10,000 Crore seed fund corpus', '4-month average patent grant timeline target', '100+ incubators supported'],
    previousRule: 'Fragmented funding schemes across separate ministries without unified risk capital or fast-tracked intellectual property prioritization.',
    newRule: 'Unified inter-ministerial single-window clearance, dedicated venture debt instruments, and priority IP examination under DPIIT.',
    practicalImpact: 'Accelerates time-to-market for indigenous quantum hardware, AI accelerators, and advanced materials.',
    actionRequired: 'Eligible deep tech startups should prepare pitch decks and register on the NDTIS portal for upcoming funding windows.',
    importantConditions: ['Must be DPIIT-recognized startups', 'At least 51% Indian promoter shareholding', 'Core R&D must be conducted within India'],
    officialNotification: 'Cabinet Committee on Economic Affairs (CCEA) Resolution No. 45/DT/2026',
    circularNumber: 'PIB ID: 2189342',
    relatedInvestment: 'National Deep Tech Innovation Seed Fund',
    relatedScheme: 'Startup India Seed Fund Scheme (SISFS)',
    relatedOpportunity: 'Deep Tech & Semiconductor R&D Infrastructure',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'Who is eligible to apply for the Deep Tech Seed Fund?',
        answer: 'DPIIT-recognized startups working in quantum computing, photonics, AI semiconductors, and biotech with verified prototype stage.'
      },
      {
        question: 'What is the maximum funding assistance per startup?',
        answer: 'Up to ₹50 Lakhs in grant-in-aid during proof-of-concept stage and up to ₹5 Crores in convertible debentures/equity during commercialization.'
      }
    ],
    whatThisUpdateMeans: 'The government is formally underwriting high-risk scientific innovation, making it significantly easier for Indian engineers to commercialize homegrown intellectual property without relying solely on foreign venture capital.',
    content: 'The Union Cabinet chaired by the Prime Minister has approved the comprehensive National Deep Tech Innovation Strategy (NDTIS). The framework aims to streamline regulatory clearances, provide risk capital, and secure intellectual property rights for high-tech domestic ventures. Backed by a ₹10,000 Crore outlay, the initiative brings together DST, MeitY, and DPIIT to foster critical technological self-reliance.',
    factBreakdown: {
      fact: 'Union Cabinet approved National Deep Tech Innovation Strategy with a ₹10,000 Crore corpus.',
      source: 'Press Information Bureau (PIB) official cabinet briefing dated September 11, 2026.',
      explanation: 'Provides institutional risk capital and single-window clearances for quantum, AI, and semiconductor startups in India.'
    }
  },
  {
    id: 'news-rbi-02',
    title: 'RBI Announces Guidelines for Cross-Border Fast Payments and Digital Trade Corridors',
    slug: 'rbi-announces-guidelines-cross-border-fast-payments',
    description: 'Reserve Bank of India establishes interoperable payment frameworks connecting UPI with major international clearing networks.',
    authority: 'Reserve Bank of India (RBI)',
    ministry: 'Ministry of Finance',
    department: 'Department of Payment and Settlement Systems',
    category: 'Banking & Finance',
    status: 'PUBLISHED',
    effectiveStatus: 'EFFECTIVE',
    sourceUrl: 'https://www.rbi.org.in',
    sourceAuthority: 'RBI Official Notification',
    sourceName: 'RBI Press Release & Circular',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-09-09',
    effectiveDate: '2026-10-01',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'RBI issued comprehensive regulatory guidelines enabling direct real-time account-to-account cross-border retail and wholesale settlements between UPI and international fast payment systems.',
    whatChanged: 'Authorized AD Category-1 banks to partner directly with overseas central clearing counterparties for instant, low-cost multi-currency trade settlements.',
    whyItMatters: 'Reduces international wire transfer friction, lowers FX markup costs, and accelerates liquidity cycles for Indian MSME exporters.',
    whoIsAffected: 'Exporters, importers, fintech payment aggregators, scheduled commercial banks, and non-resident Indian remittance senders.',
    relevance: 'Simplifies global trade transactions and foreign currency receivables for Indian businesses.',
    keyAnnouncement: 'Launch of the UPI-Global Interoperable Settlement Network across participating G20 corridor partner nations.',
    importantNumbers: ['Zero interchange fee for retail pilot corridors', 'T+0 settlement settlement capability', '50+ partner banking institutions'],
    previousRule: 'Traditional SWIFT correspondent banking channels involving multi-day transit delays and high intermediary bank charges.',
    newRule: 'Direct API-driven bilateral fast-payment gateway integration with participating foreign central banks.',
    practicalImpact: 'Improves cash flow predictability for small exporters by eliminating 3 to 5 business day wire settlement lags.',
    actionRequired: 'Banks and authorized payment aggregators must update their API middleware and compliance protocols by October 1, 2026.',
    importantConditions: ['Compliance with FEMA 1999 guidelines', 'Mandatory AML/CFT screening on all inbound-outbound transactions', 'Adherence to RBI data localization norms'],
    officialNotification: 'RBI/2026-27/42 DPSS.CO.OD.No.S128/06-08-001/2026-27',
    circularNumber: 'RBI Circular No. 2026/894',
    relatedInvestment: 'Sovereign Green Bonds & Foreign Exchange Reserves Management',
    relatedScheme: 'Interest Equalisation Scheme for Pre and Post Shipment Export Credit',
    relatedOpportunity: 'Cross-Border Fintech & Digital Payment Infrastructure',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'Does this apply to retail remittances as well as commercial trade?',
        answer: 'Yes, the framework covers both peer-to-peer retail remittances and B2B commercial invoice settlements up to USD 1 Million per transaction.'
      },
      {
        question: 'Are crypto-assets permitted under this corridor?',
        answer: 'No, transactions are strictly restricted to sovereign fiat currencies settled through regulated central bank digital currency (CBDC) or authorized correspondent accounts.'
      }
    ],
    whatThisUpdateMeans: 'Indian businesses can now execute international trade payments with the same instant speed as domestic UPI transfers, dramatically reducing working capital lockup.',
    content: 'In an effort to reduce trade settlement times and transaction costs for Indian exporters, the Reserve Bank of India has issued regulatory guidelines enabling direct real-time account-to-account settlements across participating G20 partner nations. The framework leverages UPI infrastructure enhancements and bilateral central bank agreements.',
    factBreakdown: {
      fact: 'RBI issued new guidelines for cross-border fast payment integration with international clearing networks.',
      source: 'Reserve Bank of India Department of Payment and Settlement Systems circular dated September 9, 2026.',
      explanation: 'Enables instant T+0 cross-border retail and trade settlements, lowering intermediary transaction fees.'
    }
  },
  {
    id: 'news-dpiit-03',
    title: 'DPIIT Simplifies Startup Patent Fast-Tracking and Intellectual Property Rebate Rules',
    slug: 'dpiit-simplifies-startup-patent-fast-tracking',
    description: 'Department of Promotion of Industry and Internal Trade extends 80% patent filing fee rebate and expedites examination timelines.',
    authority: 'DPIIT, Ministry of Commerce and Industry',
    ministry: 'Ministry of Commerce and Industry',
    department: 'Department for Promotion of Industry and Internal Trade',
    category: 'Startups & Innovation',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.dpiit.gov.in',
    sourceAuthority: 'DPIIT Official Notice',
    sourceName: 'DPIIT Gazette Notification',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-09-08',
    effectiveDate: '2026-09-10',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'DPIIT amended the Patents Rules to make expedited examination universally accessible to all recognized startups without requiring formal expedited hearing fees.',
    whatChanged: '80% fee rebate on patent filing and prosecution fees is now automatically applied via the e-filing portal upon entering the Startup India recognition certificate number.',
    whyItMatters: 'Protects intellectual property assets early, empowering startups to secure venture funding and defend proprietary technologies.',
    whoIsAffected: 'DPIIT-recognized startups, patent attorneys, academic incubators, and individual inventors.',
    relevance: 'Reduces compliance cost and time burden for technology-driven enterprises.',
    keyAnnouncement: 'Automated 80% fee rebate and 120-day maximum examination turnaround for startup patent applications.',
    importantNumbers: ['80% statutory fee waiver', '120 days maximum examination window', '15,000+ patents filed under scheme'],
    previousRule: 'Mandatory separate filing for expedited examination with complex documentary proofs and manual verification delays.',
    newRule: 'Instant automated verification via API integration between Startup India database and Indian Patent Office e-filing gateway.',
    practicalImpact: 'Startups can secure granted patents before their initial seed or Series A funding rounds.',
    actionRequired: 'Ensure Startup India registration is active and linked with your e-filing portal profile.',
    importantConditions: ['Valid Startup India recognition certificate', 'Patent must originate from indigenous R&D', 'Applicant must not be a subsidiary of a large non-startup entity'],
    officialNotification: 'S.O. 3412(E) - Patents (Amendment) Rules, 2026',
    circularNumber: 'DPIIT F.No. 5/14/2025-IPR-I',
    relatedInvestment: 'National Deep Tech Innovation Seed Fund',
    relatedScheme: 'SIPP Scheme for Facilitating Startups in Intellectual Property Protection',
    relatedOpportunity: 'Establishment of Common Facility Center (CFC) for Precision Tooling',
    relatedTender: 'tender-isro-08',
    faqs: [
      {
        question: 'Can foreign subsidiaries registered in India claim the 80% rebate?',
        answer: 'Only if the entity meets the official DPIIT startup definition regarding turnover and independent shareholding.'
      }
    ],
    whatThisUpdateMeans: 'Patent protection is no longer prohibitively expensive or slow for Indian startups, ensuring robust IP ownership.',
    content: 'To foster intellectual property creation among early-stage entrepreneurs, DPIIT has updated its startup recognition portal to allow automated expedited patent examination, cutting average approval duration down to less than four months. The 80% fee rebate has been streamlined for zero-touch digital processing.',
    factBreakdown: {
      fact: 'DPIIT automated 80% patent fee rebate and expedited examination for recognized startups.',
      source: 'Ministry of Commerce and Industry DPIIT notification dated September 8, 2026.',
      explanation: 'Reduces patent approval times to under 4 months and slashes IP legal expenses.'
    }
  },
  {
    id: 'news-mnre-04',
    title: 'Green Hydrogen Corridor Initiative Attracts ₹50,000 Crore in Private Sector Intent',
    slug: 'green-hydrogen-corridor-initiative-attracts-investment',
    description: 'Ministry of New and Renewable Energy signs landmark MoU agreements for establishing electrolyser gigafactories.',
    authority: 'Ministry of New and Renewable Energy (MNRE)',
    ministry: 'Ministry of New and Renewable Energy',
    department: 'National Green Hydrogen Mission Secretariat',
    category: 'Clean Energy',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://mnre.gov.in',
    sourceAuthority: 'MNRE Official Portal',
    sourceName: 'MNRE Press Release',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-09-06',
    effectiveDate: '2026-09-06',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'MNRE finalized binding Memorandums of Understanding (MoUs) with 12 major industrial conglomerates for green hydrogen production and electrolyser manufacturing.',
    whatChanged: 'Allocation of land banks, water linkage approvals, and transmission connectivity access in coastal industrial clusters.',
    whyItMatters: 'Positions India as a global net exporter of green hydrogen and green ammonia, decarbonizing heavy industries like steel and refining.',
    whoIsAffected: 'Renewable energy developers, electrolyser manufacturers, oil refineries, and fertilizer manufacturers.',
    relevance: 'Unlocks massive capital expenditure opportunities in green energy infrastructure and EPC contracting.',
    keyAnnouncement: 'Targeted domestic manufacturing capacity of 8 GW per annum for alkaline and PEM electrolysers by 2028.',
    importantNumbers: ['₹50,000 Crore private investment intent', '8 GW electrolyser manufacturing target', '5 Million Metric Tonnes annual H2 production goal by 2030'],
    previousRule: 'Fragmented state-level approvals and lack of uniform pipeline safety and green certification standards.',
    newRule: 'Single-window clearance for green hydrogen zones with assured open-access transmission and grid banking rights.',
    practicalImpact: 'Lowers green hydrogen production costs below USD 2 per kg, making it economically viable for industrial substitution.',
    actionRequired: 'Developers must submit environmental compliance and water-sourcing blueprints to state nodal agencies.',
    importantConditions: ['Must utilize renewable energy with prior or simultaneous grid connection', 'Strict adherence to National Green Hydrogen Standard purity criteria'],
    officialNotification: 'MNRE Resolution No. 310/22/2025-Hydrogen',
    circularNumber: 'MNRE-GH2-2026-09',
    relatedInvestment: 'Sovereign Green Bonds & Renewable Energy Infrastructure',
    relatedScheme: 'SIGHT Scheme (Strategic Interventions for Green Hydrogen Transition)',
    relatedOpportunity: 'Development of 250MW Solar Park Transmission System',
    relatedTender: 'tender-iocl-green-hydrogen-30',
    faqs: [
      {
        question: 'Are fiscal incentives provided for water desalination plants in arid coastal regions?',
        answer: 'Yes, under the SIGHT scheme, capital subsidies are available for dedicated seawater desalination units attached to hydrogen plants.'
      }
    ],
    whatThisUpdateMeans: 'India is rapidly transitioning from fossil fuel dependence to self-sustained green energy industrial ecosystems.',
    content: 'The National Green Hydrogen Mission has crossed a major milestone as leading industrial conglomerates commit capital toward domestic electrolyser manufacturing plants in Gujarat, Odisha, and Andhra Pradesh. MNRE has streamlined grid connectivity and land allotment.',
    factBreakdown: {
      fact: 'MNRE secured ₹50,000 Crore in private investment commitments for green hydrogen and electrolyser manufacturing.',
      source: 'Ministry of New and Renewable Energy official update dated September 6, 2026.',
      explanation: 'Accelerates domestic green hydrogen production to replace grey hydrogen in refineries and fertilizer units.'
    }
  },
  {
    id: 'news-meity-05',
    title: 'MeitY Launches Semiconductor Design Incubation Cohort Across Tier-2 Cities',
    slug: 'meity-launches-semiconductor-design-incubation',
    description: 'Specialized EDA tool licenses and fabrication shuttle runs provided to 100 VLSI design startups.',
    authority: 'Ministry of Electronics and Information Technology (MeitY)',
    ministry: 'Ministry of Electronics and Information Technology',
    department: 'Digital India Corporation / C-DAC',
    category: 'Semiconductors',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.meity.gov.in',
    sourceAuthority: 'MeitY Official Release',
    sourceName: 'MeitY C2S Portal Notification',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-09-05',
    effectiveDate: '2026-09-12',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'MeitY inducted 100 new Very Large Scale Integration (VLSI) design startups into the Chips to Startup (C2S) incubation network.',
    whatChanged: 'Provision of subsidized electronic design automation (EDA) software suites (Synopsys/Cadence) and sponsored Multi-Project Wafer (MPW) shuttle runs.',
    whyItMatters: 'Reduces the prohibitive upfront tooling and software license costs that historically barred Indian engineers from designing silicon chips.',
    whoIsAffected: 'Fabless semiconductor design startups, academic engineering departments, and electronic hardware incubators.',
    relevance: 'Builds a robust domestic talent pool and commercial pipeline for India’s upcoming semiconductor fabrication foundries.',
    keyAnnouncement: 'Free access to advanced 28nm and 14nm FinFET process design kits (PDKs) for selected cohort members.',
    importantNumbers: ['100 VLSI startups inducted', '₹15 Lakh average EDA software subsidy per startup', '12 partner academic institutions'],
    previousRule: 'Startups had to bear entire commercial EDA license costs and foreign foundry fabrication expenses.',
    newRule: 'Centralized government procurement of enterprise EDA licenses and subsidized foundry shuttle manufacturing runs.',
    practicalImpact: 'Enables Indian startups to tape out custom silicon chips within 12 months of incubation.',
    actionRequired: 'Interested design teams must apply through the C2S portal during quarterly open calls.',
    importantConditions: ['Must be Indian registered entity', 'IP generated must remain domiciled in India for at least 5 years'],
    officialNotification: 'MeitY Notification No. 3(3)/2025-C2S',
    circularNumber: 'MeitY-C2S-2026-04',
    relatedInvestment: 'Semiconductor Fab & Display Ecosystem Incentives',
    relatedScheme: 'Chips to Startup (C2S) Programme',
    relatedOpportunity: 'Supply of High-Purity Silicon Wafers and GaN Substrates',
    relatedTender: 'tender-drdo-15',
    faqs: [
      {
        question: 'Which foundries are partnered for MPW shuttle runs?',
        answer: 'Partnered with international foundries through C-DAC and IMEC, alongside upcoming domestic semiconductor foundries.'
      }
    ],
    whatThisUpdateMeans: 'India is actively creating a domestic fabless chip design ecosystem, empowering local engineers to build silicon for automotive, telecom, and defense sectors.',
    content: 'Under the Chips to Startup (C2S) program, MeitY has inducted a new batch of semiconductor design ventures focusing on power management ICs, IoT microcontrollers, and 5G baseband silicon. Participants receive subsidized EDA software and fabrication support.',
    factBreakdown: {
      fact: 'MeitY launched a new semiconductor design incubation cohort providing subsidized EDA tools and MPW shuttle runs.',
      source: 'Ministry of Electronics and Information Technology official release dated September 5, 2026.',
      explanation: 'Removes financial barriers for Indian fabless semiconductor startups to design and tape out custom chips.'
    }
  },
  {
    id: 'news-sebi-06',
    title: 'SEBI Introduces Social Stock Exchange Amendments to Ease Zero-Coupon Zero-Principal Instruments',
    slug: 'sebi-introduces-social-stock-exchange-amendments',
    description: 'Regulatory adjustments designed to encourage philanthropic and institutional capital flow into verified social impact projects.',
    authority: 'Securities and Exchange Board of India (SEBI)',
    ministry: 'Ministry of Finance',
    department: 'Market Regulation Department',
    category: 'Capital Markets',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.sebi.gov.in',
    sourceAuthority: 'SEBI Circular',
    sourceName: 'SEBI Official Gazetted Regulation',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-09-04',
    effectiveDate: '2026-09-20',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'SEBI amended the Issue of Capital and Disclosure Requirements (ICDR) regulations to reduce minimum issue size and compliance friction on the Social Stock Exchange (SSE).',
    whatChanged: 'Minimum issue size for Zero Coupon Zero Principal (ZCZP) instruments reduced from ₹1 Crore to ₹50 Lakhs, and audit requirements simplified for smaller non-profits.',
    whyItMatters: 'Enables grassroots non-profit organizations (NPOs) and social enterprises to raise public capital transparently from retail and institutional impact investors.',
    whoIsAffected: 'Non-profit organizations, social impact funds, stock exchanges (BSE/NSE), and socially responsible investors.',
    relevance: 'Creates verified investment and philanthropic channels for institutional and retail investors seeking measurable social outcomes.',
    keyAnnouncement: 'Relaxation of public issue thresholds and streamlined social audit parameters for SSE-listed entities.',
    importantNumbers: ['₹50 Lakh minimum issue size (lowered from ₹1 Cr)', '100+ registered social enterprises on SSE', 'Zero capital gains tax on philanthropic ZCZP transfers'],
    previousRule: 'High minimum issue size of ₹1 Crore and rigorous quarterly compliance reporting that deterred smaller NPOs.',
    newRule: 'Lowered financial thresholds and half-yearly social impact reporting verified by empanelled Social Audit Organizations (SAOs).',
    practicalImpact: 'Expands the pipeline of investable social projects in healthcare, education, and rural livelihoods.',
    actionRequired: 'NPOs seeking capital must register with the SSE segment on BSE or NSE and obtain a valid social audit certificate.',
    importantConditions: ['Must be registered as a Section 8 company or registered trust/society for at least 3 years', 'Must demonstrate active engagement in eligible social activities'],
    officialNotification: 'SEBI/LAD-NRO/GN/2026/18 - ICDR (Amendment) Regulations, 2026',
    circularNumber: 'SEBI/HO/CFD/PoD-1/P/CIR/2026/84',
    relatedInvestment: 'Sovereign Green Bonds & Impact Investment Funds',
    relatedScheme: 'Corporate Social Responsibility (CSR) Ecosystem Guidelines',
    relatedOpportunity: 'Establishment of Common Facility Center (CFC) for Precision Tooling',
    relatedTender: 'tender-nainital-jal-21',
    faqs: [
      {
        question: 'Do investors receive financial returns on ZCZP instruments?',
        answer: 'No, ZCZP instruments are philanthropic grants structured as securities; investors receive social impact reports rather than monetary interest or dividends.'
      }
    ],
    whatThisUpdateMeans: 'Philanthropy in India is moving toward public exchange-traded transparency, allowing donors to track the exact utilization and impact of their capital.',
    content: 'SEBI has simplified listing norms on the Social Stock Exchange, permitting social enterprises and non-profit organizations to raise capital through zero-coupon zero-principal instruments with reduced compliance burdens and lower minimum issue thresholds.',
    factBreakdown: {
      fact: 'SEBI amended ICDR regulations to lower SSE minimum issue size to ₹50 Lakhs for ZCZP instruments.',
      source: 'Securities and Exchange Board of India regulatory circular dated September 4, 2026.',
      explanation: 'Makes it easier for grassroots non-profits to raise public philanthropic capital on BSE and NSE.'
    }
  },
  {
    id: 'news-msme-07',
    title: 'Ministry of MSME Expands Credit Guarantee Scheme Cover to ₹5 Crores per Enterprise',
    slug: 'ministry-msme-expands-credit-guarantee-cover',
    description: 'Collateral-free institutional credit access enhanced to support capital modernization and export scaling for manufacturing units.',
    authority: 'Ministry of MSME',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    department: 'CGTMSE (Credit Guarantee Fund Trust for Micro and Small Enterprises)',
    category: 'MSME Growth',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://msme.gov.in',
    sourceAuthority: 'Ministry of MSME Gazette Notification',
    sourceName: 'CGTMSE Operational Guidelines Update',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-09-02',
    effectiveDate: '2026-09-05',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE) raised the maximum collateral-free loan guarantee ceiling from ₹2 Crores to ₹5 Crores.',
    whatChanged: 'Eligible manufacturing MSMEs can now secure institutional bank loans up to ₹5 Crores without providing third-party collateral or mortgage, backed by sovereign guarantee.',
    whyItMatters: 'Lack of immovable collateral is the primary bottleneck preventing growing manufacturing MSMEs from upgrading machinery and scaling exports.',
    whoIsAffected: 'Registered Udyam MSMEs, scheduled commercial banks, regional rural banks, and NBFC lenders.',
    relevance: 'Directly facilitates capital expenditure and equipment acquisition for small and medium manufacturing enterprises.',
    keyAnnouncement: 'Enhancement of CGTMSE guarantee ceiling to ₹5 Crores with concessional annual guarantee fees for women-led enterprises.',
    importantNumbers: ['₹5 Crore maximum loan cover (increased from ₹2 Cr)', '85% sovereign guarantee coverage for micro enterprises', '10,000+ MSMEs targeted in current fiscal'],
    previousRule: 'Maximum collateral-free loan limit under CGTMSE was capped at ₹2 Crores with higher guarantee fees.',
    newRule: 'Revised ceiling of ₹5 Crores with tiered risk-based guarantee fee structures and automated digital claim settlement.',
    practicalImpact: 'MSMEs can finance advanced CNC machinery, automation lines, and testing equipment without mortgaging promoter real estate.',
    actionRequired: 'Approach member lending institutions (MLIs) with Udyam registration and verified GST returns to apply for enhanced CGTMSE loans.',
    importantConditions: ['Must hold active Udyam Registration', 'Satisfactory credit bureau history', 'Loan proceeds must be utilized strictly for capital expenditure or working capital expansion'],
    officialNotification: 'CGTMSE/Circular No. 226/2026-27',
    circularNumber: 'MSME-F.No. 1(4)/2025-Credit',
    relatedInvestment: 'Collateral-Free MSME Growth Debt Funds',
    relatedScheme: 'Credit Guarantee Scheme for Micro and Small Enterprises (CGTMSE)',
    relatedOpportunity: 'Establishment of Common Facility Center (CFC) for Precision Tooling',
    relatedTender: 'tender-nmcc-17',
    faqs: [
      {
        question: 'Is there any concession for women entrepreneurs under this expanded scheme?',
        answer: 'Yes, women-managed micro and small enterprises receive an additional 10% concession on annual guarantee fees.'
      }
    ],
    whatThisUpdateMeans: 'Banks can now lend up to ₹5 Crores to promising manufacturing MSMEs with complete confidence backed by government credit guarantees, fueling industrial growth.',
    content: 'The Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE) has revised its ceiling, allowing eligible manufacturing units to access collateral-free bank loans backed by sovereign guarantee support up to ₹5 Crores.',
    factBreakdown: {
      fact: 'Ministry of MSME expanded CGTMSE collateral-free credit guarantee limit from ₹2 Crores to ₹5 Crores.',
      source: 'Ministry of MSME official press release dated September 2, 2026.',
      explanation: 'Empowers manufacturing MSMEs to secure large institutional term loans for technology upgrade without real estate collateral.'
    }
  },
  {
    id: 'news-nhai-08',
    title: 'NHAI Monetizes Highway Bundles Worth ₹15,000 Crore via Infrastructure Investment Trusts',
    slug: 'nhai-monetizes-highway-bundles-via-invits',
    description: 'Institutional and retail investors participate in robust toll-operates-transfer (TOT) asset monetization rounds.',
    authority: 'National Highways Authority of India (NHAI)',
    ministry: 'Ministry of Road Transport and Highways (MoRTH)',
    department: 'NHAI Monetization Cell',
    category: 'Infrastructure',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://nhai.gov.in',
    sourceAuthority: 'NHAI Official Bulletin',
    sourceName: 'NHAI InvIT Round Announcement',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-30',
    effectiveDate: '2026-09-01',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'NHAI successfully closed its latest Infrastructure Investment Trust (InvIT) monetization round, raising ₹15,000 Crore from domestic and international institutional investors.',
    whatChanged: 'Operational national highway stretches transferred to InvIT management under Toll-Operate-Transfer (TOT) concession agreements.',
    whyItMatters: 'Recycles public capital into new greenfield highway construction without increasing sovereign fiscal deficit.',
    whoIsAffected: 'Institutional pension funds, foreign portfolio investors, retail mutual fund investors, and highway toll users.',
    relevance: 'Demonstrates robust private sector confidence in Indian transport infrastructure cash flows.',
    keyAnnouncement: 'Successful syndication of ₹15,000 Crore highway asset bundle with guaranteed yield distribution to unitholders.',
    importantNumbers: ['₹15,000 Crore total capital mobilized', '850 kilometers of operational national highways monetized', '7.8% projected annual investor yield'],
    previousRule: 'Government relied entirely on budgetary allocations and borrowings to fund national highway construction.',
    newRule: 'Perpetual asset recycling model where operational toll roads are monetized to fund fresh greenfield corridors.',
    practicalImpact: 'Accelerates the pace of expressway expansion across economically strategic transport corridors.',
    actionRequired: 'Institutional investors can trade InvIT units directly on NSE and BSE platforms.',
    importantConditions: ['Concession period capped at 20 years', 'Toll rates governed strictly by National Highways Fee Rules'],
    officialNotification: 'NHAI/InvIT/2026/R-04',
    circularNumber: 'MoRTH-NHAI-M-2026-88',
    relatedInvestment: 'Infrastructure Investment Trusts (InvITs) & Highway Toll Funds',
    relatedScheme: 'National Monetisation Pipeline (NMP)',
    relatedOpportunity: 'Four-Laning of National Highway Section with Rigid Pavement',
    relatedTender: 'tender-nhai-03',
    faqs: [
      {
        question: 'Does InvIT monetization lead to higher toll rates for commuters?',
        answer: 'No, toll rates continue to be strictly regulated by central statutory rules and annual Wholesale Price Index (WPI) adjustments.'
      }
    ],
    whatThisUpdateMeans: 'India is successfully utilizing private institutional capital to maintain and operate world-class highways while freeing up public funds for new infrastructure.',
    content: 'Demonstrating strong investor confidence in Indian transport infrastructure, NHAI successfully closed its latest Infrastructure Investment Trust (InvIT) offering, channeling domestic and foreign institutional savings into highway maintenance and expansion.',
    factBreakdown: {
      fact: 'NHAI monetized 850 km of operational highways raising ₹15,000 Crore through InvIT syndication.',
      source: 'National Highways Authority of India official bulletin dated August 30, 2026.',
      explanation: 'Recycles public capital from operational toll roads into new greenfield expressway construction.'
    }
  },
  {
    id: 'news-icmr-09',
    title: 'ICMR and BIRAC Partner to Establish National Medical Device Testing and Prototyping Hubs',
    slug: 'icmr-birac-partner-medical-device-hubs',
    description: 'Cutting regulatory hurdles for indigenous diagnostic kit manufacturers and orthopedic implant developers.',
    authority: 'Indian Council of Medical Research (ICMR) / BIRAC',
    ministry: 'Ministry of Health and Family Welfare / Department of Biotechnology',
    department: 'ICMR Innovation Cell & BIRAC',
    category: 'Medical Technology',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://main.icmr.nic.in',
    sourceAuthority: 'ICMR Joint Press Release',
    sourceName: 'ICMR-BIRAC Memorandum',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-28',
    effectiveDate: '2026-09-01',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'ICMR and BIRAC inaugurated four national medical device testing and prototyping centers equipped with ISO 13485 compliant testing machinery.',
    whatChanged: 'Startups and researchers can now perform biocompatibility testing, electrical safety audits, and accelerated aging tests domestically at subsidized rates.',
    whyItMatters: 'Previously, Indian medtech startups spent 40% of their seed capital sending prototypes to foreign laboratories for regulatory certification.',
    whoIsAffected: 'Medical device manufacturers, diagnostic kit developers, biomedical engineers, and clinical research organizations.',
    relevance: 'Accelerates CDSCO regulatory approval timelines for indigenous healthcare devices.',
    keyAnnouncement: 'Establishment of 4 regional medical device testing hubs in New Delhi, Bengaluru, Mumbai, and Hyderabad.',
    importantNumbers: ['4 regional testing hubs operational', '60% testing fee subsidy for registered startups', '30-day average testing turnaround time'],
    previousRule: 'Heavy reliance on expensive overseas accredited laboratories for ISO 10993 biocompatibility and safety testing.',
    newRule: 'World-class domestic testing infrastructure empanelled directly with Central Drugs Standard Control Organization (CDSCO).',
    practicalImpact: 'Slashes prototype testing expenses and shortens time-to-market for affordable medical diagnostic tools.',
    actionRequired: 'Submit sample testing requisitions through the ICMR-BIRAC shared research portal.',
    importantConditions: ['Prototypes must be designed and developed within India', 'Compliance with ethical committee guidelines for clinical samples'],
    officialNotification: 'ICMR/Tech/2026/MedDev-12',
    circularNumber: 'BIRAC/PR/2026/89',
    relatedInvestment: 'Healthcare & Medical Technology Venture Funds',
    relatedScheme: 'Biotechnology Industry Research Assistance Council (BIRAC) BIPP Scheme',
    relatedOpportunity: 'Supply of Advanced Robotic Surgical Systems and Navigation Consoles',
    relatedTender: 'post-aiims-09',
    faqs: [
      {
        question: 'Are test reports issued by these hubs accepted by CDSCO?',
        answer: 'Yes, all four hubs are officially accredited by NABL and recognized by CDSCO for statutory regulatory submissions.'
      }
    ],
    whatThisUpdateMeans: 'India is building sovereign testing infrastructure for medical devices, ensuring homegrown healthcare innovations can be validated and commercialized rapidly.',
    content: 'To accelerate domestic medical device commercialization, ICMR and BIRAC have inaugurated accredited testing laboratories offering subsidized biocompatibility testing, electrical safety certification, and clinical trial coordination.',
    factBreakdown: {
      fact: 'ICMR and BIRAC established 4 national medical device testing hubs offering subsidized ISO certification.',
      source: 'Indian Council of Medical Research joint release dated August 28, 2026.',
      explanation: 'Eliminates costly overseas testing requirements for Indian medical equipment and diagnostic startups.'
    }
  },
  {
    id: 'news-railways-10',
    title: 'Dedicated Freight Corridor Completes Final Link, Cutting Freight Transit Time by 40%',
    slug: 'dedicated-freight-corridor-completes-final-link',
    description: 'Heavy haul freight trains achieve average speeds of 75 km/h across Eastern and Western industrial corridors.',
    authority: 'Ministry of Railways',
    ministry: 'Ministry of Railways',
    department: 'Dedicated Freight Corridor Corporation of India (DFCCIL)',
    category: 'Logistics & Transport',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://indianrailways.gov.in',
    sourceAuthority: 'Ministry of Railways Official Release',
    sourceName: 'DFCCIL Commissioning Notice',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-26',
    effectiveDate: '2026-08-28',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'DFCCIL successfully commissioned the final connecting link of the Dedicated Freight Corridor, integrating the entire 2,843 km network.',
    whatChanged: 'Seamless movement of heavy freight trains carrying containers, coal, and cement from northern industrial hubs to western ports without passenger line congestion.',
    whyItMatters: 'Lowers logistics costs as a percentage of GDP, improves supply chain predictability, and reduces carbon emissions from road freight.',
    whoIsAffected: 'Logistics companies, manufacturing exporters, port operators, and industrial goods consumers.',
    relevance: 'Unlocks massive efficiency gains for manufacturing supply chains and industrial freight transport.',
    keyAnnouncement: 'Full operationalization of Eastern and Western DFC routes with guaranteed time-tabled freight train services.',
    importantNumbers: ['2,843 total corridor route kilometers', '40% reduction in transit times', '75 km/h average freight train operating speed'],
    previousRule: 'Freight trains shared congested passenger rail tracks, resulting in unpredictable transit times and average speeds under 25 km/h.',
    newRule: 'Dedicated high-speed freight arteries operating heavy-haul double-stack container trains on automated signaling.',
    practicalImpact: 'Enables manufacturers in northern hinterlands to reach western export terminals within 24 hours.',
    actionRequired: 'Logistics providers should book freight rake slots via the DFC e-portal for time-tabled transit.',
    importantConditions: ['Adherence to maximum axle load specifications', 'Mandatory RFID tagging on all containerized cargo'],
    officialNotification: 'DFCCIL/Operations/2026/Com-09',
    circularNumber: 'Railway Board Circular No. 42/2026',
    relatedInvestment: 'Multi-Modal Logistics Parks & Rail Freight Infrastructure',
    relatedScheme: 'PM Gati Shakti National Master Plan',
    relatedOpportunity: 'Construction of Road Over Bridges on Dedicated Freight Corridor',
    relatedTender: 'tender-dfccil-19',
    faqs: [
      {
        question: 'Can private train operators utilize the Dedicated Freight Corridor?',
        answer: 'Yes, private container train operators (PCTOs) have open access to run services upon payment of haulage charges.'
      }
    ],
    whatThisUpdateMeans: 'India’s rail logistics has entered a high-speed era, slashing cargo transit times and logistics costs to global benchmark levels.',
    content: 'With the successful commissioning of the final connecting link, the Dedicated Freight Corridor Corporation of India (DFCCIL) has officially integrated its multi-thousand-kilometer rail network, dramatically reducing cargo transit times between northern manufacturing hubs and western ports.',
    factBreakdown: {
      fact: 'DFCCIL completed the final link of the 2,843 km Dedicated Freight Corridor network.',
      source: 'Ministry of Railways official commissioning notice dated August 26, 2026.',
      explanation: 'Cuts freight transit times by 40% and separates goods traffic from congested passenger rail routes.'
    }
  },
  {
    id: 'news-agri-11',
    title: 'Ministry of Agriculture Deploys AI-Powered Crop Yield Forecasting and Digital Mandi Platform',
    slug: 'ministry-agriculture-deploys-ai-crop-forecasting',
    description: 'Integration of satellite remote sensing data with e-NAM marketplace to provide transparent price discovery for farmers.',
    authority: 'Ministry of Agriculture and Farmers Welfare',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    department: 'Department of Agriculture and Cooperation',
    category: 'AgriTech',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://agricoop.nic.in',
    sourceAuthority: 'Ministry of Agriculture Portal',
    sourceName: 'AgriTech Digital Launch Bulletin',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-24',
    effectiveDate: '2026-08-28',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The government rolled out an advanced geospatial AI agricultural intelligence platform integrated directly with the electronic National Agriculture Market (e-NAM).',
    whatChanged: 'Real-time satellite multispectral imaging combined with soil moisture sensors to forecast district-level crop yields and fair market prices.',
    whyItMatters: 'Protects smallholder farmers from distress selling by providing accurate advance production estimates and direct buyer matching.',
    whoIsAffected: 'Farmer Producer Organizations (FPOs), agricultural traders, agri-tech startups, and rural cooperatives.',
    relevance: 'Creates transparent digital market linkages and risk mitigation tools for agricultural commerce.',
    keyAnnouncement: 'Nationwide deployment of Krishi-AI geospatial forecasting dashboard accessible via mobile app.',
    importantNumbers: ['700+ districts covered', '92% forecasting accuracy benchmark', '1.8 Crore farmers linked to e-NAM'],
    previousRule: 'Manual crop surveys and delayed statistical estimates prone to regional discrepancies and price speculation.',
    newRule: 'Automated weekly satellite-based yield modeling and instantaneous digital auction price dissemination.',
    practicalImpact: 'FPOs can time their harvest storage and market sales to achieve optimal price realization.',
    actionRequired: 'FPOs should register on the e-NAM portal and link their verified bank accounts for direct digital payments.',
    importantConditions: ['Mandatory geotagging of member farm plots', 'Adherence to AGMARK quality grading standards'],
    officialNotification: 'Agri/Digital/2026/F-04',
    circularNumber: 'e-NAM Advisory No. 2026/11',
    relatedInvestment: 'AgriTech Venture Capital & Rural Supply Chain Funds',
    relatedScheme: 'Agriculture Infrastructure Fund (AIF)',
    relatedOpportunity: 'Establishment of Common Facility Center for Agri-Processing',
    relatedTender: 'tender-cppp-01',
    faqs: [
      {
        question: 'Is individual farmer data protected under this digital platform?',
        answer: 'Yes, data privacy complies strictly with the Digital Personal Data Protection (DPDP) Act, anonymizing individual holdings.'
      }
    ],
    whatThisUpdateMeans: 'Indian agriculture is embracing precision data intelligence, empowering farmers and FPOs with institutional-grade market forecasting.',
    content: 'The government has rolled out an advanced geospatial agricultural intelligence platform capable of predicting district-level crop yields weeks in advance, empowering Farmer Producer Organizations (FPOs) with better price negotiation leverage.',
    factBreakdown: {
      fact: 'Ministry of Agriculture deployed AI-powered geospatial crop forecasting across 700+ districts.',
      source: 'Ministry of Agriculture and Farmers Welfare portal bulletin dated August 24, 2026.',
      explanation: 'Integrates satellite remote sensing with e-NAM to deliver accurate yield estimates and transparent pricing.'
    }
  },
  {
    id: 'news-commerce-12',
    title: 'India-Gulf Economic Corridor Framework Agreement Signed to Boost Non-Oil Bilateral Trade',
    slug: 'india-gulf-economic-corridor-framework-signed',
    description: 'Bilateral trade pact targets USD 150 Billion in investments spanning logistics, ports, clean energy, and digital infrastructure.',
    authority: 'Ministry of Commerce and Industry',
    ministry: 'Ministry of Commerce and Industry',
    department: 'Department of Commerce (Economic Division)',
    category: 'Foreign Trade',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://commerce.gov.in',
    sourceAuthority: 'Ministry of Commerce Press Release',
    sourceName: 'India-Gulf Trade Pact Communique',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-22',
    effectiveDate: '2026-09-01',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'India and key Gulf economic partners signed a comprehensive bilateral economic corridor framework agreement.',
    whatChanged: 'Establishment of multi-modal transport links, fast-tracked customs clearance corridors, and joint investment promotion funds.',
    whyItMatters: 'Deepens strategic economic integration, secures crude oil and energy supply chains, and expands export markets for Indian engineering goods.',
    whoIsAffected: 'Exporters, shipping lines, infrastructure developers, logistics providers, and sovereign wealth funds.',
    relevance: 'Unlocks massive cross-border trade and infrastructure investment opportunities.',
    keyAnnouncement: 'Joint task force established to channel USD 150 Billion into priority transport and green energy infrastructure projects.',
    importantNumbers: ['USD 150 Billion target investment', '30% reduction in maritime transit bottlenecks', 'Unified digital customs protocol'],
    previousRule: 'Bilateral trade governed by standard WTO maritime shipping and conventional bilateral treaties without dedicated logistics corridors.',
    newRule: 'Integrated economic corridor featuring dedicated shipping lanes, rail-sea transit links, and mutual digital trade document recognition.',
    practicalImpact: 'Shortens transit times for goods moving from Indian manufacturing hubs to Middle Eastern distribution centers.',
    actionRequired: 'Exporters should utilize the revised preferential tariff certificates of origin under the corridor agreement.',
    importantConditions: ['Minimum 35% regional value content for tariff concessions', 'Compliance with bilateral sanitary and phytosanitary standards'],
    officialNotification: 'Ministry of Commerce Notification No. 44/2026-T',
    circularNumber: 'DoC-IECE-2026-08',
    relatedInvestment: 'International Trade Infrastructure & Logistics Corridors',
    relatedScheme: 'NIRVIK Scheme (Remission of Duties and Taxes on Exported Products - RoDTEP)',
    relatedOpportunity: 'Construction of Automated Hydrant Fueling System at International Airport',
    relatedTender: 'tender-customs-27',
    faqs: [
      {
        question: 'Does this agreement include digital currency trade settlements?',
        answer: 'Yes, provisions exist for bilateral local currency settlement mechanisms to reduce reliance on third-party reserve currencies.'
      }
    ],
    whatThisUpdateMeans: 'India and Gulf partners are building an unbreakable economic bridge, combining Indian manufacturing scale with Gulf sovereign capital and logistical connectivity.',
    content: 'Representing a major leap in international trade integration, India and key Gulf partners have finalized the economic corridor framework, establishing fast-tracked customs clearance protocols and joint venture investment vehicles.',
    factBreakdown: {
      fact: 'India and Gulf partners signed economic corridor framework targeting USD 150 Billion in trade and infrastructure investments.',
      source: 'Ministry of Commerce and Industry official communique dated August 22, 2026.',
      explanation: 'Establishes dedicated maritime-rail logistics corridors and digital customs integration for non-oil trade.'
    }
  },
  {
    id: 'news-dst-13',
    title: 'Anusandhan National Research Foundation (ANRF) Allocates ₹2,000 Crore for University R&D',
    slug: 'anrf-allocates-2000-crore-university-rd',
    description: 'Funding earmarked for state-of-the-art laboratories in materials science, electric vehicle battery chemistry, and photonics.',
    authority: 'Anusandhan National Research Foundation (ANRF)',
    ministry: 'Ministry of Science and Technology',
    department: 'ANRF Secretariat / Department of Science and Technology',
    category: 'Research & Science',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://anrf.gov.in',
    sourceAuthority: 'ANRF Official Portal Notice',
    sourceName: 'ANRF Research Grant Call',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-20',
    effectiveDate: '2026-09-01',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'ANRF sanctioned ₹2,000 Crore in translational research grants to academic and research institutions across India.',
    whatChanged: 'Establishment of 50 Translation Research Centers focusing on commercializable innovations in EV battery chemistry, advanced ceramics, and semiconductor materials.',
    whyItMatters: 'Historically, Indian academic research rarely translated into commercial patents; ANRF bridges this gap by mandating industry co-funding.',
    whoIsAffected: 'Universities, IITs, NITs, public research laboratories, and deep-tech industrial partners.',
    relevance: 'Fuels indigenous intellectual property creation and academic-industry collaboration.',
    keyAnnouncement: 'Launch of the Translation Research Excellence (TREX) grant program with mandatory industry partnership.',
    importantNumbers: ['₹2,000 Crore total grant allocation', '50 specialized research centers', '50% mandatory industry co-funding matching rule'],
    previousRule: 'Disjointed academic grants with minimal accountability for commercial prototype delivery or industrial transfer.',
    newRule: 'Milestone-based funding tied strictly to commercial prototype creation, patent filing, and technology transfer agreements.',
    practicalImpact: 'Accelerates domestic scientific breakthroughs into investable deep-tech startup ventures.',
    actionRequired: 'Consortiums of academic institutions and registered industrial partners must submit joint grant proposals on the ANRF portal.',
    importantConditions: ['Must include a commercial industry partner willing to co-fund at least 50%', 'IP ownership sharing agreement pre-signed'],
    officialNotification: 'ANRF/TREX/2026/Grants-02',
    circularNumber: 'DST-ANRF-2026-15',
    relatedInvestment: 'Deep Tech R&D Venture Funds',
    relatedScheme: 'Anusandhan National Research Foundation Act Framework',
    relatedOpportunity: 'Establishment of Common Facility Center for Precision Tooling',
    relatedTender: 'tender-drdo-15',
    faqs: [
      {
        question: 'Can private universities apply for ANRF grants?',
        answer: 'Yes, UGC-recognized private universities meeting rigorous research infrastructure benchmarks are fully eligible to participate.'
      }
    ],
    whatThisUpdateMeans: 'India is restructuring public scientific funding so that university laboratories actively generate commercial patents and industrial solutions.',
    content: 'ANRF has sanctioned research grants to over 150 academic institutions across India under its flagship Translation Research Excellence scheme, bridging the gap between academic publications and commercial prototype development.',
    factBreakdown: {
      fact: 'ANRF allocated ₹2,000 Crore for university R&D under the Translation Research Excellence scheme.',
      source: 'Anusandhan National Research Foundation official portal notice dated August 20, 2026.',
      explanation: 'Funds 50 specialized research centers with mandatory industry co-funding for commercializing scientific breakthroughs.'
    }
  },
  {
    id: 'news-tourism-14',
    title: 'Ministry of Tourism Unveils Sustainable Eco-Tourism Circuit Development Fund',
    slug: 'ministry-tourism-unveils-eco-tourism-fund',
    description: 'Financial incentives for boutique hospitality operators and green homestay ventures adhering to zero-carbon standards.',
    authority: 'Ministry of Tourism',
    ministry: 'Ministry of Tourism',
    department: 'Development Division (Swadesh Darshan / PRASHAD)',
    category: 'Hospitality & Tourism',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://tourism.gov.in',
    sourceAuthority: 'Ministry of Tourism Press Release',
    sourceName: 'Eco-Tourism Scheme Guidelines',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-18',
    effectiveDate: '2026-08-25',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'The Ministry of Tourism launched a ₹500 Crore concessional financing scheme to support sustainable eco-tourism infrastructure.',
    whatChanged: 'Provision of interest subvention and capital subsidies for rural homestays, eco-lodges, and renewable energy-powered hospitality units.',
    whyItMatters: 'Encourages responsible tourism, preserves fragile ecological zones, and creates rural micro-entrepreneurship opportunities.',
    whoIsAffected: 'Hospitality operators, rural homestay owners, state tourism development corporations, and eco-tourist enterprises.',
    relevance: 'Unlocks sustainable hospitality development and green building construction opportunities.',
    keyAnnouncement: 'Interest subvention of 3% on commercial loans for eco-certified hospitality construction in designated heritage and wildlife zones.',
    importantNumbers: ['₹500 Crore financial outlay', '3% annual interest subvention', '100% solar and zero-plastic compliance requirement'],
    previousRule: 'Lack of targeted financial incentives for green building adoption in remote eco-tourism circuits.',
    newRule: 'Subsidized debt financing tied strictly to environmental certifications (LEED/Green Key) and waste-water recycling compliance.',
    practicalImpact: 'Reduces operational energy costs for boutique hotels while attracting conscious global travelers.',
    actionRequired: 'Apply through the National Sustainable Tourism Portal with certified architectural green blueprints.',
    importantConditions: ['Mandatory solar power generation meeting 100% of daytime energy load', 'Zero single-use plastic policy'],
    officialNotification: 'MoT/EcoTourism/2026/G-08',
    circularNumber: 'Tourism Circular No. 2026/41',
    relatedInvestment: 'Sustainable Hospitality & Tourism Infrastructure Funds',
    relatedScheme: 'Swadesh Darshan 2.0 & PRASHAD Scheme',
    relatedOpportunity: 'Construction of Cryogenic Storage & Hospitality Infrastructure',
    relatedTender: 'tender-nainital-jal-21',
    faqs: [
      {
        question: 'Are existing hotels eligible for retrofitting subsidies?',
        answer: 'Yes, existing operators upgrading to verified net-zero energy and waste systems can claim capital subsidy grants.'
      }
    ],
    whatThisUpdateMeans: 'India is championing sustainable tourism, offering financial rewards to hospitality operators who protect local ecology and achieve net-zero carbon standards.',
    content: 'The Ministry of Tourism has launched a concessional loan and subsidy scheme to encourage sustainable hospitality infrastructure development in ecologically sensitive heritage zones, emphasizing solar power, rainwater harvesting, and local handicraft integration.',
    factBreakdown: {
      fact: 'Ministry of Tourism launched a ₹500 Crore eco-tourism fund offering 3% interest subvention for green hotels.',
      source: 'Ministry of Tourism official release dated August 18, 2026.',
      explanation: 'Rewards boutique operators and homestays implementing net-zero carbon, solar, and zero-plastic standards.'
    }
  },
  {
    id: 'news-cbic-15',
    title: 'Faceless Assessment and 24x7 Customs Clearance Drive Reduces Cargo Dwell Time by 50%',
    slug: 'faceless-assessment-customs-clearance-reduces-dwell-time',
    description: 'Digital paperless processing and automated risk management systems streamline import-export operations at all major ports.',
    authority: 'Central Board of Indirect Taxes and Customs (CBIC)',
    ministry: 'Ministry of Finance',
    department: 'Directorate General of Systems and Data Management',
    category: 'Customs & Trade Facilitation',
    status: 'PUBLISHED',
    effectiveStatus: 'CURRENT',
    sourceUrl: 'https://www.cbic.gov.in',
    sourceAuthority: 'CBIC Official Notification',
    sourceName: 'Customs Trade Facilitation Report',
    verificationStatus: 'VERIFIED',
    publishedDate: '2026-08-16',
    effectiveDate: '2026-08-16',
    sourceVerificationDate: '2026-09-16',
    completenessLevel: 'COMPLETE',
    whatHappened: 'CBIC reported that nationwide rollout of 24x7 Turant Customs and automated electronic cargo release has halved port dwell times.',
    whatChanged: 'Complete elimination of physical officer interface during bill of entry processing through algorithmic risk management system (RMS) channelling.',
    whyItMatters: 'Drastically lowers import-export transaction costs and enhances supply chain predictability for Indian manufacturers.',
    whoIsAffected: 'Importers, exporters, customs brokers, freight forwarders, and port terminal operators.',
    relevance: 'Streamlines cross-border supply chains and logistics execution.',
    keyAnnouncement: 'Mandatory 24x7 operations across all major container freight stations and customs houses.',
    importantNumbers: ['50% reduction in average cargo dwell time', '98% electronic bill of entry processing without physical intervention', '24x7 operational compliance'],
    previousRule: 'Manual document verification and restricted working hours at customs houses causing multi-day container congestion.',
    newRule: 'Automated electronic risk-based clearance operating continuously round-the-clock.',
    practicalImpact: 'Goods reach factory floors faster, reducing demurrage and warehouse holding charges.',
    actionRequired: 'Ensure electronic data interchange (EDI) filings and KYC profiles are fully updated on the ICEGATE portal.',
    importantConditions: ['Accurate commodity classification under HSN codes', 'Digital signature authentication on all shipping bills'],
    officialNotification: 'CBIC Instruction No. 18/2026-Customs',
    circularNumber: 'F.No.450/123/2025-Cus.IV',
    relatedInvestment: 'Port Infrastructure & Logistics Technology Funds',
    relatedScheme: 'Turant Customs & National Logistics Policy Framework',
    relatedOpportunity: 'Installation of High-Energy Rail-Mounted Container Scanner Portals',
    relatedTender: 'tender-customs-27',
    faqs: [
      {
        question: 'Can cargo be cleared on national holidays under the 24x7 drive?',
        answer: 'Yes, customs assessment and physical examination desks operate 365 days a year without exception.'
      }
    ],
    whatThisUpdateMeans: 'Indian customs has transformed into a fully digital, paperless, round-the-clock service, making international trade frictionless and rapid.',
    content: 'CBIC reports that nationwide implementation of faceless customs assessment and electronic container tracking has drastically improved Ease of Doing Business metrics, establishing Indian ports among the most efficient in South Asia.',
    factBreakdown: {
      fact: 'CBIC 24x7 Turant Customs drive reduced container port dwell times by 50% nationwide.',
      source: 'Central Board of Indirect Taxes and Customs official trade report dated August 16, 2026.',
      explanation: 'Automated RMS risk channels and paperless bill of entry processing eliminate physical delays.'
    }
  }
];
