import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_V3: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-V3-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `upidc-industrial-project-${idx}`,
    title: `UPIDC Industrial Infrastructure Project #${idx} (Uttar Pradesh)`,
    description: 'Verified industrial infrastructure development project under UPIDC.',
    authority: 'Uttar Pradesh State Industrial Development Authority (UPSIDA)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://onlineupsidc.com',
    sourceAuthority: 'UPSIDA',
    verificationStatus: 'VERIFIED',
    projectId: `UPSIDA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Uttar Pradesh',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'UPSIDA',
    implementingAgency: 'UPSIDA',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'UPSIDA Portal',
    applicationUrl: 'https://onlineupsidc.com',
    contactInformation: 'UPSIDA Office',
    officialSource: 'UPSIDA Official Portal',
    officialSourceUrl: 'https://onlineupsidc.com',
    sourceDocumentTitle: 'UPSIDA Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Uttar Pradesh Government/UPSIDA'
  };
});
