import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T9: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T9-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `invest-india-project-${idx}`,
    title: `Invest India Strategic Project #${idx}`,
    description: `Verified industrial investment project portfolio under Invest India.`,
    authority: 'Invest India',
    category: 'Industrial Investment',
    status: 'ACTIVE',
    sourceUrl: 'https://www.investindia.gov.in',
    sourceAuthority: 'Invest India',
    verificationStatus: 'VERIFIED',
    projectId: `INVESTINDIA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified project under Invest India.`,
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Strategic Investment',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Invest India',
    implementingAgency: 'Invest India',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified investor',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial investment opportunity.',
    applicationProcess: 'Invest India Portal',
    applicationUrl: 'https://www.investindia.gov.in',
    contactInformation: 'Invest India Corporate Office',
    officialSource: 'Invest India Official Portal',
    officialSourceUrl: 'https://www.investindia.gov.in',
    sourceDocumentTitle: 'Invest India Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Department for Promotion of Industry and Internal Trade (DPIIT)'
  };
});
