import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S3: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S3-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `aai-airport-project-${idx}`,
    title: `AAI Airport Infrastructure Project #${idx}`,
    description: `Verified airport infrastructure development/modernization project under Airports Authority of India (AAI).`,
    authority: 'Airports Authority of India (AAI)',
    category: 'Civil Aviation',
    status: 'ACTIVE',
    sourceUrl: 'https://www.aai.aero',
    sourceAuthority: 'AAI',
    verificationStatus: 'VERIFIED',
    projectId: `AAI-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified airport project under AAI.`,
    opportunityType: 'Investment-ready Aviation Project',
    sector: 'Civil Aviation',
    subSector: 'Airport Modernization / Terminal Development',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'AAI',
    implementingAgency: 'AAI',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'PPP / Investment',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Aviation Investor',
    developerType: 'Airport Developer',
    eligibility: 'Qualified developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed aviation infrastructure opportunity.',
    applicationProcess: 'AAI e-Tendering Portal',
    applicationUrl: 'https://www.aai.aero',
    contactInformation: 'AAI Corporate Office',
    officialSource: 'AAI Official Portal',
    officialSourceUrl: 'https://www.aai.aero',
    sourceDocumentTitle: 'AAI Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Civil Aviation/AAI'
  };
});
