import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T3: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T3-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `telecom-infrastructure-project-${idx}`,
    title: `Digital & Telecom Infrastructure Project #${idx}`,
    description: `Verified digital and telecom infrastructure project under Department of Telecommunications.`,
    authority: 'Department of Telecommunications',
    category: 'Digital Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://dot.gov.in',
    sourceAuthority: 'DoT',
    verificationStatus: 'VERIFIED',
    projectId: `DOT-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified telecom project under DoT.`,
    opportunityType: 'Investment-ready Telecom Infrastructure',
    sector: 'Digital Infrastructure',
    subSector: 'Fiber / Broadband Infrastructure',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Department of Telecommunications',
    implementingAgency: 'DoT',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Telecom Investor',
    developerType: 'Telecom Developer',
    eligibility: 'Qualified telecom developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed telecom infrastructure opportunity.',
    applicationProcess: 'DoT Tendering Portal',
    applicationUrl: 'https://dot.gov.in',
    contactInformation: 'DoT Office',
    officialSource: 'DoT Official Portal',
    officialSourceUrl: 'https://dot.gov.in',
    sourceDocumentTitle: 'DoT Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Department of Telecommunications'
  };
});
