import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U6: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U6-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `pidb-industrial-project-${idx}`,
    title: `PIDB Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under PIDB.',
    authority: 'Punjab Infrastructure Development Board (PIDB)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://pidb.punjab.gov.in',
    sourceAuthority: 'PIDB',
    verificationStatus: 'VERIFIED',
    projectId: `PIDB-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Punjab',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'PIDB',
    implementingAgency: 'PIDB',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'PIDB Portal',
    applicationUrl: 'https://pidb.punjab.gov.in',
    contactInformation: 'PIDB Office',
    officialSource: 'PIDB Official Portal',
    officialSourceUrl: 'https://pidb.punjab.gov.in',
    sourceDocumentTitle: 'PIDB Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Punjab Government/PIDB'
  };
});
