import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T5: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T5-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `tidco-infrastructure-project-${idx}`,
    title: `TIDCO Infrastructure Project #${idx} (Tamil Nadu)`,
    description: `Verified industrial infrastructure project under Tamil Nadu Industrial Development Corporation (TIDCO).`,
    authority: 'Tamil Nadu Industrial Development Corporation',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://tidco.com',
    sourceAuthority: 'TIDCO',
    verificationStatus: 'VERIFIED',
    projectId: `TIDCO-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified project under TIDCO.`,
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Tamil Nadu',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'TIDCO',
    implementingAgency: 'TIDCO',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'TIDCO Portal',
    applicationUrl: 'https://tidco.com',
    contactInformation: 'TIDCO Corporate Office',
    officialSource: 'TIDCO Official Portal',
    officialSourceUrl: 'https://tidco.com',
    sourceDocumentTitle: 'TIDCO Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Tamil Nadu Government/TIDCO'
  };
});
