import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U4: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U4-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `hsiidc-industrial-project-${idx}`,
    title: `HSIIDC Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under HSIIDC.',
    authority: 'Haryana State Industrial and Infrastructure Development Corporation (HSIIDC)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://hsiidc.org.in',
    sourceAuthority: 'HSIIDC',
    verificationStatus: 'VERIFIED',
    projectId: `HSIIDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Haryana',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'HSIIDC',
    implementingAgency: 'HSIIDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'HSIIDC Portal',
    applicationUrl: 'https://hsiidc.org.in',
    contactInformation: 'HSIIDC Office',
    officialSource: 'HSIIDC Official Portal',
    officialSourceUrl: 'https://hsiidc.org.in',
    sourceDocumentTitle: 'HSIIDC Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Haryana Government/HSIIDC'
  };
});
