import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_V5: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-V5-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `sidco-industrial-project-${idx}`,
    title: `SIDCO Industrial Infrastructure Project #${idx} (Tamil Nadu)`,
    description: 'Verified industrial infrastructure development project under SIDCO.',
    authority: 'Small Industries Development Corporation (SIDCO), Tamil Nadu',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://sidco.tn.gov.in',
    sourceAuthority: 'SIDCO',
    verificationStatus: 'VERIFIED',
    projectId: `SIDCO-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Tamil Nadu',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'SIDCO',
    implementingAgency: 'SIDCO',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'SIDCO Portal',
    applicationUrl: 'https://sidco.tn.gov.in',
    contactInformation: 'SIDCO Office',
    officialSource: 'SIDCO Official Portal',
    officialSourceUrl: 'https://sidco.tn.gov.in',
    sourceDocumentTitle: 'SIDCO Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Tamil Nadu Government/SIDCO'
  };
});
