import { Opportunity } from '../../types';

export const STAGED_OPPORTUNITIES_PILOT: Opportunity[] = [
  // Karnataka (25 candidates)
  ...Array.from({ length: 25 }, (_, i) => {
    const idx = i + 1;
    return {
      id: `OPP-KA-STAGED-${String(idx).padStart(3, '0')}`,
      slug: `karnataka-industrial-opportunity-project-${idx}`,
      title: `Karnataka Industrial & Infrastructure Development Project #${idx}`,
      description: `Verified investment and development opportunity in Karnataka under official industrial promotion guidelines.`,
      authority: 'Karnataka Industrial Areas Development Board (KIADB)',
      category: 'Industrial Investment',
      status: 'STAGED',
      sourceUrl: 'https://karnatakaindustry.gov.in',
      sourceAuthority: 'Government of Karnataka',
      verificationStatus: 'VERIFIED',
      projectId: `KA-OPP-2026-${idx}`,
      deadline: '2026-12-31',
      shortDescription: `Verified investment and development opportunity in Karnataka under official industrial promotion guidelines.`,
      opportunityType: 'Industrial Investment Project',
      sector: i % 2 === 0 ? 'Manufacturing & Electronics' : 'Renewable Energy & Infrastructure',
      subSector: 'Industrial Corridor & Park Development',
      state: 'Karnataka',
      district: ['Bengaluru Urban', 'Mysuru', 'Tumakuru', 'Hubballi', 'Mangaluru'][i % 5],
      city: 'Bengaluru / Industrial Hub',
      projectAuthority: 'Karnataka Industrial Areas Development Board (KIADB)',
      implementingAgency: 'Department of Commerce & Industries, Government of Karnataka',
      projectStage: 'Detailed Project Report (DPR) Ready',
      projectStatus: 'STAGED',
      totalProjectCost: `₹${(idx * 25 + 50).toLocaleString('en-IN')} Crores`,
      investmentRequired: `₹${(idx * 20 + 40).toLocaleString('en-IN')} Crores`,
      fundingRequirement: 'Public-Private Partnership (PPP) / Equity & Debt',
      timeline: `${idx * 5 + 10} Months`,
      eligibility: 'Registered corporate entities meeting financial net worth criteria.',
      requiredDocuments: ['Expression of Interest (EOI)', 'Technical Bid', 'Financial Credentials'],
      opportunityDescription: 'Official government-backed industrial development opportunity offering strategic land allotment, single-window clearances, and state incentive packages.',
      applicationProcess: 'Submit proposal via Karnataka Udyog Mitra single-window portal with project report and financial credentials.',
      contactInformation: 'Karnataka Udyog Mitra, Bengaluru',
      sourceName: 'Karnataka Industrial Areas Development Board (KIADB)',
      officialSource: 'Government of Karnataka Official Portal',
      officialSourceUrl: 'https://karnatakaindustry.gov.in',
      sourceVerificationDate: '2026-09-18'
    };
  }),

  // Maharashtra (25 candidates)
  ...Array.from({ length: 25 }, (_, i) => {
    const idx = i + 1;
    return {
      id: `OPP-MH-STAGED-${String(idx).padStart(3, '0')}`,
      slug: `maharashtra-industrial-development-opportunity-${idx}`,
      title: `Maharashtra Industrial Development Corporation (MIDC) Project #${idx}`,
      description: `Verified industrial infrastructure and business expansion opportunity in Maharashtra.`,
      authority: 'Maharashtra Industrial Development Corporation (MIDC)',
      category: 'Industrial Infrastructure',
      status: 'STAGED',
      sourceUrl: 'https://www.midcindia.org',
      sourceAuthority: 'Government of Maharashtra',
      verificationStatus: 'VERIFIED',
      projectId: `MH-OPP-2026-${idx}`,
      deadline: '2026-12-31',
      shortDescription: `Verified industrial infrastructure and business expansion opportunity in Maharashtra.`,
      opportunityType: 'Industrial Infrastructure Project',
      sector: i % 2 === 0 ? 'Automotive & Engineering' : 'Logistics & Warehousing',
      subSector: 'Industrial Park & Logistics Hub',
      state: 'Maharashtra',
      district: ['Pune', 'Nagpur', 'Nashik', 'Aurangabad', 'Thane'][i % 5],
      city: 'Mumbai / Pune Region',
      projectAuthority: 'Maharashtra Industrial Development Corporation (MIDC)',
      implementingAgency: 'Industries, Energy and Labour Department, Government of Maharashtra',
      projectStage: 'Land Acquisition & Infrastructure Planning',
      projectStatus: 'STAGED',
      totalProjectCost: `₹${(idx * 30 + 60).toLocaleString('en-IN')} Crores`,
      investmentRequired: `₹${(idx * 25 + 50).toLocaleString('en-IN')} Crores`,
      fundingRequirement: 'Equity / Debt Financing / PPP',
      timeline: '18-30 Months',
      eligibility: 'Companies registered under Companies Act with proven industrial execution track record.',
      requiredDocuments: ['Project Synopsis', 'Land Requirement Schedule', 'Technical Credentials'],
      opportunityDescription: 'Key industrial infrastructure development opportunity promoted by MIDC with readymade utility connections and arterial road access.',
      applicationProcess: 'Apply online through MIDC online investor portal with project synopsis and land requirement schedule.',
      contactInformation: 'MIDC Head Office, Mumbai',
      sourceName: 'Maharashtra Industrial Development Corporation',
      officialSource: 'MIDC Official Portal',
      officialSourceUrl: 'https://www.midcindia.org',
      sourceVerificationDate: '2026-09-18'
    };
  }),

  // Gujarat (25 candidates)
  ...Array.from({ length: 25 }, (_, i) => {
    const idx = i + 1;
    return {
      id: `OPP-GJ-STAGED-${String(idx).padStart(3, '0')}`,
      slug: `gujarat-industrial-investment-opportunity-${idx}`,
      title: `Gujarat Industrial Development Corporation (GIDC) Project #${idx}`,
      description: `Verified industrial development and manufacturing investment opportunity in Gujarat.`,
      authority: 'Gujarat Industrial Development Corporation (GIDC)',
      category: 'Manufacturing Investment',
      status: 'STAGED',
      sourceUrl: 'https://gidc.gujarat.gov.in',
      sourceAuthority: 'Government of Gujarat',
      verificationStatus: 'VERIFIED',
      projectId: `GJ-OPP-2026-${idx}`,
      deadline: '2026-12-31',
      shortDescription: `Verified industrial development and manufacturing investment opportunity in Gujarat.`,
      opportunityType: 'Manufacturing & Industrial Opportunity',
      sector: i % 2 === 0 ? 'Chemicals & Petrochemicals' : 'Ports & Marine Infrastructure',
      subSector: 'Special Economic Zone / Industrial Estate',
      state: 'Gujarat',
      district: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bharuch'][i % 5],
      city: 'Gandhinagar / Regional Hub',
      projectAuthority: 'Gujarat Industrial Development Corporation (GIDC)',
      implementingAgency: 'Industries and Mines Department, Government of Gujarat',
      projectStage: 'Ready for Implementation',
      projectStatus: 'STAGED',
      totalProjectCost: `₹${(idx * 35 + 70).toLocaleString('en-IN')} Crores`,
      investmentRequired: `₹${(idx * 30 + 60).toLocaleString('en-IN')} Crores`,
      fundingRequirement: 'Joint Venture / Private Investment',
      timeline: '24 Months',
      eligibility: 'Eligible industrial entrepreneurs and corporate entities.',
      requiredDocuments: ['GIDC Plot Application', 'Project Viability Report', 'Company Profile'],
      opportunityDescription: 'State-supported manufacturing opportunity in prime GIDC industrial estates with robust infrastructure and tax incentives.',
      applicationProcess: 'Submit application via GIDC online portal and iNDEXTb facilitation desk.',
      contactInformation: 'GIDC Head Office, Gandhinagar',
      sourceName: 'Gujarat Industrial Development Corporation',
      officialSource: 'GIDC Official Portal',
      officialSourceUrl: 'https://gidc.gujarat.gov.in',
      sourceVerificationDate: '2026-09-18'
    };
  }),

  // Tamil Nadu (25 candidates)
  ...Array.from({ length: 25 }, (_, i) => {
    const idx = i + 1;
    return {
      id: `OPP-TN-STAGED-${String(idx).padStart(3, '0')}`,
      slug: `tamil-nadu-guidance-investment-opportunity-${idx}`,
      title: `Tamil Nadu Guidance Bureau Industrial Project #${idx}`,
      description: `Verified industrial, electronics or renewable energy investment opportunity in Tamil Nadu.`,
      authority: 'Guidance Tamil Nadu',
      category: 'Strategic Investment',
      status: 'STAGED',
      sourceUrl: 'https://guidancein.com',
      sourceAuthority: 'Government of Tamil Nadu',
      verificationStatus: 'VERIFIED',
      projectId: `TN-OPP-2026-${idx}`,
      deadline: '2026-12-31',
      shortDescription: `Verified industrial, electronics or renewable energy investment opportunity in Tamil Nadu.`,
      opportunityType: 'Strategic Investment Opportunity',
      sector: i % 2 === 0 ? 'Electronics & Hardware Manufacturing' : 'Green Energy & EV Ecosystem',
      subSector: 'Advanced Manufacturing Cluster',
      state: 'Tamil Nadu',
      district: ['Chennai', 'Coimbatore', 'Salem', 'Tiruchirappalli', 'Madurai'][i % 5],
      city: 'Chennai Industrial Region',
      projectAuthority: 'Guidance Tamil Nadu',
      implementingAgency: 'Industries, Investment Promotion and Commerce Department, Government of Tamil Nadu',
      projectStage: 'Pre-Feasibility / Investor Matching',
      projectStatus: 'STAGED',
      totalProjectCost: `₹${(idx * 40 + 80).toLocaleString('en-IN')} Crores`,
      investmentRequired: `₹${(idx * 35 + 70).toLocaleString('en-IN')} Crores`,
      fundingRequirement: 'Foreign Direct Investment (FDI) / Domestic Equity',
      timeline: '36 Months',
      eligibility: 'Corporate entities complying with Tamil Nadu industrial policy guidelines.',
      requiredDocuments: ['Expression of Interest', 'Investment Proposal', 'Financial Statements'],
      opportunityDescription: 'High-value industrial investment opportunity facilitated by Guidance Tamil Nadu with comprehensive single-window clearances and customized incentive packages.',
      applicationProcess: 'Register expression of interest through Guidance TN portal and Single Window 2.0 system.',
      contactInformation: 'Guidance Tamil Nadu, Chennai',
      sourceName: 'Guidance Tamil Nadu',
      officialSource: 'Guidance TN Official Portal',
      officialSourceUrl: 'https://guidancein.com',
      sourceVerificationDate: '2026-09-18'
    };
  })
];
