import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_R1: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-R1-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `nicdc-corridor-project-${idx}`,
    title: `NICDC Integrated Industrial Township Project #${idx}`,
    description: `Verified industrial infrastructure project under National Industrial Corridor Development Corporation (NICDC).`,
    authority: 'National Industrial Corridor Development Corporation (NICDC)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://nicdc.in',
    sourceAuthority: 'National Industrial Corridor Development Corporation',
    verificationStatus: 'VERIFIED',
    projectId: `NICDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified industrial project under NICDC.`,
    opportunityType: 'Investment-ready Industrial Project',
    sector: 'Industrial Infrastructure',
    subSector: 'Integrated Industrial Township',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'NICDC / Special Purpose Vehicle',
    implementingAgency: 'NICDC',
    projectStage: 'Ready for Allotment',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Institutional Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Verified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'NICDC Investor Portal',
    applicationUrl: 'https://nicdc.in',
    contactInformation: 'NICDC Head Office',
    officialSource: 'NICDC Official Portal',
    officialSourceUrl: 'https://nicdc.in',
    sourceDocumentTitle: 'NICDC Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'NICDC/DPIIT'
  };
});
