import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T8: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T8-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `apiic-infrastructure-project-${idx}`,
    title: `APIIC Industrial Project #${idx} (Andhra Pradesh)`,
    description: `Verified industrial infrastructure project under Andhra Pradesh Industrial Infrastructure Corporation (APIIC).`,
    authority: 'Andhra Pradesh Industrial Infrastructure Corporation',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://apiic.in',
    sourceAuthority: 'APIIC',
    verificationStatus: 'VERIFIED',
    projectId: `APIIC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified project under APIIC.`,
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Andhra Pradesh',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'APIIC',
    implementingAgency: 'APIIC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'APIIC Portal',
    applicationUrl: 'https://apiic.in',
    contactInformation: 'APIIC Corporate Office',
    officialSource: 'APIIC Official Portal',
    officialSourceUrl: 'https://apiic.in',
    sourceDocumentTitle: 'APIIC Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Andhra Pradesh Government/APIIC'
  };
});
