import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T4: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T4-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `morth-logistics-project-${idx}`,
    title: `MoRTH Logistics Infrastructure Project #${idx}`,
    description: `Verified logistics infrastructure project under Ministry of Road Transport and Highways (MoRTH).`,
    authority: 'Ministry of Road Transport and Highways',
    category: 'Logistics Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://morth.nic.in',
    sourceAuthority: 'MoRTH',
    verificationStatus: 'VERIFIED',
    projectId: `MORTH-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified logistics project under MoRTH.`,
    opportunityType: 'Investment-ready Logistics Infrastructure',
    sector: 'Logistics Infrastructure',
    subSector: 'Logistics Park / Terminal',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of Road Transport and Highways',
    implementingAgency: 'MoRTH',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Logistics Investor',
    developerType: 'Logistics Developer',
    eligibility: 'Qualified logistics developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed logistics infrastructure opportunity.',
    applicationProcess: 'MoRTH Tendering Portal',
    applicationUrl: 'https://morth.nic.in',
    contactInformation: 'MoRTH Office',
    officialSource: 'MoRTH Official Portal',
    officialSourceUrl: 'https://morth.nic.in',
    sourceDocumentTitle: 'MoRTH Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Road Transport and Highways'
  };
});
