import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S1: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S1-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `seci-solar-project-${idx}`,
    title: `SECI Solar Power Investment Project #${idx}`,
    description: `Verified solar power infrastructure project promoted under Solar Energy Corporation of India Limited (SECI).`,
    authority: 'Solar Energy Corporation of India Limited (SECI)',
    category: 'Renewable Energy',
    status: 'ACTIVE',
    sourceUrl: 'https://www.seci.co.in',
    sourceAuthority: 'SECI',
    verificationStatus: 'VERIFIED',
    projectId: `SECI-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified solar project under SECI.`,
    opportunityType: 'Investment-ready Renewable Energy Project',
    sector: 'Renewable Energy',
    subSector: 'Solar Power Plant',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'SECI',
    implementingAgency: 'SECI',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Debt / Equity',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Renewable Energy Investor',
    developerType: 'Solar Developer',
    eligibility: 'Qualified renewable energy developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed solar energy opportunity.',
    applicationProcess: 'SECI Tendering Portal',
    applicationUrl: 'https://www.seci.co.in',
    contactInformation: 'SECI Corporate Office',
    officialSource: 'SECI Official Portal',
    officialSourceUrl: 'https://www.seci.co.in',
    sourceDocumentTitle: 'SECI Tender/Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of New and Renewable Energy/SECI'
  };
});
