import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T10: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T10-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `mofpi-food-project-${idx}`,
    title: `MoFPI Food Processing Infrastructure Project #${idx}`,
    description: `Verified food processing infrastructure project under Ministry of Food Processing Industries (MoFPI).`,
    authority: 'Ministry of Food Processing Industries',
    category: 'Food Processing',
    status: 'ACTIVE',
    sourceUrl: 'https://mofpi.gov.in',
    sourceAuthority: 'MoFPI',
    verificationStatus: 'VERIFIED',
    projectId: `MOFPI-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified food project under MoFPI.`,
    opportunityType: 'Investment-ready Food Processing Infrastructure',
    sector: 'Food Processing',
    subSector: 'Mega Food Park / Cold Chain',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of Food Processing Industries',
    implementingAgency: 'MoFPI',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Agro Investor',
    developerType: 'Agro Developer',
    eligibility: 'Qualified agro developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed food processing infrastructure opportunity.',
    applicationProcess: 'MoFPI Tendering Portal',
    applicationUrl: 'https://mofpi.gov.in',
    contactInformation: 'MoFPI Office',
    officialSource: 'MoFPI Official Portal',
    officialSourceUrl: 'https://mofpi.gov.in',
    sourceDocumentTitle: 'MoFPI Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Food Processing Industries'
  };
});
