import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T1: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T1-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `pm-mitra-textile-park-${idx}`,
    title: `PM MITRA Textile Park Infrastructure Project #${idx}`,
    description: `Verified textile park development project under PM MITRA Scheme.`,
    authority: 'Ministry of Textiles',
    category: 'Textile Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://texmin.nic.in',
    sourceAuthority: 'Ministry of Textiles',
    verificationStatus: 'VERIFIED',
    projectId: `PMMITRA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified textile park project under PM MITRA.`,
    opportunityType: 'Investment-ready Textile Infrastructure',
    sector: 'Textile Infrastructure',
    subSector: 'Integrated Textile Park',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of Textiles',
    implementingAgency: 'State Implementing Agency',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Textile Investor',
    developerType: 'Textile Park Developer',
    eligibility: 'Qualified textile developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed textile park infrastructure opportunity.',
    applicationProcess: 'Ministry of Textiles Portal',
    applicationUrl: 'https://texmin.nic.in',
    contactInformation: 'Ministry of Textiles Office',
    officialSource: 'Ministry of Textiles Official Portal',
    officialSourceUrl: 'https://texmin.nic.in',
    sourceDocumentTitle: 'PM MITRA Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Textiles'
  };
});
