import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_V6: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-V6-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `msme-industrial-project-${idx}`,
    title: `Ministry of MSME Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under Ministry of MSME.',
    authority: 'Ministry of Micro, Small and Medium Enterprises',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://msme.gov.in',
    sourceAuthority: 'MoMSME',
    verificationStatus: 'VERIFIED',
    projectId: `MSME-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Infrastructure',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of MSME',
    implementingAgency: 'Ministry of MSME',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'MSME Portal',
    applicationUrl: 'https://msme.gov.in',
    contactInformation: 'MSME Office',
    officialSource: 'MSME Official Portal',
    officialSourceUrl: 'https://msme.gov.in',
    sourceDocumentTitle: 'MSME Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of MSME'
  };
});
