import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_R3: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-R3-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `sagarmala-port-project-${idx}`,
    title: `Sagarmala Port Modernization Project #${idx}`,
    description: `Verified port modernization project under Sagarmala Programme.`,
    authority: 'Ministry of Ports, Shipping and Waterways',
    category: 'Port Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://sagarmala.gov.in',
    sourceAuthority: 'Ministry of Ports, Shipping and Waterways',
    verificationStatus: 'VERIFIED',
    projectId: `SAGARMALA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified port project under Sagarmala.`,
    opportunityType: 'Investment-ready Port Project',
    sector: 'Port Infrastructure',
    subSector: 'Port Modernization / Terminal Development',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Sagarmala Development Company',
    implementingAgency: 'Ministry of Ports, Shipping and Waterways',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'PPP / Investment',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Maritime Investor',
    developerType: 'Port Developer',
    eligibility: 'Qualified maritime developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed port infrastructure opportunity.',
    applicationProcess: 'Sagarmala Portal',
    applicationUrl: 'https://sagarmala.gov.in',
    contactInformation: 'Sagarmala Secretariat',
    officialSource: 'Sagarmala Official Portal',
    officialSourceUrl: 'https://sagarmala.gov.in',
    sourceDocumentTitle: 'Sagarmala Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Ports, Shipping and Waterways/Sagarmala'
  };
});
