import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T7: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T7-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `gidc-infrastructure-project-${idx}`,
    title: `GIDC Industrial Project #${idx} (Gujarat)`,
    description: `Verified industrial infrastructure project under Gujarat Industrial Development Corporation (GIDC).`,
    authority: 'Gujarat Industrial Development Corporation',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://gidc.gujarat.gov.in',
    sourceAuthority: 'GIDC',
    verificationStatus: 'VERIFIED',
    projectId: `GIDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified project under GIDC.`,
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Gujarat',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'GIDC',
    implementingAgency: 'GIDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'GIDC Portal',
    applicationUrl: 'https://gidc.gujarat.gov.in',
    contactInformation: 'GIDC Corporate Office',
    officialSource: 'GIDC Official Portal',
    officialSourceUrl: 'https://gidc.gujarat.gov.in',
    sourceDocumentTitle: 'GIDC Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Gujarat Government/GIDC'
  };
});
