import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_V4: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-V4-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `gsidc-industrial-project-${idx}`,
    title: `GSIDC Infrastructure Project #${idx} (Goa)`,
    description: 'Verified infrastructure development project under GSIDC.',
    authority: 'Goa State Infrastructure Development Corporation (GSIDC)',
    category: 'Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://gsidc.in',
    sourceAuthority: 'GSIDC',
    verificationStatus: 'VERIFIED',
    projectId: `GSIDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified infrastructure project.',
    opportunityType: 'Investment-ready Infrastructure',
    sector: 'Infrastructure',
    subSector: 'Infrastructure Development',
    state: 'Goa',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'GSIDC',
    implementingAgency: 'GSIDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Infrastructure Investor',
    developerType: 'Infrastructure Developer',
    eligibility: 'Qualified developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed infrastructure opportunity.',
    applicationProcess: 'GSIDC Portal',
    applicationUrl: 'https://gsidc.in',
    contactInformation: 'GSIDC Office',
    officialSource: 'GSIDC Official Portal',
    officialSourceUrl: 'https://gsidc.in',
    sourceDocumentTitle: 'GSIDC Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Goa Government/GSIDC'
  };
});
