import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_V7: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-V7-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `nicdc-project-extra-${idx}`,
    title: `NICDC Infrastructure Development Project #${idx}`,
    description: 'Verified industrial infrastructure development project under NICDC.',
    authority: 'National Industrial Corridor Development Corporation (NICDC)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://nicdc.in',
    sourceAuthority: 'NICDC',
    verificationStatus: 'VERIFIED',
    projectId: `NICDC-EXTRA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'NICDC',
    implementingAgency: 'NICDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'NICDC Portal',
    applicationUrl: 'https://nicdc.in',
    contactInformation: 'NICDC Office',
    officialSource: 'NICDC Official Portal',
    officialSourceUrl: 'https://nicdc.in',
    sourceDocumentTitle: 'NICDC Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'DPIIT/NICDC'
  };
});
