import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S6: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S6-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `steel-infrastructure-project-${idx}`,
    title: `Ministry of Steel Industrial Infrastructure Project #${idx}`,
    description: `Verified steel manufacturing and downstream infrastructure project under Ministry of Steel.`,
    authority: 'Ministry of Steel',
    category: 'Steel & Manufacturing',
    status: 'ACTIVE',
    sourceUrl: 'https://steel.gov.in',
    sourceAuthority: 'Ministry of Steel',
    verificationStatus: 'VERIFIED',
    projectId: `STEEL-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified steel project under Ministry of Steel.`,
    opportunityType: 'Investment-ready Steel Project',
    sector: 'Steel & Manufacturing',
    subSector: 'Steel Manufacturing / Downstream Processing',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of Steel',
    implementingAgency: 'Ministry of Steel',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Steel Industry Investor',
    developerType: 'Steel Manufacturer',
    eligibility: 'Qualified manufacturer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed steel infrastructure opportunity.',
    applicationProcess: 'Ministry of Steel Tendering Portal',
    applicationUrl: 'https://steel.gov.in',
    contactInformation: 'Ministry of Steel Office',
    officialSource: 'Ministry of Steel Official Portal',
    officialSourceUrl: 'https://steel.gov.in',
    sourceDocumentTitle: 'Ministry of Steel Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Steel'
  };
});
