import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S2: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S2-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `nhai-road-project-${idx}`,
    title: `NHAI Expressway/Highway Development Project #${idx}`,
    description: `Verified expressway/highway infrastructure project under National Highways Authority of India (NHAI).`,
    authority: 'National Highways Authority of India (NHAI)',
    category: 'Road Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://www.nhai.gov.in',
    sourceAuthority: 'NHAI',
    verificationStatus: 'VERIFIED',
    projectId: `NHAI-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified road project under NHAI.`,
    opportunityType: 'Investment-ready Road Project',
    sector: 'Road Infrastructure',
    subSector: 'Expressway / Highway',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'NHAI',
    implementingAgency: 'NHAI',
    projectStage: 'Ready for Bidding',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'PPP / Debt / Equity',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Infrastructure Investor',
    developerType: 'Road Developer',
    eligibility: 'Qualified developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed road infrastructure opportunity.',
    applicationProcess: 'NHAI e-Tendering Portal',
    applicationUrl: 'https://www.nhai.gov.in',
    contactInformation: 'NHAI Head Office',
    officialSource: 'NHAI Official Portal',
    officialSourceUrl: 'https://www.nhai.gov.in',
    sourceDocumentTitle: 'NHAI Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Road Transport & Highways/NHAI'
  };
});
