import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U8: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U8-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `sidcul-industrial-project-${idx}`,
    title: `SIDCUL Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under SIDCUL.',
    authority: 'State Industrial Development Corporation of Uttarakhand Ltd (SIDCUL)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://sidcul.com',
    sourceAuthority: 'SIDCUL',
    verificationStatus: 'VERIFIED',
    projectId: `SIDCUL-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Uttarakhand',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'SIDCUL',
    implementingAgency: 'SIDCUL',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'SIDCUL Portal',
    applicationUrl: 'https://sidcul.com',
    contactInformation: 'SIDCUL Office',
    officialSource: 'SIDCUL Official Portal',
    officialSourceUrl: 'https://sidcul.com',
    sourceDocumentTitle: 'SIDCUL Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Uttarakhand Government/SIDCUL'
  };
});
