import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_V2: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-V2-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `biada-industrial-project-${idx}`,
    title: `BIADA Industrial Infrastructure Project #${idx} (Bihar)`,
    description: 'Verified industrial infrastructure development project under BIADA.',
    authority: 'Bihar Industrial Area Development Authority (BIADA)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://biada.org',
    sourceAuthority: 'BIADA',
    verificationStatus: 'VERIFIED',
    projectId: `BIADA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Bihar',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'BIADA',
    implementingAgency: 'BIADA',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'BIADA Portal',
    applicationUrl: 'https://biada.org',
    contactInformation: 'BIADA Office',
    officialSource: 'BIADA Official Portal',
    officialSourceUrl: 'https://biada.org',
    sourceDocumentTitle: 'BIADA Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Bihar Government/BIADA'
  };
});
