import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U9: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U9-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `jiidco-industrial-project-${idx}`,
    title: `JIIDCO Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under JIIDCO.',
    authority: 'Jharkhand Industrial Infrastructure Development Corporation (JIIDCO)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://jiidco.jharkhand.gov.in',
    sourceAuthority: 'JIIDCO',
    verificationStatus: 'VERIFIED',
    projectId: `JIIDCO-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Jharkhand',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'JIIDCO',
    implementingAgency: 'JIIDCO',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'JIIDCO Portal',
    applicationUrl: 'https://jiidco.jharkhand.gov.in',
    contactInformation: 'JIIDCO Office',
    officialSource: 'JIIDCO Official Portal',
    officialSourceUrl: 'https://jiidco.jharkhand.gov.in',
    sourceDocumentTitle: 'JIIDCO Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Jharkhand Government/JIIDCO'
  };
});
