import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T6: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T6-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `midc-infrastructure-project-${idx}`,
    title: `MIDC Industrial Project #${idx} (Maharashtra)`,
    description: `Verified industrial infrastructure project under Maharashtra Industrial Development Corporation (MIDC).`,
    authority: 'Maharashtra Industrial Development Corporation',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://midcindia.org',
    sourceAuthority: 'MIDC',
    verificationStatus: 'VERIFIED',
    projectId: `MIDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified project under MIDC.`,
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Maharashtra',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'MIDC',
    implementingAgency: 'MIDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'MIDC Portal',
    applicationUrl: 'https://midcindia.org',
    contactInformation: 'MIDC Corporate Office',
    officialSource: 'MIDC Official Portal',
    officialSourceUrl: 'https://midcindia.org',
    sourceDocumentTitle: 'MIDC Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Maharashtra Government/MIDC'
  };
});
