import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U10: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U10-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `aiidc-industrial-project-${idx}`,
    title: `AIIDC Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under AIIDC.',
    authority: 'Assam Industrial Infrastructure Development Corporation (AIIDC)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://aiidc.assam.gov.in',
    sourceAuthority: 'AIIDC',
    verificationStatus: 'VERIFIED',
    projectId: `AIIDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Assam',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'AIIDC',
    implementingAgency: 'AIIDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'AIIDC Portal',
    applicationUrl: 'https://aiidc.assam.gov.in',
    contactInformation: 'AIIDC Office',
    officialSource: 'AIIDC Official Portal',
    officialSourceUrl: 'https://aiidc.assam.gov.in',
    sourceDocumentTitle: 'AIIDC Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Assam Government/AIIDC'
  };
});
