import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U1: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U1-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `hpsidc-industrial-project-${idx}`,
    title: `HPSIDC Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under HPSIDC.',
    authority: 'Himachal Pradesh State Industrial Development Corporation (HPSIDC)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://hpsidc.in',
    sourceAuthority: 'HPSIDC',
    verificationStatus: 'VERIFIED',
    projectId: `HPSIDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Estate / Infrastructure',
    state: 'Himachal Pradesh',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'HPSIDC',
    implementingAgency: 'HPSIDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'HPSIDC Portal',
    applicationUrl: 'https://hpsidc.in',
    contactInformation: 'HPSIDC Office',
    officialSource: 'HPSIDC Official Portal',
    officialSourceUrl: 'https://hpsidc.in',
    sourceDocumentTitle: 'HPSIDC Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Himachal Pradesh Government/HPSIDC'
  };
});
