import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U3: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U3-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `wbiidc-industrial-project-${idx}`,
    title: `WBIIDC Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under WBIIDC.',
    authority: 'West Bengal Industrial Infrastructure Development Corporation (WBIIDC)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://wbiidc.org',
    sourceAuthority: 'WBIIDC',
    verificationStatus: 'VERIFIED',
    projectId: `WBIIDC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'West Bengal',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'WBIIDC',
    implementingAgency: 'WBIIDC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'WBIIDC Portal',
    applicationUrl: 'https://wbiidc.org',
    contactInformation: 'WBIIDC Office',
    officialSource: 'WBIIDC Official Portal',
    officialSourceUrl: 'https://wbiidc.org',
    sourceDocumentTitle: 'WBIIDC Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'West Bengal Government/WBIIDC'
  };
});
