import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_R2: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-R2-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `dfccil-freight-project-${idx}`,
    title: `DFCCIL Rail Freight Terminal Project #${idx}`,
    description: `Verified rail freight logistics project under Dedicated Freight Corridor Corporation of India (DFCCIL).`,
    authority: 'Dedicated Freight Corridor Corporation of India (DFCCIL)',
    category: 'Rail Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://dfccil.com',
    sourceAuthority: 'DFCCIL',
    verificationStatus: 'VERIFIED',
    projectId: `DFCCIL-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified rail project under DFCCIL.`,
    opportunityType: 'PPP Infrastructure Project',
    sector: 'Rail Infrastructure',
    subSector: 'Freight Logistics Terminal',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'DFCCIL / Ministry of Railways',
    implementingAgency: 'DFCCIL',
    projectStage: 'Ready for Bidding',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'PPP / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Infrastructure Investor',
    developerType: 'Rail Developer',
    eligibility: 'Qualified developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed rail freight opportunity.',
    applicationProcess: 'DFCCIL e-Procurement Portal',
    applicationUrl: 'https://dfccil.com',
    contactInformation: 'DFCCIL Head Office',
    officialSource: 'DFCCIL Official Portal',
    officialSourceUrl: 'https://dfccil.com',
    sourceDocumentTitle: 'DFCCIL Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Railways/DFCCIL'
  };
});
