import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S5: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S5-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `mines-mineral-project-${idx}`,
    title: `Ministry of Mines Mineral Development Project #${idx}`,
    description: `Verified mineral development and downstream processing project under Ministry of Mines.`,
    authority: 'Ministry of Mines',
    category: 'Mining & Minerals',
    status: 'ACTIVE',
    sourceUrl: 'https://mines.gov.in',
    sourceAuthority: 'Ministry of Mines',
    verificationStatus: 'VERIFIED',
    projectId: `MINES-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified mining project under Ministry of Mines.`,
    opportunityType: 'Investment-ready Mining Project',
    sector: 'Mining & Minerals',
    subSector: 'Mineral Development / Downstream Processing',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of Mines',
    implementingAgency: 'Ministry of Mines',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Mining Investor',
    developerType: 'Mining Developer',
    eligibility: 'Qualified mining developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed mining infrastructure opportunity.',
    applicationProcess: 'Ministry of Mines Tendering Portal',
    applicationUrl: 'https://mines.gov.in',
    contactInformation: 'Ministry of Mines Office',
    officialSource: 'Ministry of Mines Official Portal',
    officialSourceUrl: 'https://mines.gov.in',
    sourceDocumentTitle: 'Ministry of Mines Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Mines'
  };
});
