import { OpportunityRecord } from '../../types/opportunity';
import { PaginationParams, FilterParams, PaginatedResponse } from '../../types/infrastructure';

export interface IOpportunityRepository {
  getAll(): Promise<OpportunityRecord[]>;
  getPaginated(params: PaginationParams, filters?: FilterParams): Promise<PaginatedResponse<OpportunityRecord>>;
  getBySlug(slug: string): Promise<OpportunityRecord | null>;
}

const MOCK_OPPORTUNITIES: OpportunityRecord[] = [
  {
    id: 'invest-india-ppp-1',
    slug: 'national-infrastructure-pipeline-ppp',
    title: 'National Infrastructure Pipeline (NIP) - PPP Opportunity',
    shortSummary: 'Opportunities for private participation in infrastructure projects under NIP.',
    description: 'Various infrastructure projects in energy, transport, and urban sectors offered under Public-Private Partnership models.',
    opportunityType: 'PPP Opportunity',
    sector: 'Infrastructure',
    industry: 'Energy, Transport, Urban',
    authority: 'Ministry of Finance / Invest India',
    organisation: 'Invest India',
    state: 'Pan-India',
    projectStage: 'Implementation',
    participationType: 'PPP',
    eligibility: 'As per project-specific RFP',
    applicationProcess: 'Portal application on Invest India/DPIIT platform',
    status: 'ACTIVE',
    officialSourceUrl: 'https://www.investindia.gov.in',
    sourceAuthority: 'Invest India',
    sourceType: 'Government Portal',
    lastVerifiedAt: '2026-09-11',
    verificationStatus: 'VERIFIED',
    tags: ['PPP', 'Infrastructure', 'NIP'],
    seoTitle: 'National Infrastructure Pipeline PPP Opportunities | SarkarSaathi',
    seoDescription: 'Explore Public-Private Partnership opportunities under the National Infrastructure Pipeline.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/national-infrastructure-pipeline-ppp'
  },
  {
    id: 'iig-green-hydrogen-001',
    slug: 'green-hydrogen-mission-manufacturing-opportunity',
    title: 'Green Hydrogen Mission: Electrolyzer Manufacturing Opportunity',
    shortSummary: 'Incentives and infrastructure support for Electrolyzer manufacturing.',
    description: 'Opportunities for manufacturing Electrolyzers required for Green Hydrogen production under the National Green Hydrogen Mission.',
    opportunityType: 'Investment Opportunity',
    sector: 'Renewable Energy',
    industry: 'Green Hydrogen / Manufacturing',
    authority: 'Ministry of New and Renewable Energy (MNRE)',
    organisation: 'India Investment Grid (IIG)',
    state: 'Pan-India',
    projectStage: 'Operational',
    participationType: 'Investment',
    eligibility: 'Manufacturing entities complying with MNRE guidelines',
    applicationProcess: 'Via IIG portal and MNRE directives',
    status: 'ACTIVE',
    officialSourceUrl: 'https://indiainvestmentgrid.gov.in',
    sourceAuthority: 'IIG',
    sourceType: 'Government Portal',
    lastVerifiedAt: '2026-09-12',
    verificationStatus: 'VERIFIED',
    tags: ['Green Energy', 'Manufacturing', 'Green Hydrogen'],
    seoTitle: 'Green Hydrogen Electrolyzer Manufacturing Investment Opportunity | SarkarSaathi',
    seoDescription: 'Explore investment opportunities in Electrolyzer manufacturing under the National Green Hydrogen Mission.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/green-hydrogen-mission-manufacturing-opportunity'
  },
  {
    id: 'iig-electronic-components-002',
    slug: 'electronic-components-manufacturing-opportunity',
    title: 'Electronic Components Manufacturing Opportunity',
    shortSummary: 'Investment opportunity in electronic components under PLI schemes.',
    description: 'Project opportunities for manufacturing various electronic components under the incentive schemes managed by MeitY.',
    opportunityType: 'Investment Opportunity',
    sector: 'Electronics',
    industry: 'Electronic Components / Manufacturing',
    authority: 'Ministry of Electronics and Information Technology (MeitY)',
    organisation: 'India Investment Grid (IIG)',
    state: 'Pan-India',
    projectStage: 'Conceptualization',
    participationType: 'Investment',
    eligibility: 'As per PLI scheme guidelines',
    applicationProcess: 'Via IIG portal and MeitY platform',
    status: 'ACTIVE',
    officialSourceUrl: 'https://indiainvestmentgrid.gov.in',
    sourceAuthority: 'IIG',
    sourceType: 'Government Portal',
    lastVerifiedAt: '2026-09-12',
    verificationStatus: 'NEEDS_REVIEW',
    tags: ['Electronics', 'PLI', 'Manufacturing'],
    seoTitle: 'Electronic Components Manufacturing Opportunity | SarkarSaathi',
    seoDescription: 'Explore investment opportunities for electronic components manufacturing in India.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/electronic-components-manufacturing-opportunity'
  },
  {
    id: 'pli-semiconductor-design-001',
    slug: 'pli-semiconductor-design-opportunity',
    title: 'PLI Scheme for Semiconductor Design',
    shortSummary: 'Support for semiconductor design-linked manufacturing.',
    description: 'Government incentives for semiconductor design-linked manufacturing and deployment.',
    opportunityType: 'Investment Opportunity',
    sector: 'Electronics',
    industry: 'Semiconductors',
    authority: 'Ministry of Electronics and Information Technology (MeitY)',
    organisation: 'DPIIT / MeitY',
    state: 'Pan-India',
    projectStage: 'Operational',
    participationType: 'Investment',
    eligibility: 'Manufacturing entities complying with MeitY guidelines',
    applicationProcess: 'MeitY official portal',
    status: 'ACTIVE',
    officialSourceUrl: 'https://www.meity.gov.in',
    sourceAuthority: 'MeitY',
    sourceType: 'Government Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['Semiconductor', 'PLI', 'Design'],
    seoTitle: 'PLI Scheme for Semiconductor Design | SarkarSaathi',
    seoDescription: 'Explore investment opportunities in Semiconductor Design under PLI schemes.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/pli-semiconductor-design-opportunity'
  },
  {
    id: 'nlp-logistics-park-001',
    slug: 'national-logistics-policy-logistics-park',
    title: 'National Logistics Policy: Logistics Park Development',
    shortSummary: 'Opportunities for developing multi-modal logistics parks.',
    description: 'Infrastructure opportunities for multi-modal logistics parks under the National Logistics Policy.',
    opportunityType: 'Infrastructure Opportunity',
    sector: 'Logistics',
    industry: 'Infrastructure / Logistics',
    authority: 'Ministry of Road Transport and Highways (MoRTH)',
    organisation: 'National Logistics Policy (NLP) Cell',
    state: 'Pan-India',
    projectStage: 'Implementation',
    participationType: 'PPP / Investment',
    eligibility: 'Infrastructure developers',
    applicationProcess: 'MoRTH and NLP portals',
    status: 'ACTIVE',
    officialSourceUrl: 'https://logistics.gov.in',
    sourceAuthority: 'MoRTH',
    sourceType: 'Government Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['Logistics', 'Infrastructure', 'NLP'],
    seoTitle: 'National Logistics Policy: Logistics Park Development | SarkarSaathi',
    seoDescription: 'Explore opportunities for Logistics Park development under National Logistics Policy.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/national-logistics-policy-logistics-park'
  },
  {
    id: 'pm-gati-shakti-infra-001',
    slug: 'pm-gati-shakti-integrated-infrastructure',
    title: 'PM Gati Shakti: Integrated Infrastructure Development',
    shortSummary: 'Investment in integrated infrastructure projects.',
    description: 'Opportunities for private sector investment in projects aligned with PM Gati Shakti National Master Plan.',
    opportunityType: 'Infrastructure Opportunity',
    sector: 'Infrastructure',
    industry: 'Integrated Infrastructure',
    authority: 'Department for Promotion of Industry and Internal Trade (DPIIT)',
    organisation: 'DPIIT',
    state: 'Pan-India',
    projectStage: 'Conceptualization',
    participationType: 'Investment / Partnership',
    eligibility: 'Infrastructure development firms',
    applicationProcess: 'Gati Shakti portal and DPIIT',
    status: 'ACTIVE',
    officialSourceUrl: 'https://gati-shakti.gov.in',
    sourceAuthority: 'DPIIT',
    sourceType: 'Government Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['Infrastructure', 'Gati Shakti', 'Investment'],
    seoTitle: 'PM Gati Shakti: Integrated Infrastructure Development | SarkarSaathi',
    seoDescription: 'Explore opportunities in integrated infrastructure under PM Gati Shakti.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/pm-gati-shakti-integrated-infrastructure'
  },
  {
    id: 'nicdc-dholera-sir-001',
    slug: 'dholera-special-investment-region-dsir',
    title: 'Dholera Special Investment Region (DSIR) - Industrial Smart City',
    shortSummary: 'Plug-and-play industrial land allotment and manufacturing investment in India\'s first greenfield semiconductor city.',
    description: 'Special Investment Region spanning 920 sq. km under the Delhi-Mumbai Industrial Corridor (DMIC), offering world-class trunk infrastructure, dedicated power/water utilities, high-speed road/metro connectivity, and dedicated zones for semiconductors, electronics, solar energy, aerospace, and heavy engineering.',
    opportunityType: 'Industrial City Land Allotment & Manufacturing Setup',
    sector: 'Electronics & Advanced Manufacturing',
    industry: 'Semiconductors, Electronics, Aerospace & Heavy Engineering',
    authority: 'Dholera Industrial City Development Limited (DICDL) & NICDC',
    organisation: 'Government of Gujarat & Government of India',
    state: 'Gujarat',
    city: 'Ahmedabad (Dholera)',
    projectStage: 'Operational / Land Allotment Active',
    participationType: 'Industrial Plot Allotment / Direct Investment',
    investmentRequired: 'As per plot size and sector category',
    projectValue: '₹1.5 Lakh+ Crore Trunk Infrastructure & Industrial Outlay',
    eligibility: 'Domestic and global industrial manufacturing entities, high-tech firms, and infrastructure developers',
    applicationProcess: 'Online investor single-window registration and e-allotment via Dholera Portal and NICDC platform',
    status: 'ACTIVE',
    officialSourceUrl: 'https://dholera.gujarat.gov.in',
    sourceAuthority: 'Dholera Industrial City Development Limited (DICDL)',
    sourceType: 'State Government / Central Joint Venture Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['NICDC', 'Dholera SIR', 'Semiconductor', 'Smart City', 'DMIC'],
    seoTitle: 'Dholera Special Investment Region (DSIR) Investment Opportunity | SarkarSaathi',
    seoDescription: 'Explore industrial plot allotment and investment opportunities in Dholera Special Investment Region (DSIR), Gujarat.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/dholera-special-investment-region-dsir'
  },
  {
    id: 'nicdc-auric-maharashtra-002',
    slug: 'auric-shendra-bidkin-industrial-area',
    title: 'Aurangabad Industrial City (AURIC) - Shendra Bidkin Industrial Area',
    shortSummary: 'Greenfield industrial smart city land allotment for EVs, automotive, engineering, and textile manufacturing.',
    description: 'A 10,000-acre master-planned smart industrial city under DMIC located near Chhatrapati Sambhajinagar, offering plug-and-play industrial plots, uninterrupted water/power supply, ICT-enabled civic management, and proximity to major transport corridors.',
    opportunityType: 'Industrial Smart City Plot Allotment',
    sector: 'Automotive & Clean Mobility',
    industry: 'Electric Vehicles (EV), Automotive, Engineering, Pharmaceuticals & Textiles',
    authority: 'Aurangabad Industrial Township Limited (AITL)',
    organisation: 'MIDC & NICDC Joint Venture',
    state: 'Maharashtra',
    city: 'Chhatrapati Sambhajinagar',
    projectStage: 'Operational / Land Allotment Active',
    participationType: 'Industrial Plot Leasehold / Commercial Concession',
    investmentRequired: 'Varies by industrial plot tier and activity',
    projectValue: '₹67,800+ Crore Potential Investment Horizon',
    eligibility: 'Registered industrial enterprises, original equipment manufacturers (OEMs), and ancillary suppliers',
    applicationProcess: 'E-allotment application through the official AURIC single-window investor portal',
    status: 'ACTIVE',
    officialSourceUrl: 'https://www.auric.city',
    sourceAuthority: 'Aurangabad Industrial Township Limited (AITL)',
    sourceType: 'Government Joint Venture Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['NICDC', 'AURIC', 'Automotive', 'EV', 'Maharashtra'],
    seoTitle: 'AURIC Shendra Bidkin Industrial City Investment Opportunity | SarkarSaathi',
    seoDescription: 'Explore industrial plot allotment and manufacturing investment opportunities in AURIC Maharashtra.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/auric-shendra-bidkin-industrial-area'
  },
  {
    id: 'nicdc-iitgnl-up-003',
    slug: 'integrated-industrial-township-greater-noida',
    title: 'Integrated Industrial Township Greater Noida (IITGNL)',
    shortSummary: 'Plug-and-play smart industrial city plots and commercial spaces in Delhi NCR.',
    description: 'Flagship smart industrial township spanning 747.5 acres under DMIC in Greater Noida, featuring underground utility tunnels, smart power grids, 24/7 automated waste systems, and direct connectivity to the Western Dedicated Freight Corridor and Noida International Airport.',
    opportunityType: 'Plug-and-Play Industrial Park Investment',
    sector: 'Electronics, IT & High-Tech Manufacturing',
    industry: 'Electronics, IT/ITeS, Telecommunications & Precision Engineering',
    authority: 'Integrated Industrial Township Greater Noida Limited (IITGNL)',
    organisation: 'Greater Noida Industrial Development Authority (GNIDA) & NICDC',
    state: 'Uttar Pradesh',
    city: 'Greater Noida',
    projectStage: 'Operational / Land Allotment Active',
    participationType: 'Industrial Land Allotment & Infrastructure Partnership',
    investmentRequired: 'Based on notified plot tariff and built-up area',
    projectValue: '₹10,000+ Crore Industrial Cluster',
    eligibility: 'High-tech manufacturing entities, R&D centers, IT/ITeS companies, and electronics manufacturers',
    applicationProcess: 'Online investor registration and bidding through IITGNL and Nivesh Mitra portals',
    status: 'ACTIVE',
    officialSourceUrl: 'https://iitgnl.com',
    sourceAuthority: 'IITGNL / GNIDA',
    sourceType: 'State & Central Government Enterprise Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['NICDC', 'IITGNL', 'Greater Noida', 'Smart Township', 'Electronics'],
    seoTitle: 'IITGNL Greater Noida Industrial Township Opportunity | SarkarSaathi',
    seoDescription: 'Explore industrial land allotment and business setup opportunities at IITGNL Greater Noida.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/integrated-industrial-township-greater-noida'
  },
  {
    id: 'nicdc-vikram-udyogpuri-mp-004',
    slug: 'vikram-udyogpuri-industrial-township-ujjain',
    title: 'Integrated Industrial Township Vikram Udyogpuri (Ujjain)',
    shortSummary: 'Smart manufacturing township land allotment for engineering, pharma, and food processing.',
    description: 'Smart industrial township spanning 1,100+ acres located near Ujjain on the Delhi-Mumbai Industrial Corridor node in Madhya Pradesh, offering developed industrial plots, dedicated water and power grids, effluent treatment, and logistics connectivity.',
    opportunityType: 'Industrial Plot Allotment & Business Park Setup',
    sector: 'Pharma & Precision Engineering',
    industry: 'Pharmaceuticals, Medical Devices, Heavy Engineering, Auto Components & Food Processing',
    authority: 'Vikram Udyogpuri Limited (VUL) & MPIDC',
    organisation: 'Madhya Pradesh Industrial Development Corporation & NICDC',
    state: 'Madhya Pradesh',
    city: 'Ujjain',
    projectStage: 'Operational / Land Allotment Active',
    participationType: 'Industrial Plot Allotment & Long-Term Lease',
    investmentRequired: 'As per MPIDC industrial policy and plot dimensions',
    projectValue: '₹4,000+ Crore Industrial Hub',
    eligibility: 'Manufacturing units, pharmaceutical companies, and commercial developers',
    applicationProcess: 'Apply via MPIDC MP-Invest Single Window Clearance and VUL portals',
    status: 'ACTIVE',
    officialSourceUrl: 'https://mpidc.co.in',
    sourceAuthority: 'Madhya Pradesh Industrial Development Corporation (MPIDC)',
    sourceType: 'State Industrial Agency Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['NICDC', 'MPIDC', 'Vikram Udyogpuri', 'Madhya Pradesh', 'Pharma'],
    seoTitle: 'Vikram Udyogpuri Industrial Township Investment Opportunity | SarkarSaathi',
    seoDescription: 'Explore industrial land allotment opportunities at Vikram Udyogpuri Smart Industrial Township, MP.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/vikram-udyogpuri-industrial-township-ujjain'
  },
  {
    id: 'nhlml-mmlp-jogighopa-005',
    slug: 'multi-modal-logistics-park-mmlp-jogighopa',
    title: 'Multi-Modal Logistics Park (MMLP) Jogighopa',
    shortSummary: 'First international multi-modal logistics hub development and warehousing concession in Northeast India.',
    description: 'Pioneering 317-acre Multi-Modal Logistics Park developed under the Bharatmala Pariyojana at Jogighopa, Assam. Features multi-modal integration across National Waterway-2 (Brahmaputra), broad gauge rail line, and 4-lane highway, offering private participation opportunities in warehousing, cold storage, container freight stations (CFS), and value-added logistics operations.',
    opportunityType: 'Logistics Infrastructure Concession & Warehousing Setup',
    sector: 'Logistics & Supply Chain',
    industry: 'Multi-Modal Freight, Warehousing, Cold Chain & Inland Waterway Logistics',
    authority: 'National Highways Logistics Management Limited (NHLML)',
    organisation: 'NHAI & Ministry of Road Transport and Highways (MoRTH)',
    state: 'Assam',
    city: 'Jogighopa (Bongaigaon)',
    projectStage: 'Implementation / Concession Active',
    participationType: 'Logistics Concession / Private Warehousing Facility Setup',
    investmentRequired: 'Facility-specific capital investment',
    projectValue: '₹693+ Crore Logistics Park Project',
    eligibility: 'Logistics service providers, 3PL/4PL operators, cold chain enterprises, and supply chain operators',
    applicationProcess: 'Expression of Interest and facility allotment via NHLML / MoRTH portal',
    status: 'ACTIVE',
    officialSourceUrl: 'https://morth.nic.in',
    sourceAuthority: 'National Highways Logistics Management Limited (NHLML)',
    sourceType: 'Central Public Enterprise Portal',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    tags: ['Logistics', 'MMLP', 'Bharatmala', 'NHLML', 'Assam', 'Northeast'],
    seoTitle: 'Multi-Modal Logistics Park Jogighopa Investment Opportunity | SarkarSaathi',
    seoDescription: 'Explore logistics concession and warehousing investment opportunities at MMLP Jogighopa, Assam.',
    canonicalUrl: 'https://www.sarkarsaathi.org/opportunities/multi-modal-logistics-park-mmlp-jogighopa'
  }

];

export class MockOpportunityRepository implements IOpportunityRepository {
  async getAll(): Promise<OpportunityRecord[]> {
    return MOCK_OPPORTUNITIES;
  }
  async getPaginated(params: PaginationParams, filters?: FilterParams): Promise<PaginatedResponse<OpportunityRecord>> {
    return { data: MOCK_OPPORTUNITIES, total: MOCK_OPPORTUNITIES.length, page: params.page, limit: params.limit };
  }
  async getBySlug(slug: string): Promise<OpportunityRecord | null> {
    return MOCK_OPPORTUNITIES.find(o => o.slug === slug) || null;
  }
}
