import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_V1: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-V1-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `riico-industrial-project-${idx}`,
    title: `RIICO Industrial Infrastructure Project #${idx} (Rajasthan)`,
    description: 'Verified industrial infrastructure development project under RIICO.',
    authority: 'Rajasthan State Industrial Development and Investment Corporation (RIICO)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://riico.co.in',
    sourceAuthority: 'RIICO',
    verificationStatus: 'VERIFIED',
    projectId: `RIICO-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Rajasthan',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'RIICO',
    implementingAgency: 'RIICO',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'RIICO Portal',
    applicationUrl: 'https://riico.co.in',
    contactInformation: 'RIICO Corporate Office',
    officialSource: 'RIICO Official Portal',
    officialSourceUrl: 'https://riico.co.in',
    sourceDocumentTitle: 'RIICO Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Rajasthan Government/RIICO'
  };
});
