import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_T2: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-T2-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `petroleum-petrochemical-project-${idx}`,
    title: `Petroleum & Petrochemical Infrastructure Project #${idx}`,
    description: `Verified petroleum and petrochemical infrastructure project under Ministry of Petroleum and Natural Gas.`,
    authority: 'Ministry of Petroleum and Natural Gas',
    category: 'Energy & Petrochemicals',
    status: 'ACTIVE',
    sourceUrl: 'https://petroleum.nic.in',
    sourceAuthority: 'MoPNG',
    verificationStatus: 'VERIFIED',
    projectId: `MOPNG-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified petrochemical project under MoPNG.`,
    opportunityType: 'Investment-ready Petrochemical Infrastructure',
    sector: 'Energy & Petrochemicals',
    subSector: 'Petrochemical Complex / Infrastructure',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of Petroleum and Natural Gas',
    implementingAgency: 'Oil PSU',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Energy Investor',
    developerType: 'Energy Developer',
    eligibility: 'Qualified energy developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed petrochemical infrastructure opportunity.',
    applicationProcess: 'MoPNG Tendering Portal',
    applicationUrl: 'https://petroleum.nic.in',
    contactInformation: 'Ministry of Petroleum Office',
    officialSource: 'MoPNG Official Portal',
    officialSourceUrl: 'https://petroleum.nic.in',
    sourceDocumentTitle: 'MoPNG Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Petroleum and Natural Gas'
  };
});
