import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S7: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S7-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `pharma-infrastructure-project-${idx}`,
    title: `Department of Pharmaceuticals Infrastructure Project #${idx}`,
    description: `Verified pharmaceutical manufacturing and infrastructure project under Department of Pharmaceuticals.`,
    authority: 'Department of Pharmaceuticals',
    category: 'Healthcare & Pharmaceuticals',
    status: 'ACTIVE',
    sourceUrl: 'https://pharmaceuticals.gov.in',
    sourceAuthority: 'Department of Pharmaceuticals',
    verificationStatus: 'VERIFIED',
    projectId: `PHARMA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified pharma project under Dept of Pharmaceuticals.`,
    opportunityType: 'Investment-ready Pharma Project',
    sector: 'Healthcare & Pharmaceuticals',
    subSector: 'Pharma Manufacturing / Infrastructure',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Department of Pharmaceuticals',
    implementingAgency: 'Department of Pharmaceuticals',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Pharma Investor',
    developerType: 'Pharma Developer',
    eligibility: 'Qualified pharma developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed pharma infrastructure opportunity.',
    applicationProcess: 'Dept of Pharmaceuticals Portal',
    applicationUrl: 'https://pharmaceuticals.gov.in',
    contactInformation: 'Department of Pharmaceuticals Office',
    officialSource: 'Department of Pharmaceuticals Official Portal',
    officialSourceUrl: 'https://pharmaceuticals.gov.in',
    sourceDocumentTitle: 'Department of Pharmaceuticals Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Department of Pharmaceuticals'
  };
});
