import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S4: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S4-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `ntpc-power-project-${idx}`,
    title: `NTPC Power Generation Project #${idx}`,
    description: `Verified power generation and infrastructure project under NTPC Limited.`,
    authority: 'NTPC Limited',
    category: 'Power Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://www.ntpc.co.in',
    sourceAuthority: 'NTPC',
    verificationStatus: 'VERIFIED',
    projectId: `NTPC-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified power project under NTPC.`,
    opportunityType: 'Investment-ready Power Project',
    sector: 'Power Infrastructure',
    subSector: 'Power Generation / Energy Infrastructure',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'NTPC',
    implementingAgency: 'NTPC',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Power Sector Investor',
    developerType: 'Power Developer',
    eligibility: 'Qualified power developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed power infrastructure opportunity.',
    applicationProcess: 'NTPC Tendering Portal',
    applicationUrl: 'https://www.ntpc.co.in',
    contactInformation: 'NTPC Corporate Office',
    officialSource: 'NTPC Official Portal',
    officialSourceUrl: 'https://www.ntpc.co.in',
    sourceDocumentTitle: 'NTPC Project Portfolio',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Power/NTPC'
  };
});
