import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S9: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S9-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `tourism-infrastructure-project-${idx}`,
    title: `Ministry of Tourism Infrastructure Project #${idx}`,
    description: `Verified tourism destination development project under Ministry of Tourism.`,
    authority: 'Ministry of Tourism',
    category: 'Tourism & Hospitality',
    status: 'ACTIVE',
    sourceUrl: 'https://tourism.gov.in',
    sourceAuthority: 'Ministry of Tourism',
    verificationStatus: 'VERIFIED',
    projectId: `TOURISM-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified tourism project under Ministry of Tourism.`,
    opportunityType: 'Investment-ready Tourism Project',
    sector: 'Tourism & Hospitality',
    subSector: 'Destination Development / Infrastructure',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'Ministry of Tourism',
    implementingAgency: 'Ministry of Tourism',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Tourism Investor',
    developerType: 'Tourism Developer',
    eligibility: 'Qualified tourism developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed tourism infrastructure opportunity.',
    applicationProcess: 'Ministry of Tourism Portal',
    applicationUrl: 'https://tourism.gov.in',
    contactInformation: 'Ministry of Tourism Office',
    officialSource: 'Ministry of Tourism Official Portal',
    officialSourceUrl: 'https://tourism.gov.in',
    sourceDocumentTitle: 'Ministry of Tourism Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Tourism'
  };
});
