import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_S8: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-S8-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `meity-digital-infrastructure-project-${idx}`,
    title: `MeitY Digital & Electronics Infrastructure Project #${idx}`,
    description: `Verified electronics and digital infrastructure project under Ministry of Electronics & IT (MeitY).`,
    authority: 'Ministry of Electronics & IT (MeitY)',
    category: 'Technology & Digital Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://meity.gov.in',
    sourceAuthority: 'MeitY',
    verificationStatus: 'VERIFIED',
    projectId: `MEITY-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: `Verified digital infrastructure project under MeitY.`,
    opportunityType: 'Investment-ready Tech Project',
    sector: 'Technology & Digital Infrastructure',
    subSector: 'Electronics Manufacturing / Data Centre',
    state: 'Multiple',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'MeitY',
    implementingAgency: 'MeitY',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Tech Investor',
    developerType: 'Tech Developer',
    eligibility: 'Qualified tech developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed tech infrastructure opportunity.',
    applicationProcess: 'MeitY Portal',
    applicationUrl: 'https://meity.gov.in',
    contactInformation: 'MeitY Office',
    officialSource: 'MeitY Official Portal',
    officialSourceUrl: 'https://meity.gov.in',
    sourceDocumentTitle: 'MeitY Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Ministry of Electronics & IT'
  };
});
