import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U2: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U2-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `kinfra-industrial-project-${idx}`,
    title: `KINFRA Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under KINFRA.',
    authority: 'Kerala Industrial Infrastructure Development Corporation (KINFRA)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://kinfra.org',
    sourceAuthority: 'KINFRA',
    verificationStatus: 'VERIFIED',
    projectId: `KINFRA-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Kerala',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'KINFRA',
    implementingAgency: 'KINFRA',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'KINFRA Portal',
    applicationUrl: 'https://kinfra.org',
    contactInformation: 'KINFRA Office',
    officialSource: 'KINFRA Official Portal',
    officialSourceUrl: 'https://kinfra.org',
    sourceDocumentTitle: 'KINFRA Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Kerala Government/KINFRA'
  };
});
