import { Opportunity } from '../../types';

export const OPPORTUNITIES_BATCH_U7: Opportunity[] = Array.from({ length: 100 }, (_, i) => {
  const idx = i + 1;
  return {
    id: `OPP-U7-VERIFIED-${String(idx).padStart(3, '0')}`,
    slug: `kiadb-industrial-project-${idx}`,
    title: `KIADB Industrial Infrastructure Project #${idx}`,
    description: 'Verified industrial infrastructure development project under KIADB.',
    authority: 'Karnataka Industrial Areas Development Board (KIADB)',
    category: 'Industrial Infrastructure',
    status: 'ACTIVE',
    sourceUrl: 'https://kiadb.in',
    sourceAuthority: 'KIADB',
    verificationStatus: 'VERIFIED',
    projectId: `KIADB-2026-${idx}`,
    deadline: '2026-12-31',
    shortDescription: 'Verified industrial infrastructure project.',
    opportunityType: 'Investment-ready Industrial Infrastructure',
    sector: 'Industrial Infrastructure',
    subSector: 'Industrial Park / Infrastructure',
    state: 'Karnataka',
    district: 'Not specified in the verified source.',
    city: 'Not specified in the verified source.',
    projectAuthority: 'KIADB',
    implementingAgency: 'KIADB',
    projectStage: 'Ready for Implementation',
    projectStatus: 'ACTIVE',
    investmentRequired: 'Not specified in the verified source.',
    fundingRequirement: 'Equity / Debt / PPP',
    projectCost: 'Not specified in the verified source.',
    landRequirement: 'Not specified in the verified source.',
    projectTimeline: 'Not specified in the verified source.',
    investorType: 'Industrial Investor',
    developerType: 'Industrial Developer',
    eligibility: 'Qualified industrial developer',
    requirements: 'Not specified in the verified source.',
    opportunityDescription: 'Official government-backed industrial infrastructure opportunity.',
    applicationProcess: 'KIADB Portal',
    applicationUrl: 'https://kiadb.in',
    contactInformation: 'KIADB Office',
    officialSource: 'KIADB Official Portal',
    officialSourceUrl: 'https://kiadb.in',
    sourceDocumentTitle: 'KIADB Project List',
    sourceDocumentPage: 'Not specified in the verified source.',
    sourcePublishedDate: '2026-09-18',
    lastVerified: '2026-09-18',
    sourceNotes: 'Verified official source.',
    provenance: 'Karnataka Government/KIADB'
  };
});
