import { TenderRecord } from '../../types/tender';
import { PaginationParams, FilterParams, PaginatedResponse } from '../../types/infrastructure';

export interface ITenderRepository {
  getAll(): Promise<TenderRecord[]>;
  getPaginated(params: PaginationParams, filters?: FilterParams): Promise<PaginatedResponse<TenderRecord>>;
  getBySlug(slug: string): Promise<TenderRecord | null>;
}

const MOCK_TENDERS: TenderRecord[] = [
  {
    id: 'historical-central-1',
    tenderId: 'CPPP-2023-001',
    referenceNumber: 'CPPP-2023-001',
    slug: 'historical-central-procurement-2023',
    title: 'Supply of Office Stationery for Central Govt Office',
    description: 'Procurement of stationery items for various central government ministries in Delhi.',
    organisation: 'Ministry of Finance',
    department: 'General Administration',
    issuingAuthority: 'Department of Expenditure',
    state: 'Delhi',
    tenderCategory: 'Goods',
    procurementCategory: 'Stationery',
    publishDate: '2023-01-15',
    submissionDeadline: '2023-02-15',
    status: 'ARCHIVED',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'CPPP',
    sourceUrl: 'https://eprocure.gov.in',
    sourcePortal: 'eprocure.gov.in',
    lastVerifiedAt: '2026-09-11',
    verificationStatus: 'ARCHIVED',
    seoTitle: 'Historical Tender: Office Stationery Procurement 2023',
    seoDescription: 'Details of the historical 2023 stationery procurement tender.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/historical-central-procurement-2023'
  },
  {
    id: 'active-tender-001',
    tenderId: 'CPPP-2026-0001-MEITY',
    referenceNumber: 'UNVERIFIED',
    slug: 'procurement-server-hardware-meity-2026',
    title: 'Procurement of Server Hardware for Data Center',
    description: 'Supply and installation of high-performance server hardware for data center upgrade.',
    organisation: 'Ministry of Electronics and Information Technology',
    department: 'Digital India Corporation',
    issuingAuthority: 'MeitY Procurement Division',
    state: 'Delhi',
    tenderCategory: 'Goods',
    procurementCategory: 'IT Hardware',
    publishDate: '2026-09-10',
    submissionDeadline: '2026-10-10',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'CPPP',
    sourceUrl: 'https://eprocure.gov.in',
    sourcePortal: 'eprocure.gov.in',
    lastVerifiedAt: '2026-09-12',
    verificationStatus: 'NEEDS_REVIEW',
    seoTitle: 'Active Tender: Server Hardware Procurement 2026',
    seoDescription: 'Details of the active 2026 server hardware procurement tender by MeitY.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/procurement-server-hardware-meity-2026'
  },
  {
    id: 'active-tender-002',
    tenderId: 'CPPP-2026-0002-FCI',
    referenceNumber: 'UNVERIFIED',
    slug: 'construction-silos-fci-2026',
    title: 'Construction of Silos for Food Corporation of India',
    description: 'Design, supply, and construction of steel silos for food grain storage.',
    organisation: 'Ministry of Consumer Affairs, Food and Public Distribution',
    department: 'Food Corporation of India',
    issuingAuthority: 'FCI Engineering Division',
    state: 'Punjab',
    tenderCategory: 'Works',
    procurementCategory: 'Civil Construction',
    publishDate: '2026-09-08',
    submissionDeadline: '2026-10-08',
    status: 'ACTIVE',
    corrigendumAvailable: true,
    corrigendumCount: 1,
    sourceName: 'CPPP',
    sourceUrl: 'https://eprocure.gov.in',
    sourcePortal: 'eprocure.gov.in',
    lastVerifiedAt: '2026-09-12',
    verificationStatus: 'NEEDS_REVIEW',
    seoTitle: 'Active Tender: Silo Construction FCI 2026',
    seoDescription: 'Details of the active 2026 silo construction tender by FCI.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/construction-silos-fci-2026'
  },
  {
    id: 'cil-supply-001',
    tenderId: 'CIL/2026/001',
    referenceNumber: 'CIL/2026/001',
    slug: 'coal-india-conveyor-belt-supply-2026',
    title: 'Supply of Conveyor Belts for CIL Mines',
    description: 'Procurement of high-grade conveyor belts for CIL operations.',
    organisation: 'Ministry of Coal',
    department: 'Coal India Limited',
    issuingAuthority: 'CIL Procurement Division',
    state: 'Pan-India',
    tenderCategory: 'Goods',
    procurementCategory: 'Supply',
    publishDate: '2026-09-01',
    submissionDeadline: '2026-10-15',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'Coal India Limited',
    sourceUrl: 'https://www.coalindia.in/tenders',
    sourcePortal: 'coalindia.in',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    seoTitle: 'Active Tender: Conveyor Belt Supply CIL 2026',
    seoDescription: 'Details of the active 2026 tender for conveyor belt supply by Coal India.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/coal-india-conveyor-belt-supply-2026'
  },
  {
    id: 'bhel-maintenance-001',
    tenderId: 'BHEL/MNT/2026',
    referenceNumber: 'BHEL/MNT/2026',
    slug: 'bhel-thermal-plant-maintenance-2026',
    title: 'Maintenance Services for Thermal Plant',
    description: 'Annual maintenance services for thermal power plants.',
    organisation: 'Ministry of Heavy Industries',
    department: 'Bharat Heavy Electricals Limited',
    issuingAuthority: 'BHEL Engineering',
    state: 'Pan-India',
    tenderCategory: 'Services',
    procurementCategory: 'Maintenance',
    publishDate: '2026-09-05',
    submissionDeadline: '2026-10-05',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'BHEL',
    sourceUrl: 'https://www.bhel.com/tenders',
    sourcePortal: 'bhel.com',
    lastVerifiedAt: '2026-09-13',
    verificationStatus: 'VERIFIED',
    seoTitle: 'Active Tender: BHEL Thermal Maintenance 2026',
    seoDescription: 'Details of the active 2026 tender for thermal plant maintenance by BHEL.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/bhel-thermal-plant-maintenance-2026'
  },
  {
    id: 'nhai-highway-paved-shoulder-2026',
    tenderId: 'NHAI/RO-DEL/2026/04',
    referenceNumber: 'NHAI/RO-DEL/2026/04',
    slug: 'nhai-highway-paved-shoulder-upgradation',
    title: 'Four-Laning and Paved Shoulder Upgradation of National Highway Section',
    description: 'Civil construction works for four-laning and paved shoulder upgradation of designated national highway sections under NHAI corridor development.',
    organisation: 'Ministry of Road Transport and Highways',
    department: 'National Highways Authority of India',
    issuingAuthority: 'NHAI Regional Office Delhi',
    state: 'Uttar Pradesh',
    tenderCategory: 'Works',
    procurementCategory: 'Highway Construction',
    publishDate: '2026-09-02',
    submissionDeadline: '2026-10-20',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'NHAI e-Procurement',
    sourceUrl: 'https://etenders.gov.in',
    sourcePortal: 'etenders.gov.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'NHAI Highway Paved Shoulder Upgradation Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of NHAI highway four-laning and paved shoulder construction tender.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/nhai-highway-paved-shoulder-upgradation'
  },
  {
    id: 'ireps-railway-track-renewal-2026',
    tenderId: 'IREPS/NR/2026/W-104',
    referenceNumber: 'IREPS/NR/2026/W-104',
    slug: 'railway-track-renewal-ballast-supply',
    title: 'Track Renewal and Ballast Supply Works Across Northern Railway Division',
    description: 'Procurement of ballast and execution of track renewal works to enhance railway safety and speed standards across Northern Railway division.',
    organisation: 'Ministry of Railways',
    department: 'Northern Railway',
    issuingAuthority: 'Principal Chief Engineer Office',
    state: 'Delhi',
    tenderCategory: 'Works',
    procurementCategory: 'Railway Infrastructure',
    publishDate: '2026-09-03',
    submissionDeadline: '2026-10-18',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'IREPS',
    sourceUrl: 'https://www.ireps.gov.in',
    sourcePortal: 'ireps.gov.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'Railway Track Renewal and Ballast Supply Tender IREPS 2026 | SarkarSaathi',
    seoDescription: 'Details of Indian Railways track renewal and ballast procurement tender on IREPS.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/railway-track-renewal-ballast-supply'
  },
  {
    id: 'ntpc-solapur-solar-spares-2026',
    tenderId: 'NTPC/SOLAPUR/2026/CS-09',
    referenceNumber: 'NTPC/SOLAPUR/2026/CS-09',
    slug: 'ntpc-solapur-solar-inverter-spares',
    title: 'Supply and Installation of Solar Inverter Spares at NTPC Solapur',
    description: 'Procurement, supply, and installation of specialized solar inverter replacement spares and diagnostic testing equipment at NTPC Solapur solar plant.',
    organisation: 'Ministry of Power',
    department: 'NTPC Limited',
    issuingAuthority: 'NTPC Solapur Procurement Cell',
    state: 'Maharashtra',
    tenderCategory: 'Goods',
    procurementCategory: 'Power Plant Spares',
    publishDate: '2026-09-04',
    submissionDeadline: '2026-10-12',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'NTPC e-Procurement',
    sourceUrl: 'https://etenders.gov.in',
    sourcePortal: 'etenders.gov.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'NTPC Solapur Solar Inverter Spares Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of solar inverter spares procurement tender by NTPC Solapur.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/ntpc-solapur-solar-inverter-spares'
  },
  {
    id: 'gail-pipeline-coating-2026',
    tenderId: 'GAIL/ND/C&P/C-2601',
    referenceNumber: 'GAIL/ND/C&P/C-2601',
    slug: 'gail-pipeline-anti-corrosion-coating',
    title: 'Anti-Corrosion Coating and Pipeline Maintenance Works',
    description: 'Execution of pipeline anti-corrosion wrap coating, Cathodic Protection maintenance, and integrity assessment along the Hazira-Vijaipur-Jagdishpur pipeline network.',
    organisation: 'Ministry of Petroleum and Natural Gas',
    department: 'GAIL (India) Limited',
    issuingAuthority: 'GAIL Central Procurement',
    state: 'Pan-India',
    tenderCategory: 'Services',
    procurementCategory: 'Pipeline Maintenance',
    publishDate: '2026-09-05',
    submissionDeadline: '2026-10-22',
    status: 'ACTIVE',
    corrigendumAvailable: true,
    corrigendumCount: 1,
    sourceName: 'GAIL Tender Portal',
    sourceUrl: 'https://gailonline.com',
    sourcePortal: 'gailonline.com',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'GAIL Pipeline Anti-Corrosion Coating Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of pipeline coating and maintenance tender by GAIL India.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/gail-pipeline-anti-corrosion-coating'
  },
  {
    id: 'ongc-mumbai-offshore-drilling-2026',
    tenderId: 'ONGC/MM/MUM/DRL/2026/15',
    referenceNumber: 'ONGC/MM/MUM/DRL/2026/15',
    slug: 'ongc-drilling-fluid-chemicals-procurement',
    title: 'Procurement of Specialized Drilling Fluid Chemicals and Mud Additives',
    description: 'Supply of high-performance drilling fluid chemicals and specialized mud additives for offshore drilling operations in Mumbai High asset.',
    organisation: 'Ministry of Petroleum and Natural Gas',
    department: 'Oil and Natural Gas Corporation',
    issuingAuthority: 'ONGC Materials Management',
    state: 'Maharashtra',
    tenderCategory: 'Goods',
    procurementCategory: 'Drilling Chemicals',
    publishDate: '2026-09-06',
    submissionDeadline: '2026-10-25',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'ONGC e-Procurement',
    sourceUrl: 'https://etenders.gov.in',
    sourcePortal: 'etenders.gov.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'ONGC Drilling Fluid Chemicals Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of drilling fluid chemicals procurement tender by ONGC Mumbai.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/ongc-drilling-fluid-chemicals-procurement'
  },
  {
    id: 'iocl-panipat-refinery-catalyst-2026',
    tenderId: 'IOCL/PR/M/2026/T-102',
    referenceNumber: 'IOCL/PR/M/2026/T-102',
    slug: 'iocl-panipat-refinery-hydrotreating-catalysts',
    title: 'Supply of Hydrotreating Catalysts for Panipat Refinery',
    description: 'Procurement and delivery of advanced hydrotreating catalysts for cleaner fuel production units at Indian Oil Corporation Panipat Refinery expansion.',
    organisation: 'Ministry of Petroleum and Natural Gas',
    department: 'Indian Oil Corporation Limited',
    issuingAuthority: 'IOCL Panipat Refinery Materials Dept',
    state: 'Haryana',
    tenderCategory: 'Goods',
    procurementCategory: 'Refinery Catalysts',
    publishDate: '2026-09-07',
    submissionDeadline: '2026-10-15',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'IOCL Tender Portal',
    sourceUrl: 'https://iocl.com',
    sourcePortal: 'iocl.com',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'IOCL Panipat Refinery Hydrotreating Catalysts Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of hydrotreating catalysts procurement tender by IOCL Panipat Refinery.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/iocl-panipat-refinery-hydrotreating-catalysts'
  },
  {
    id: 'bpcl-mumbai-refinery-valve-2026',
    tenderId: 'BPCL/MR/ENG/2026/V-40',
    referenceNumber: 'BPCL/MR/ENG/2026/V-40',
    slug: 'bpcl-mumbai-refinery-control-valves',
    title: 'Replacement of High-Pressure Control Valves and Actuation Units',
    description: 'Supply, calibration, and commissioning of high-pressure control valves and pneumatic actuation units for process units at BPCL Mumbai Refinery.',
    organisation: 'Ministry of Petroleum and Natural Gas',
    department: 'Bharat Petroleum Corporation Limited',
    issuingAuthority: 'BPCL Mumbai Refinery Engineering',
    state: 'Maharashtra',
    tenderCategory: 'Goods',
    procurementCategory: 'Industrial Valves',
    publishDate: '2026-09-08',
    submissionDeadline: '2026-10-16',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'BPCL e-Procurement',
    sourceUrl: 'https://bharatpetroleum.in',
    sourcePortal: 'bharatpetroleum.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'BPCL Mumbai Refinery Control Valves Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of control valves replacement tender by BPCL Mumbai Refinery.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/bpcl-mumbai-refinery-control-valves'
  },
  {
    id: 'hpcl-visakh-refinery-piping-2026',
    tenderId: 'HPCL/VR/PROJ/2026/P-88',
    referenceNumber: 'HPCL/VR/PROJ/2026/P-88',
    slug: 'hpcl-visakh-cryogenic-piping-installation',
    title: 'Cryogenic Piping Installation and Insulation Works',
    description: 'Specialized cryogenic piping installation, welding, NDT testing, and thermal insulation works for Visakh Refinery Modernization Project (VRMP).',
    organisation: 'Ministry of Petroleum and Natural Gas',
    department: 'Hindustan Petroleum Corporation Limited',
    issuingAuthority: 'HPCL Visakh Refinery Projects',
    state: 'Andhra Pradesh',
    tenderCategory: 'Works',
    procurementCategory: 'Refinery Piping Works',
    publishDate: '2026-09-09',
    submissionDeadline: '2026-10-28',
    status: 'ACTIVE',
    corrigendumAvailable: true,
    corrigendumCount: 2,
    sourceName: 'HPCL Tender Portal',
    sourceUrl: 'https://hindustanpetroleum.com',
    sourcePortal: 'hindustanpetroleum.com',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'HPCL Visakh Cryogenic Piping Installation Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of cryogenic piping installation tender for HPCL Visakh Refinery.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/hpcl-visakh-cryogenic-piping-installation'
  },
  {
    id: 'hal-nasik-avionics-test-rig-2026',
    tenderId: 'HAL/MIG/MM/2026/ATR-12',
    referenceNumber: 'HAL/MIG/MM/2026/ATR-12',
    slug: 'hal-nasik-avionics-diagnostic-test-benches',
    title: 'Procurement of Advanced Avionics Test Benches and Diagnostic Equipment',
    description: 'Acquisition of computerized avionics test benches and radar diagnostic test rigs for fighter aircraft overhaul at HAL Nasik division.',
    organisation: 'Ministry of Defence',
    department: 'Hindustan Aeronautics Limited',
    issuingAuthority: 'HAL MiG Complex Materials Management',
    state: 'Maharashtra',
    tenderCategory: 'Goods',
    procurementCategory: 'Aerospace Equipment',
    publishDate: '2026-09-01',
    submissionDeadline: '2026-10-30',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'HAL Tender Portal',
    sourceUrl: 'https://hal-india.co.in',
    sourcePortal: 'hal-india.co.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'HAL Nasik Avionics Test Benches Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of avionics test benches procurement tender by HAL Nasik.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/hal-nasik-avionics-diagnostic-test-benches'
  },
  {
    id: 'mdl-mumbai-dock-crane-2026',
    tenderId: 'MDL/SHIP/PRJ/2026/CR-04',
    referenceNumber: 'MDL/SHIP/PRJ/2026/CR-04',
    slug: 'mazagon-dock-gantry-crane-modernization',
    title: 'Modernization and Load Testing of Shipyard Gantry Cranes',
    description: 'Overhauling, electrical drive replacement, and statutory load testing of heavy-duty shipyard gantry cranes at Mazagon Dock Shipbuilders Mumbai.',
    organisation: 'Ministry of Defence',
    department: 'Mazagon Dock Shipbuilders Limited',
    issuingAuthority: 'MDL Shipbuilding Infrastructure Dept',
    state: 'Maharashtra',
    tenderCategory: 'Services',
    procurementCategory: 'Shipyard Equipment Maintenance',
    publishDate: '2026-09-02',
    submissionDeadline: '2026-10-14',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'Mazagon Dock Portal',
    sourceUrl: 'https://mazagondock.in',
    sourcePortal: 'mazagondock.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'Mazagon Dock Gantry Crane Modernization Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of shipyard gantry crane modernization tender by Mazagon Dock.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/mazagon-dock-gantry-crane-modernization'
  },
  {
    id: 'cochin-shipyard-dewatering-pumps-2026',
    tenderId: 'CSL/PROJ/MECH/2026/DP-11',
    referenceNumber: 'CSL/PROJ/MECH/2026/DP-11',
    slug: 'cochin-shipyard-dewatering-pumps-supply',
    title: 'Supply of High-Capacity Dewatering Pumps for New Dry Dock',
    description: 'Procurement and commissioning of high-discharge centrifugal dewatering pumps and heavy-duty sluice valves for Cochin Shipyard new dry dock facility.',
    organisation: 'Ministry of Ports, Shipping and Waterways',
    department: 'Cochin Shipyard Limited',
    issuingAuthority: 'CSL Mechanical Procurement Division',
    state: 'Kerala',
    tenderCategory: 'Goods',
    procurementCategory: 'Marine Machinery',
    publishDate: '2026-09-03',
    submissionDeadline: '2026-10-19',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'Cochin Shipyard Portal',
    sourceUrl: 'https://cochinshipyard.in',
    sourcePortal: 'cochinshipyard.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'Cochin Shipyard Dewatering Pumps Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of dewatering pumps procurement tender for Cochin Shipyard dry dock.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/cochin-shipyard-dewatering-pumps-supply'
  },
  {
    id: 'sci-vessel-dry-docking-2026',
    tenderId: 'SCI/TECH/DD/2026/02',
    referenceNumber: 'SCI/TECH/DD/2026/02',
    slug: 'shipping-corporation-vessel-dry-docking-repairs',
    title: 'Special Survey and Dry Docking Repairs for Bulk Carriers',
    description: 'Special survey, hull grit blasting, coating, and machinery overhaul for Shipping Corporation of India fleet vessels at certified shipyards.',
    organisation: 'Ministry of Ports, Shipping and Waterways',
    department: 'The Shipping Corporation of India Limited',
    issuingAuthority: 'SCI Technical and Fleet Management',
    state: 'Maharashtra',
    tenderCategory: 'Services',
    procurementCategory: 'Ship Repair Services',
    publishDate: '2026-09-04',
    submissionDeadline: '2026-10-17',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'SCI Tender Portal',
    sourceUrl: 'https://shipindia.com',
    sourcePortal: 'shipindia.com',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'SCI Vessel Dry Docking Repairs Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of vessel dry docking and special survey tender by Shipping Corporation of India.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/shipping-corporation-vessel-dry-docking-repairs'
  },
  {
    id: 'jnpa-container-terminal-dredging-2026',
    tenderId: 'JNPA/CIVIL/DREDGE/2026/08',
    referenceNumber: 'JNPA/CIVIL/DREDGE/2026/08',
    slug: 'jnpa-approach-channel-maintenance-dredging',
    title: 'Maintenance Dredging of Approach Channels and Turning Basins',
    description: 'Execution of capital and maintenance dredging works in navigation channels, turning basins, and berthing pockets at Jawaharlal Nehru Port.',
    organisation: 'Ministry of Ports, Shipping and Waterways',
    department: 'Jawaharlal Nehru Port Authority',
    issuingAuthority: 'JNPA Civil Engineering Department',
    state: 'Maharashtra',
    tenderCategory: 'Works',
    procurementCategory: 'Marine Dredging',
    publishDate: '2026-09-05',
    submissionDeadline: '2026-10-26',
    status: 'ACTIVE',
    corrigendumAvailable: true,
    corrigendumCount: 1,
    sourceName: 'JNPA Portal',
    sourceUrl: 'https://www.jnport.gov.in',
    sourcePortal: 'jnport.gov.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'JNPA Maintenance Dredging Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of approach channel maintenance dredging tender by JNPA.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/jnpa-approach-channel-maintenance-dredging'
  },
  {
    id: 'aai-chennai-airfield-lighting-2026',
    tenderId: 'AAI/CHAND/ENGY/2026/03',
    referenceNumber: 'AAI/CHAND/ENGY/2026/03',
    slug: 'aai-chennai-airfield-ground-lighting-upgrade',
    title: 'Upgradation of LED Airfield Ground Lighting and CAT-III Cabling',
    description: 'Supply, installation, testing, and commissioning of energy-efficient LED airfield ground lighting systems and CAT-III instrument landing system cabling at Chennai Airport.',
    organisation: 'Ministry of Civil Aviation',
    department: 'Airports Authority of India',
    issuingAuthority: 'AAI Chennai Airport Engineering Directorate',
    state: 'Tamil Nadu',
    tenderCategory: 'Works',
    procurementCategory: 'Airport Electrical Works',
    publishDate: '2026-09-06',
    submissionDeadline: '2026-10-21',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'AAI e-Tender Portal',
    sourceUrl: 'https://www.aai.aero',
    sourcePortal: 'aai.aero',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'AAI Chennai Airfield Ground Lighting Upgrade Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of airfield ground lighting and CAT-III cabling tender at Chennai Airport.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/aai-chennai-airfield-ground-lighting-upgrade'
  },
  {
    id: 'powergrid-transmission-towers-2026',
    tenderId: 'PGCIL/C&M/SER/2026/EHV-55',
    referenceNumber: 'PGCIL/C&M/SER/2026/EHV-55',
    slug: 'powergrid-765kv-transmission-tower-supply',
    title: 'Supply of Galvanized Steel Towers for 765kV Transmission Corridor',
    description: 'Fabrication and supply of heavy-duty galvanized lattice steel towers and structural hardware components for 765kV interstate power transmission corridors.',
    organisation: 'Ministry of Power',
    department: 'Power Grid Corporation of India Limited',
    issuingAuthority: 'PGCIL Contracts and Materials',
    state: 'Pan-India',
    tenderCategory: 'Goods',
    procurementCategory: 'Transmission Line Hardware',
    publishDate: '2026-09-07',
    submissionDeadline: '2026-10-24',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'POWERGRID Portal',
    sourceUrl: 'https://powergrid.in',
    sourcePortal: 'powergrid.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'POWERGRID 765kV Transmission Tower Supply Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of transmission tower supply tender by Power Grid Corporation of India.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/powergrid-765kv-transmission-tower-supply'
  },
  {
    id: 'sjvn-nathpa-jhakri-hydro-2026',
    tenderId: 'SJVN/NJHPS/MNT/2026/07',
    referenceNumber: 'SJVN/NJHPS/MNT/2026/07',
    slug: 'sjvn-hydro-turbine-runner-refurbishment',
    title: 'Overhauling and Refurbishment of Hydro Turbine Runner Blades',
    description: 'Precision machining, cavitation repair, balancing, and refurbishment of Francis turbine runner blades at Nathpa Jhakri Hydro Power Station.',
    organisation: 'Ministry of Power',
    department: 'SJVN Limited',
    issuingAuthority: 'SJVN NJHPS Electrical & Mechanical Division',
    state: 'Himachal Pradesh',
    tenderCategory: 'Services',
    procurementCategory: 'Hydro Power Maintenance',
    publishDate: '2026-09-08',
    submissionDeadline: '2026-10-18',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'SJVN Tender Portal',
    sourceUrl: 'https://sjvn.nic.in',
    sourcePortal: 'sjvn.nic.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'SJVN Hydro Turbine Runner Refurbishment Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of hydro turbine runner refurbishment tender by SJVN Limited.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/sjvn-hydro-turbine-runner-refurbishment'
  },
  {
    id: 'rec-cloud-erp-it-2026',
    tenderId: 'REC/IT/CLOUD/2026/01',
    referenceNumber: 'REC/IT/CLOUD/2026/01',
    slug: 'rec-cloud-erp-cyber-security-audit',
    title: 'Implementation of Cloud-Based ERP and Cyber Security Auditing Modules',
    description: 'Deployment of enterprise cloud resource planning platform, workflow automation tools, and comprehensive cyber security vulnerability auditing for REC Limited.',
    organisation: 'Ministry of Power',
    department: 'REC Limited',
    issuingAuthority: 'REC Information Technology Division',
    state: 'Delhi',
    tenderCategory: 'Services',
    procurementCategory: 'IT & Cloud Services',
    publishDate: '2026-09-09',
    submissionDeadline: '2026-10-15',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'REC Limited Portal',
    sourceUrl: 'https://recindia.nic.in',
    sourcePortal: 'recindia.nic.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'REC Cloud ERP and Cyber Security Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of cloud ERP and cyber security audit tender by REC Limited.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/rec-cloud-erp-cyber-security-audit'
  },
  {
    id: 'pfc-green-energy-consultancy-2026',
    tenderId: 'PFC/CONS/RE/2026/09',
    referenceNumber: 'PFC/CONS/RE/2026/09',
    slug: 'pfc-offshore-wind-green-hydrogen-advisory',
    title: 'Advisory and Consultancy Services for Offshore Wind and Green Hydrogen Project Appraisal',
    description: 'Engagement of expert consultancy firms for techno-economic viability appraisal and risk assessment of offshore wind and green hydrogen credit portfolios.',
    organisation: 'Ministry of Power',
    department: 'Power Finance Corporation Limited',
    issuingAuthority: 'PFC Consultancy Services Division',
    state: 'Delhi',
    tenderCategory: 'Services',
    procurementCategory: 'Financial & Technical Consultancy',
    publishDate: '2026-09-01',
    submissionDeadline: '2026-10-12',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'PFC Portal',
    sourceUrl: 'https://pfcindia.com',
    sourcePortal: 'pfcindia.com',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'PFC Green Energy Consultancy Advisory Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of green energy and offshore wind consultancy tender by Power Finance Corporation.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/pfc-offshore-wind-green-hydrogen-advisory'
  },
  {
    id: 'nmdc-bailadila-conveyor-spares-2026',
    tenderId: 'NMDC/BAIL/MM/2026/CB-18',
    referenceNumber: 'NMDC/BAIL/MM/2026/CB-18',
    slug: 'nmdc-heavy-duty-conveyor-rollers-procurement',
    title: 'Procurement of Heavy-Duty Conveyor Rollers and Drive Motors',
    description: 'Supply of impact roller assemblies, heavy-duty conveyor belts, and high-torque electric drive motors for Bailadila Iron Ore Mining Complex.',
    organisation: 'Ministry of Steel',
    department: 'NMDC Limited',
    issuingAuthority: 'NMDC Bailadila Materials Management',
    state: 'Chhattisgarh',
    tenderCategory: 'Goods',
    procurementCategory: 'Mining Equipment Spares',
    publishDate: '2026-09-02',
    submissionDeadline: '2026-10-16',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'NMDC e-Procurement',
    sourceUrl: 'https://nmdc.co.in',
    sourcePortal: 'nmdc.co.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'NMDC Bailadila Conveyor Spares Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of conveyor rollers and drive motors procurement tender by NMDC Bailadila.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/nmdc-heavy-duty-conveyor-rollers-procurement'
  },
  {
    id: 'moil-underground-mining-supports-2026',
    tenderId: 'MOIL/MINE/PROC/2026/SUP-03',
    referenceNumber: 'MOIL/MINE/PROC/2026/SUP-03',
    slug: 'moil-hydraulic-roof-supports-rock-bolts',
    title: 'Supply of Hydraulic Roof Supports and Rock Bolts for Underground Mines',
    description: 'Procurement of certified hydraulic props, friction roof supports, and resin-encapsulated rock bolts for underground safety reinforcement in MOIL manganese mines.',
    organisation: 'Ministry of Steel',
    department: 'MOIL Limited',
    issuingAuthority: 'MOIL Central Procurement Department',
    state: 'Madhya Pradesh',
    tenderCategory: 'Goods',
    procurementCategory: 'Underground Safety Equipment',
    publishDate: '2026-09-03',
    submissionDeadline: '2026-10-21',
    status: 'ACTIVE',
    corrigendumAvailable: false,
    corrigendumCount: 0,
    sourceName: 'MOIL Portal',
    sourceUrl: 'https://moil.nic.in',
    sourcePortal: 'moil.nic.in',
    lastVerifiedAt: '2026-09-14',
    verificationStatus: 'VERIFIED',
    seoTitle: 'MOIL Hydraulic Roof Supports Tender 2026 | SarkarSaathi',
    seoDescription: 'Details of hydraulic roof supports and rock bolts procurement tender by MOIL Limited.',
    canonicalUrl: 'https://www.sarkarsaathi.org/tenders/moil-hydraulic-roof-supports-rock-bolts'
  }
];

export class MockTenderRepository implements ITenderRepository {
  async getAll(): Promise<TenderRecord[]> {
    return MOCK_TENDERS;
  }
  async getPaginated(params: PaginationParams, filters?: FilterParams): Promise<PaginatedResponse<TenderRecord>> {
    return { data: MOCK_TENDERS, total: MOCK_TENDERS.length, page: params.page, limit: params.limit };
  }
  async getBySlug(slug: string): Promise<TenderRecord | null> {
    return MOCK_TENDERS.find(t => t.slug === slug) || null;
  }
}
