import { OfficialSource } from './OfficialSource';

export const OfficialSourceRegistry: OfficialSource[] = [
  {
    id: 'rbi',
    name: 'Reserve Bank of India',
    authority: 'RBI',
    authorityType: 'REGULATOR',
    sourceCategory: 'REGULATOR',
    officialUrl: 'https://www.rbi.org.in/',
    sourceType: 'Official Regulator',
    scope: 'Central',
    country: 'India',
    domain: 'rbi.org.in',
    description: 'Central bank of India, regulator of monetary policy and government securities.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Weekly',
    active: true,
  },
  {
    id: 'finmin',
    name: 'Ministry of Finance',
    authority: 'Ministry of Finance',
    authorityType: 'MINISTRY',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://finmin.nic.in/',
    sourceType: 'Official Ministry Portal',
    scope: 'Central',
    country: 'India',
    domain: 'finmin.nic.in',
    description: 'Governs financial policy, savings schemes, and investment products.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'indiapost',
    name: 'India Post',
    authority: 'Department of Posts',
    authorityType: 'DEPARTMENT',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://www.indiapost.gov.in/',
    sourceType: 'Official Government Portal',
    scope: 'Central',
    country: 'India',
    domain: 'indiapost.gov.in',
    description: 'Operates small savings schemes and investment products.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'ism',
    name: 'India Semiconductor Mission',
    authority: 'MeitY',
    authorityType: 'DEPARTMENT',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://ism.gov.in/',
    sourceType: 'Official Scheme Portal',
    scope: 'Central',
    country: 'India',
    domain: 'ism.gov.in',
    description: 'Implements semiconductor and display manufacturing incentives.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'mhi',
    name: 'Ministry of Heavy Industries',
    authority: 'Ministry of Heavy Industries',
    authorityType: 'MINISTRY',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://heavyindustries.gov.in/',
    sourceType: 'Official Ministry Portal',
    scope: 'Central',
    country: 'India',
    domain: 'heavyindustries.gov.in',
    description: 'Manages PLI schemes for auto and battery industries.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'mnre',
    name: 'Ministry of New and Renewable Energy',
    authority: 'MNRE',
    authorityType: 'MINISTRY',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://mnre.gov.in/',
    sourceType: 'Official Ministry Portal',
    scope: 'Central',
    country: 'India',
    domain: 'mnre.gov.in',
    description: 'Promotes renewable energy including Green Hydrogen Mission.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'epfo',
    name: 'Employees Provident Fund Organisation',
    authority: 'EPFO',
    authorityType: 'PSU',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://www.epfindia.gov.in/',
    sourceType: 'Official Regulator',
    scope: 'Central',
    country: 'India',
    domain: 'epfindia.gov.in',
    description: 'Manages provident fund and pension schemes for employees.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'pfrda',
    name: 'Pension Fund Regulatory and Development Authority',
    authority: 'PFRDA',
    authorityType: 'REGULATOR',
    sourceCategory: 'REGULATOR',
    officialUrl: 'https://www.pfrda.org.in/',
    sourceType: 'Official Regulator',
    scope: 'Central',
    country: 'India',
    domain: 'pfrda.org.in',
    description: 'Regulates pension funds including NPS and APY.',
    verificationStatus: 'VERIFIED',
    lastVerified: '2026-09-12',
    verificationFrequency: 'Monthly',
    active: true,
  },
];
