import { OfficialSource } from './OfficialSource';

export const OfficialSourceRegistry: OfficialSource[] = [
  {
    id: 'rbi',
    name: 'Reserve Bank of India',
    authority: 'RBI',
    sourceCategory: 'REGULATOR',
    officialUrl: 'https://www.rbi.org.in/',
    jurisdiction: 'Central',
    supportedDataTypes: ['Investment Products', 'Monetary Policy Updates'],
    verificationFrequency: 'Weekly',
    active: true,
  },
  {
    id: 'mea',
    name: 'Ministry of Finance',
    authority: 'Ministry of Finance',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://finmin.nic.in/',
    jurisdiction: 'Central',
    supportedDataTypes: ['Investment Schemes', 'Investment Products'],
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'ism',
    name: 'India Semiconductor Mission',
    authority: 'MeitY',
    sourceCategory: 'CENTRAL_GOVERNMENT',
    officialUrl: 'https://ism.gov.in/',
    jurisdiction: 'Central',
    supportedDataTypes: ['Investment Schemes'],
    verificationFrequency: 'Monthly',
    active: true,
  },
  {
    id: 'cppp',
    name: 'Central Public Procurement Portal',
    authority: 'Ministry of Finance',
    sourceCategory: 'PROCUREMENT_PORTAL',
    officialUrl: 'https://eprocure.gov.in/',
    jurisdiction: 'Central',
    supportedDataTypes: ['Tenders'],
    verificationFrequency: 'Weekly',
    active: true,
  },
  {
    id: 'invest-india',
    name: 'Invest India',
    authority: 'DPIIT',
    sourceCategory: 'INVESTMENT_PORTAL',
    officialUrl: 'https://www.investindia.gov.in/',
    jurisdiction: 'Central',
    supportedDataTypes: ['Investment Opportunities', 'Investment Projects'],
    verificationFrequency: 'Monthly',
    active: true,
  },
];
